; ============================================================
;  ACS Dashboard — auto-generated by acs_parser_dashboard.py
; ============================================================

dashboard_index:
  .word dashboard_pointer_0  ; 
dashboard_index_record_length:
  .byte 2  ; each dashboard_index entry is 1 .word (2 bytes)

dashboard_pointers:
dashboard_pointer_0:
  .word dashboard_0_id              ;  id              [0,1]
  .word dashboard_0_name            ;  name            [2,3]
  .word dashboard_0_total_sim_time  ;  total_sim_time  [4,5]
  .word dashboard_0_water_level0    ;  water_level0    [6,7]
  .word dashboard_0_water_level1    ;  water_level1    [8,9]
  .word dashboard_0_water_level2    ;  water_level2    [10,11]
  .word dashboard_0_water_level3    ;  water_level3    [12,13]
dashboard_name_offset:
  .byte 2  ; (byte of dashboard_0_name in pointers)
dashboard_total_sim_time_offset:
  .byte 4  ; (byte of dashboard_0_total_sim_time in pointers)
dashboard_water_level0_offset:
  .byte 6  ; (byte of dashboard_0_water_level0 in pointers)
dashboard_water_level1_offset:
  .byte 8  ; (byte of dashboard_0_water_level1 in pointers)
dashboard_water_level2_offset:
  .byte 10  ; (byte of dashboard_0_water_level2 in pointers)
dashboard_water_level3_offset:
  .byte 12  ; (byte of dashboard_0_water_level3 in pointers)
dashboard_record_length:
  .byte 14  ; (total .word bytes per record)

; ── Dashboard 0:  ──────────────────────────
dashboard_0_id:
  .byte 0

dashboard_0_name:
  .ascii ""
  .ascii "e"

dashboard_0_total_sim_time:
  .byte $02  ; high byte  (decimal 600)
  .byte $58  ; low byte

dashboard_0_water_level0:
  .byte $00  ; high byte  (decimal 100)
  .byte $64  ; low byte

dashboard_0_water_level1:
  .byte $00  ; high byte  (decimal 200)
  .byte $C8  ; low byte

dashboard_0_water_level2:
  .byte $01  ; high byte  (decimal 400)
  .byte $90  ; low byte

dashboard_0_water_level3:
  .byte $02  ; high byte  (decimal 600)
  .byte $58  ; low byte

; ── Total dashboard count ──────────────────────────────────────
dashboard_count:
  .byte 1
