; ============================================================
;  ACS Sensors — auto-generated by acs_parser_sensors.py
; ============================================================

sensors_index:
  .word sensor_pointer_0  ; water
  .word sensor_pointer_1  ; heart
  .word sensor_pointer_2  ; flashlight
  .word sensor_pointer_3  ; timer1minuto
  .word sensor_pointer_4  ; gamePlaying
  .word sensor_pointer_5  ; timer10minutos
sensors_index_record_length:
  .byte 2  ; each sensors_index entry is 1 .word (2 bytes)

sensors_pointers:
sensor_pointer_0:
  .word sensor_0_id        ; water id        [0,1]
  .word sensor_0_name      ; water name      [2,3]
  .word sensor_0_active    ; water active    [4,5]
  .word sensor_0_dialog_on ; water dialog_on [6,7]
  .word sensor_0_dialog_off; water dialog_off[8,9]
sensor_pointer_1:
  .word sensor_1_id        ; heart id        [10,11]
  .word sensor_1_name      ; heart name      [12,13]
  .word sensor_1_active    ; heart active    [14,15]
  .word sensor_1_dialog_on ; heart dialog_on [16,17]
  .word sensor_1_dialog_off; heart dialog_off[18,19]
sensor_pointer_2:
  .word sensor_2_id        ; flashlight id        [20,21]
  .word sensor_2_name      ; flashlight name      [22,23]
  .word sensor_2_active    ; flashlight active    [24,25]
  .word sensor_2_dialog_on ; flashlight dialog_on [26,27]
  .word sensor_2_dialog_off; flashlight dialog_off[28,29]
sensor_pointer_3:
  .word sensor_3_id        ; timer1minuto id        [30,31]
  .word sensor_3_name      ; timer1minuto name      [32,33]
  .word sensor_3_active    ; timer1minuto active    [34,35]
  .word sensor_3_dialog_on ; timer1minuto dialog_on [36,37]
  .word sensor_3_dialog_off; timer1minuto dialog_off[38,39]
sensor_pointer_4:
  .word sensor_4_id        ; gamePlaying id        [40,41]
  .word sensor_4_name      ; gamePlaying name      [42,43]
  .word sensor_4_active    ; gamePlaying active    [44,45]
  .word sensor_4_dialog_on ; gamePlaying dialog_on [46,47]
  .word sensor_4_dialog_off; gamePlaying dialog_off[48,49]
sensor_pointer_5:
  .word sensor_5_id        ; timer10minutos id        [50,51]
  .word sensor_5_name      ; timer10minutos name      [52,53]
  .word sensor_5_active    ; timer10minutos active    [54,55]
  .word sensor_5_dialog_on ; timer10minutos dialog_on [56,57]
  .word sensor_5_dialog_off; timer10minutos dialog_off[58,59]
sensor_name_offset:
  .byte 2       ; (byte of sensor_0_name in sensors_pointers)
sensor_dialog_on_offset:
  .byte 6  ; (byte of sensor_0_dialog_on in sensors_pointers)
sensor_dialog_off_offset:
  .byte 8 ; (byte of sensor_0_dialog_off in sensors_pointers)
sensor_record_length:
  .byte 10     ; (total .word bytes per sensor record)

; ── Sensor 0: water ──────────────────────────
sensor_0_id:
  .byte 0

sensor_0_name:
  .ascii "water"
  .ascii "e"

sensor_0_active:
  .byte 0  ; off

sensor_0_dialog_on:
  .ascii "El agua cae siempre cae, nunca para."
  .ascii "e"

sensor_0_dialog_off:
  .ascii ""
  .ascii "e"

; ── Sensor 1: heart ──────────────────────────
sensor_1_id:
  .byte 1

sensor_1_name:
  .ascii "heart"
  .ascii "e"

sensor_1_active:
  .byte 0  ; off

sensor_1_dialog_on:
  .ascii "Tu corazón late cada vez más rápido"
  .ascii "e"

sensor_1_dialog_off:
  .ascii "Estás mas calmado"
  .ascii "e"

; ── Sensor 2: flashlight ──────────────────────────
sensor_2_id:
  .byte 2

sensor_2_name:
  .ascii "flashlight"
  .ascii "e"

sensor_2_active:
  .byte 0  ; off

sensor_2_dialog_on:
  .ascii "Prendes la linterna"
  .ascii "e"

sensor_2_dialog_off:
  .ascii "Apagas la linterna"
  .ascii "e"

; ── Sensor 3: timer1minuto ──────────────────────────
sensor_3_id:
  .byte 3

sensor_3_name:
  .ascii "timer1minuto"
  .ascii "e"

sensor_3_active:
  .byte 0  ; off

sensor_3_dialog_on:
  .ascii "El tiempo empieza a correr no debes quedarte aqui mucho tiempo"
  .ascii "e"

sensor_3_dialog_off:
  .ascii "Aqui puedes tomartelo con calma, perono mucha"
  .ascii "e"

; ── Sensor 4: gamePlaying ──────────────────────────
sensor_4_id:
  .byte 4

sensor_4_name:
  .ascii "gamePlaying"
  .ascii "e"

sensor_4_active:
  .byte 0  ; off

sensor_4_dialog_on:
  .ascii "Comienza el Juego"
  .ascii "e"

sensor_4_dialog_off:
  .ascii "Terminó el Juego"
  .ascii "e"

; ── Sensor 5: timer10minutos ──────────────────────────
sensor_5_id:
  .byte 5

sensor_5_name:
  .ascii "timer10minutos"
  .ascii "e"

sensor_5_active:
  .byte 0  ; off

sensor_5_dialog_on:
  .ascii "Tenes 10 minutos para terminar el juego"
  .ascii "e"

sensor_5_dialog_off:
  .ascii "Se acabó tu tiempo"
  .ascii "e"

; ── Total sensor count ──────────────────────────────────────
sensor_count:
  .byte 6
