; ============================================================
;  ACS Screens — auto-generated by acs_screens_to_asm.py
; ============================================================

screens_index:
  .word screen_pointer_0  ; EntradaCueva
  .word screen_pointer_1  ; cuevaIntermedia
screens_index_record_length:
  .byte 2  ; each screens_index entry is 1 .word (2 bytes)

screens_pointers:
screen_pointer_0:
  .word screen_0_id                ; EntradaCueva id                [0,1]
  .word screen_0_name              ; EntradaCueva name              [2,3]
  .word screen_0_north             ; EntradaCueva north             [4,5]
  .word screen_0_south             ; EntradaCueva south             [6,7]
  .word screen_0_east              ; EntradaCueva east              [8,9]
  .word screen_0_west              ; EntradaCueva west              [10,11]
  .word screen_0_object1           ; EntradaCueva object1           [12,13]
  .word screen_0_object2           ; EntradaCueva object2           [14,15]
  .word screen_0_object3           ; EntradaCueva object3           [16,17]
  .word screen_0_object4           ; EntradaCueva object4           [18,19]
  .word screen_0_object5           ; EntradaCueva object5           [20,21]
  .word screen_0_object6           ; EntradaCueva object6           [22,23]
  .word screen_0_puzzle1           ; EntradaCueva puzzle1           [24,25]
  .word screen_0_puzzle2           ; EntradaCueva puzzle2           [26,27]
  .word screen_0_action1           ; EntradaCueva action1           [28,29]
  .word screen_0_action2           ; EntradaCueva action2           [30,31]
  .word screen_0_action3           ; EntradaCueva action3           [32,33]
  .word screen_0_action4           ; EntradaCueva action4           [34,35]
  .word screen_0_action5           ; EntradaCueva action5           [36,37]
  .word screen_0_action6           ; EntradaCueva action6           [38,39]
  .word screen_0_description       ; EntradaCueva description       [40,41]
  .word screen_0_ascii             ; EntradaCueva ascii             [42,43]
screen_pointer_1:
  .word screen_1_id                ; cuevaIntermedia id                [44,45]
  .word screen_1_name              ; cuevaIntermedia name              [46,47]
  .word screen_1_north             ; cuevaIntermedia north             [48,49]
  .word screen_1_south             ; cuevaIntermedia south             [50,51]
  .word screen_1_east              ; cuevaIntermedia east              [52,53]
  .word screen_1_west              ; cuevaIntermedia west              [54,55]
  .word screen_1_object1           ; cuevaIntermedia object1           [56,57]
  .word screen_1_object2           ; cuevaIntermedia object2           [58,59]
  .word screen_1_object3           ; cuevaIntermedia object3           [60,61]
  .word screen_1_object4           ; cuevaIntermedia object4           [62,63]
  .word screen_1_object5           ; cuevaIntermedia object5           [64,65]
  .word screen_1_object6           ; cuevaIntermedia object6           [66,67]
  .word screen_1_puzzle1           ; cuevaIntermedia puzzle1           [68,69]
  .word screen_1_puzzle2           ; cuevaIntermedia puzzle2           [70,71]
  .word screen_1_action1           ; cuevaIntermedia action1           [72,73]
  .word screen_1_action2           ; cuevaIntermedia action2           [74,75]
  .word screen_1_action3           ; cuevaIntermedia action3           [76,77]
  .word screen_1_action4           ; cuevaIntermedia action4           [78,79]
  .word screen_1_action5           ; cuevaIntermedia action5           [80,81]
  .word screen_1_action6           ; cuevaIntermedia action6           [82,83]
  .word screen_1_description       ; cuevaIntermedia description       [84,85]
  .word screen_1_ascii             ; cuevaIntermedia ascii             [86,87]
screen_object_offset:
  .byte 12  ; (byte of screen_0_object1 in screens_pointers)
screen_puzzle_offset:
  .byte 24  ; (byte of screen_0_puzzle1 in screens_pointers)
screen_action_offset:
  .byte 28  ; (byte of screen_0_action1 in screens_pointers)
screen_description_offset:
  .byte 40  ; (byte of screen_0_description in screens_pointers)
screen_ascii_offset:
  .byte 42  ; (byte of screen_0_ascii in screens_pointers)
screen_record_length:
  .byte 44  ; (total .word bytes per screen record)

; ── Screen 0: EntradaCueva ──────────────────────────
screen_0_id:
  .byte 0

screen_0_name:
  .ascii "EntradaCueva"
  .ascii "e"

screen_0_north:
  .byte 255  ; none

screen_0_south:
  .byte 255  ; none

screen_0_east:
  .byte 1  ; cuevaIntermedia

screen_0_west:
  .byte 255  ; none

screen_0_object1:
  .byte 1  ; encendedor

screen_0_object2:
  .byte 0  ; vela

screen_0_object3:
  .byte 3  ; llave

screen_0_object4:
  .byte 4  ; puerta

screen_0_object5:
  .byte 255  ; none

screen_0_object6:
  .byte 255  ; none

screen_0_puzzle1:
  .byte 0  ; prender_vela

screen_0_puzzle2:
  .byte 1  ; abrir_puerta_llave

screen_0_action1:
  .byte 1  ; mirar

screen_0_action2:
  .byte 2  ; usar

screen_0_action3:
  .byte 0  ; ir

screen_0_action4:
  .byte 255  ; none

screen_0_action5:
  .byte 255  ; none

screen_0_action6:
  .byte 255  ; none

screen_0_description:
  .ascii "Estas en la entrada de la cueva"
  .ascii "e"

screen_0_ascii:
  .ascii "/////------------------------------------\\\\\\n//------------------------------------------\\\n//------------------------------------------\\\n//------------------------------------------\\\n"
  .ascii "e"

; ── Screen 1: cuevaIntermedia ──────────────────────────
screen_1_id:
  .byte 1

screen_1_name:
  .ascii "cuevaIntermedia"
  .ascii "e"

screen_1_north:
  .byte 255  ; none

screen_1_south:
  .byte 255  ; none

screen_1_east:
  .byte 255  ; none

screen_1_west:
  .byte 0  ; EntradaCueva

screen_1_object1:
  .byte 0  ; vela

screen_1_object2:
  .byte 1  ; encendedor

screen_1_object3:
  .byte 255  ; none

screen_1_object4:
  .byte 255  ; none

screen_1_object5:
  .byte 255  ; none

screen_1_object6:
  .byte 255  ; none

screen_1_puzzle1:
  .byte 255  ; none

screen_1_puzzle2:
  .byte 255  ; none

screen_1_action1:
  .byte 1  ; mirar

screen_1_action2:
  .byte 255  ; none

screen_1_action3:
  .byte 255  ; none

screen_1_action4:
  .byte 255  ; none

screen_1_action5:
  .byte 255  ; none

screen_1_action6:
  .byte 255  ; none

screen_1_description:
  .ascii "estas cada vez mas profundo en la cueva, aca hay muchas estalactitas"
  .ascii "e"

screen_1_ascii:
  .ascii ""
  .ascii "e"

; ── Total screen count ──────────────────────────────────────
screen_count:
  .byte 2
