; ============================================================
;  ACS Screens — auto-generated by acs_screens_to_asm.py
; ============================================================

screens_pointers:
  .word screen_0_id          ; EntradaCueva id          [0,1]
  .word screen_0_name        ; EntradaCueva name        [2,3]
  .word screen_0_north       ; EntradaCueva north       [4,5]
  .word screen_0_south       ; EntradaCueva south       [6,7]
  .word screen_0_east        ; EntradaCueva east        [8,9]
  .word screen_0_west        ; EntradaCueva west        [10,11]
  .word screen_0_object1     ; EntradaCueva object1     [12,13]
  .word screen_0_object2     ; EntradaCueva object2     [14,15]
  .word screen_0_object3     ; EntradaCueva object3     [16,17]
  .word screen_0_object4     ; EntradaCueva object4     [18,19]
  .word screen_0_object5     ; EntradaCueva object5     [20,21]
  .word screen_0_object6     ; EntradaCueva object6     [22,23]
  .word screen_0_puzzle1     ; EntradaCueva puzzle1     [24,25]
  .word screen_0_puzzle2     ; EntradaCueva puzzle2     [26,27]
  .word screen_0_description ; EntradaCueva description [28,29]
  .word screen_0_ascii       ; EntradaCueva ascii       [30,31]
  .word screen_1_id          ; cuevaIntermedia id          [32,33]
  .word screen_1_name        ; cuevaIntermedia name        [34,35]
  .word screen_1_north       ; cuevaIntermedia north       [36,37]
  .word screen_1_south       ; cuevaIntermedia south       [38,39]
  .word screen_1_east        ; cuevaIntermedia east        [40,41]
  .word screen_1_west        ; cuevaIntermedia west        [42,43]
  .word screen_1_object1     ; cuevaIntermedia object1     [44,45]
  .word screen_1_object2     ; cuevaIntermedia object2     [46,47]
  .word screen_1_object3     ; cuevaIntermedia object3     [48,49]
  .word screen_1_object4     ; cuevaIntermedia object4     [50,51]
  .word screen_1_object5     ; cuevaIntermedia object5     [52,53]
  .word screen_1_object6     ; cuevaIntermedia object6     [54,55]
  .word screen_1_puzzle1     ; cuevaIntermedia puzzle1     [56,57]
  .word screen_1_puzzle2     ; cuevaIntermedia puzzle2     [58,59]
  .word screen_1_description ; cuevaIntermedia description [60,61]
  .word screen_1_ascii       ; cuevaIntermedia ascii       [62,63]

; ── Screen 0: EntradaCueva ──────────────────────────
screen_0_id:
  .byte 0

screen_0_name:
  .ascii "EntradaCueva"
  .ascii "e"

screen_0_north:
  .byte 255  ; none

screen_0_south:
  .byte 255  ; none

screen_0_east:
  .byte 1  ; cuevaIntermedia

screen_0_west:
  .byte 255  ; none

screen_0_object1:
  .byte 1  ; encendedor

screen_0_object2:
  .byte 0  ; vela

screen_0_object3:
  .byte 3  ; llave

screen_0_object4:
  .byte 4  ; puerta

screen_0_object5:
  .byte 255  ; none

screen_0_object6:
  .byte 255  ; none

screen_0_puzzle1:
  .byte 0  ; prender_vela

screen_0_puzzle2:
  .byte 1  ; abrir_puerta_llave

screen_0_description:
  .ascii "Estas en la entrada de la cueva"
  .ascii "e"

screen_0_ascii:
  .ascii "/////------------------------------------\\\\\\n//------------------------------------------\\\n//------------------------------------------\\\n//------------------------------------------\\\n"
  .ascii "e"

; ── Screen 1: cuevaIntermedia ──────────────────────────
screen_1_id:
  .byte 1

screen_1_name:
  .ascii "cuevaIntermedia"
  .ascii "e"

screen_1_north:
  .byte 255  ; none

screen_1_south:
  .byte 255  ; none

screen_1_east:
  .byte 255  ; none

screen_1_west:
  .byte 0  ; EntradaCueva

screen_1_object1:
  .byte 0  ; vela

screen_1_object2:
  .byte 1  ; encendedor

screen_1_object3:
  .byte 255  ; none

screen_1_object4:
  .byte 255  ; none

screen_1_object5:
  .byte 255  ; none

screen_1_object6:
  .byte 255  ; none

screen_1_puzzle1:
  .byte 255  ; none

screen_1_puzzle2:
  .byte 255  ; none

screen_1_description:
  .ascii "estas cada vez mas profundo en la cueva, aca hay muchas estalactitas"
  .ascii "e"

screen_1_ascii:
  .ascii ""
  .ascii "e"

; ── Total screen count ──────────────────────────────────────
screen_count:
  .byte 2
