import json
import os

JSON_FILE = "acs_actions.json"
ASM_FILE  = "acs_actions.asm"


def sanitize_id(name):
    """Turn an action name into a safe ASM label prefix (lowercase, spaces→_)."""
    return name.strip().lower().replace(" ", "_").replace("-", "_")


def to_asm(actions):
    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Actions — auto-generated by acs_actions_to_asm.py")
    lines.append("; ============================================================")
    lines.append("")

    # ── Pointer table ────────────────────────────────────────
    lines.append("actions_pointers:")
    offset = 0
    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        label  = f"action_{act_id}"
        name   = act.get("Name", key)
        lines.append(f"  .word {label}_id     ; {name} id     [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_name   ; {name} name   [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_sensor ; {name} sensor [{offset},{offset+1}]") ; offset += 2
    lines.append("")

    for index, (key, act) in enumerate(actions.items()):
        act_id     = act.get("ID",     str(index)).strip()
        label      = f"action_{act_id}"
        name_str   = act.get("Name",   "").replace('"', '\\"')
        sensor_str = act.get("Sensor", "").replace('"', '\\"')

        lines.append(f"; ── Action {act_id}: {act.get('Name', key)} ──────────────────────────")

        # ID
        lines.append(f"{label}_id:")
        lines.append(f"  .byte {act_id}")
        lines.append("")

        # Name
        lines.append(f"{label}_name:")
        lines.append(f'  .ascii "{name_str}"')
        lines.append('  .ascii "e"')
        lines.append("")

        # Sensor
        lines.append(f"{label}_sensor:")
        lines.append(f'  .ascii "{sensor_str}"')
        lines.append('  .ascii "e"')
        lines.append("")

    # ── Action count constant ─────────────────────────────────
    lines.append("; ── Total action count ──────────────────────────────────────")
    lines.append("action_count:")
    lines.append(f"  .byte {len(actions)}")
    lines.append("")

    return "\n".join(lines)


def main():
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found. Run the ACS editor first.")
        return

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        actions = json.load(f)

    if not actions:
        print("[WARNING] No actions found in the JSON file.")
        return

    actions = dict(sorted(actions.items(), key=lambda item: int(item[1].get("ID", 0))))

    asm = to_asm(actions)

    with open(ASM_FILE, "w", encoding="utf-8") as f:
        f.write(asm)

    print(f"[OK] Generated '{ASM_FILE}' with {len(actions)} action(s).")
    print("-" * 50)
    print(asm)


if __name__ == "__main__":
    main()