import json
import os
import sys
from acs_compression import (
    build_shared_dictionary, emit_dictionary_asm,
    emit_compressed_field_asm, compute_stats,
    SCREEN_STRING_FIELDS as STRING_FIELDS
)

JSON_FILE    = "acs_screens.json"
PUZZLES_FILE = "acs_puzzles.json"
ACTIONS_FILE = "acs_actions.json"
ASM_FILE     = "acs_screens.asm"


def load_name_to_id(filepath, id_field="ID", name_field="Name"):
    if not os.path.exists(filepath):
        print(f"[ERROR] '{filepath}' not found.")
        sys.exit(1)
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    mapping = {}
    for entry in data.values():
        name = entry.get(name_field, "").strip()
        eid  = entry.get(id_field,   "").strip()
        if name and eid:
            mapping[name] = int(eid)
    return mapping


def resolve(name, mapping, label, optional=False):
    name = name.strip()
    if not name:
        return 255
    if name not in mapping:
        print(f"[ERROR] '{name}' not found in {label}. Available: {list(mapping.keys())}")
        sys.exit(1)
    return mapping[name]


def ascii_lines(text):
    segments = text.split("\n")
    out = []
    for si, seg in enumerate(segments):
        if si < len(segments) - 1:
            seg += "\\n"
        while len(seg) > 80:
            out.append(f'  .ascii "{seg[:80]}"')
            seg = seg[80:]
        if seg:
            out.append(f'  .ascii "{seg}"')
    return out


def to_asm(screens, action_ids):
    word_to_id, id_to_word, freq = build_shared_dictionary()

    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Screens — auto-generated by acs_screens_to_asm.py")
    lines.append("; ============================================================")
    lines.append("")

    lines.extend(emit_dictionary_asm(id_to_word, freq))

    lines.append("screens_index:")
    for index, (key, scr) in enumerate(screens.items()):
        scr_id = scr.get("ID", str(index)).strip()
        name   = scr.get("Name", key)
        lines.append(f"  .word screen_pointers_{scr_id}  ; {name}")
    lines.append(f"screens_index_record_length:")
    lines.append(f"  .byte 2")
    lines.append("")

    lines.append("screens_pointers:")
    offset = 0
    screen_0_offsets = {}
    screen_0_record_length = None

    pointer_fields = [
        "id", "name", "action1", "action2", "action3", "action4",
        "description", "ascii", "flashlight_on", "flashlight_off",
        "enemy_probability", "is_secret_screen", "is_end_screen",
        "description_compressed", "flashlight_on_compressed", "flashlight_off_compressed",
    ]

    for index, (key, scr) in enumerate(screens.items()):
        scr_id = scr.get("ID", str(index)).strip()
        label  = f"screen_{scr_id}"
        name   = scr.get("Name", key)
        start_offset = offset

        lines.append(f"screen_pointers_{scr_id}:")
        for fname in pointer_fields:
            pad = " " * max(0, 35 - len(fname))
            lines.append(f"  .word {label}_{fname}{pad}; {name} {fname} [{offset},{offset+1}]")
            if index == 0:
                screen_0_offsets[fname] = offset
            offset += 2

        if index == 0:
            screen_0_record_length = offset - start_offset

    offset_labels = {
        "action": "action1", "description": "description", "ascii": "ascii",
        "flashlight_on": "flashlight_on", "flashlight_off": "flashlight_off",
        "enemy_probability": "enemy_probability", "is_secret_screen": "is_secret_screen",
        "is_end_screen": "is_end_screen", "description_compressed": "description_compressed",
        "flashlight_on_compressed": "flashlight_on_compressed",
        "flashlight_off_compressed": "flashlight_off_compressed",
    }
    for label_name, field_key in offset_labels.items():
        lines.append(f"screen_{label_name}_offset:")
        lines.append(f"  .byte {screen_0_offsets[field_key]}")
    lines.append(f"screen_record_length:")
    lines.append(f"  .byte {screen_0_record_length}")
    lines.append("")

    for index, (key, scr) in enumerate(screens.items()):
        scr_id    = scr.get("ID", str(index)).strip()
        label     = f"screen_{scr_id}"
        name_str  = scr.get("Name",        "").replace('"', '\\"')
        desc_str  = scr.get("Description", "").replace('"', '\\"')
        ascii_str = scr.get("AsciiDrawing","").replace('"', '\\"')
        desc_raw  = scr.get("Description", "")
        flon_raw  = scr.get("FlashlightOn", "")
        floff_raw = scr.get("FlashlightOff", "")

        act_ids = [
            resolve(scr.get(f"Action{i}", ""), action_ids, ACTIONS_FILE, optional=True)
            for i in range(1, 5)
        ]

        lines.append(f"; ── Screen {scr_id}: {scr.get('Name', key)} ──────────────────────────")

        lines.append(f"{label}_id:")
        lines.append(f"  .byte {scr_id}")
        lines.append("")

        lines.append(f"{label}_name:")
        lines.extend(ascii_lines(name_str))
        lines.append("")

        for i, aid in enumerate(act_ids, 1):
            act_name = scr.get(f"Action{i}", "") or "none"
            lines.append(f"{label}_action{i}:")
            lines.append(f"  .byte {aid}  ; {act_name}")
            lines.append("")

        lines.append(f"{label}_description:")
        for aline in ascii_lines(desc_str):
            lines.append(f"  ;{aline.lstrip()}")
        lines.append("")

        lines.extend(emit_compressed_field_asm(
            f"{label}_description_compressed", desc_raw, word_to_id, id_to_word))

        lines.append(f"{label}_ascii:")
        lines.extend(ascii_lines(ascii_str))
        lines.append("")

        flashlight_on_str = scr.get("FlashlightOn", "").replace('"', '\\"')
        lines.append(f"{label}_flashlight_on:")
        for aline in ascii_lines(flashlight_on_str):
            lines.append(f"  ;{aline.lstrip()}")
        lines.append("")

        lines.extend(emit_compressed_field_asm(
            f"{label}_flashlight_on_compressed", flon_raw, word_to_id, id_to_word))

        flashlight_off_str = scr.get("FlashlightOff", "").replace('"', '\\"')
        lines.append(f"{label}_flashlight_off:")
        for aline in ascii_lines(flashlight_off_str):
            lines.append(f"  ;{aline.lstrip()}")
        lines.append("")

        lines.extend(emit_compressed_field_asm(
            f"{label}_flashlight_off_compressed", floff_raw, word_to_id, id_to_word))

        try:
            enemy_prob_val = max(0, min(255, int(scr.get("EnemyProbability", 0))))
        except (ValueError, TypeError):
            enemy_prob_val = 0
        lines.append(f"{label}_enemy_probability:")
        lines.append(f"  .byte {enemy_prob_val}")
        lines.append("")

        try:
            is_secret_val = 1 if int(scr.get("IsSecretScreen", 0)) else 0
        except (ValueError, TypeError):
            is_secret_val = 0
        lines.append(f"{label}_is_secret_screen:")
        lines.append(f"  .byte {is_secret_val}  ; {'yes' if is_secret_val else 'no'}")
        lines.append("")

        try:
            is_end_val = 1 if int(scr.get("IsEndScreen", 0)) else 0
        except (ValueError, TypeError):
            is_end_val = 0
        lines.append(f"{label}_is_end_screen:")
        lines.append(f"  .byte {is_end_val}  ; {'yes' if is_end_val else 'no'}")
        lines.append("")

    lines.append("screen_count:")
    lines.append(f"  .byte {len(screens)}")
    lines.append("")

    secret_count = sum(1 for scr in screens.values()
                       if int(scr.get("IsSecretScreen", 0)))
    lines.append("screens_with_secrets:")
    lines.append(f"  .byte {secret_count}")
    lines.append("")

    texts = [scr.get(f, "") for scr in screens.values() for f in STRING_FIELDS if scr.get(f, "").strip()]
    total_orig, total_comp, dict_bytes = compute_stats(texts, word_to_id)
    net = total_comp + dict_bytes
    savings = total_orig - net
    pct = (savings / total_orig * 100) if total_orig > 0 else 0
    lines.append("; ── Compression stats (screens only, shared dict) ──────────")
    lines.append(f";  Unique tokens in shared dictionary: {len(word_to_id)}")
    lines.append(f";  Screen original string bytes: {total_orig}")
    lines.append(f";  Screen compressed bytes (1-byte IDs): {total_comp}")
    lines.append(f";  Dictionary overhead (shared, paid once): {dict_bytes}")
    lines.append(f";  Net: {net} vs {total_orig}")
    lines.append(f";  Savings: {savings} bytes ({pct:.1f}%)")
    lines.append("")

    return "\n".join(lines)


def main():
    action_ids = load_name_to_id(ACTIONS_FILE, id_field="ID", name_field="Name")
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found.")
        return
    with open(JSON_FILE, "r", encoding="utf-8") as f:
        screens = json.load(f)
    if not screens:
        print("[WARNING] No screens found.")
        return
    screens = dict(sorted(screens.items(), key=lambda item: int(item[1].get("ID", 0))))
    asm = to_asm(screens, action_ids)
    with open(ASM_FILE, "w", encoding="utf-8") as f:
        f.write(asm)
    print(f"[OK] Generated '{ASM_FILE}' with {len(screens)} screen(s).")


if __name__ == "__main__":
    main()
