; ============================================================
;  ACS Screens — auto-generated by acs_screens_to_asm.py
; ============================================================

screens_index:
  .word screen_pointers_0  ; StartScreen
  .word screen_pointers_1  ; S01P01
  .word screen_pointers_2  ; S01P02
  .word screen_pointers_3  ; S01P03
  .word screen_pointers_4  ; S01P04
  .word screen_pointers_5  ; S01P05
  .word screen_pointers_6  ; S01P06
  .word screen_pointers_7  ; S02P01
  .word screen_pointers_8  ; S02P02
  .word screen_pointers_9  ; S02P03
  .word screen_pointers_10  ; S02P04
  .word screen_pointers_11  ; S02P05
  .word screen_pointers_12  ; S02P06
  .word screen_pointers_13  ; S02P07
  .word screen_pointers_14  ; S03P01
  .word screen_pointers_15  ; S03P02
  .word screen_pointers_16  ; S03P03
  .word screen_pointers_17  ; S03P04
  .word screen_pointers_18  ; S03P05
  .word screen_pointers_19  ; S03P06
  .word screen_pointers_20  ; S04P01
  .word screen_pointers_21  ; S04P02
  .word screen_pointers_22  ; S04P03
  .word screen_pointers_23  ; S04P04
  .word screen_pointers_24  ; S05P01
  .word screen_pointers_25  ; S05P02
  .word screen_pointers_26  ; S05P03
  .word screen_pointers_27  ; S05P04
  .word screen_pointers_28  ; S05P05
  .word screen_pointers_29  ; S06P01
  .word screen_pointers_30  ; S06P02
  .word screen_pointers_31  ; S06P03
  .word screen_pointers_32  ; S07P01
  .word screen_pointers_33  ; S07P02
  .word screen_pointers_34  ; S07P03
  .word screen_pointers_35  ; S07P04
  .word screen_pointers_36  ; S07P05
  .word screen_pointers_37  ; S07P06
  .word screen_pointers_38  ; FINAL
  .word screen_pointers_39  ; EndScreenSimulationTimeisUp
  .word screen_pointers_40  ; endScreenByEnemy
  .word screen_pointers_41  ; endScreenByActionFailed
screens_index_record_length:
  .byte 2  ; each screens_index entry is 1 .word (2 bytes)

screens_pointers:
screen_pointers_0:
  .word screen_0_id                ; StartScreen id                [0,1]
  .word screen_0_name              ; StartScreen name              [2,3]
  .word screen_0_action1           ; StartScreen action1           [4,5]
  .word screen_0_action2           ; StartScreen action2           [6,7]
  .word screen_0_action3           ; StartScreen action3           [8,9]
  .word screen_0_action4           ; StartScreen action4           [10,11]
  .word screen_0_description       ; StartScreen description       [12,13]
  .word screen_0_ascii             ; StartScreen ascii             [14,15]
  .word screen_0_flashlight_on     ; StartScreen flashlight_on     [16,17]
  .word screen_0_flashlight_off    ; StartScreen flashlight_off    [18,19]
  .word screen_0_enemy_probability ; StartScreen enemy_probability [20,21]
  .word screen_0_is_secret_screen  ; StartScreen is_secret_screen  [22,23]
  .word screen_0_is_end_screen     ; StartScreen is_end_screen     [24,25]
screen_pointers_1:
  .word screen_1_id                ; S01P01 id                [26,27]
  .word screen_1_name              ; S01P01 name              [28,29]
  .word screen_1_action1           ; S01P01 action1           [30,31]
  .word screen_1_action2           ; S01P01 action2           [32,33]
  .word screen_1_action3           ; S01P01 action3           [34,35]
  .word screen_1_action4           ; S01P01 action4           [36,37]
  .word screen_1_description       ; S01P01 description       [38,39]
  .word screen_1_ascii             ; S01P01 ascii             [40,41]
  .word screen_1_flashlight_on     ; S01P01 flashlight_on     [42,43]
  .word screen_1_flashlight_off    ; S01P01 flashlight_off    [44,45]
  .word screen_1_enemy_probability ; S01P01 enemy_probability [46,47]
  .word screen_1_is_secret_screen  ; S01P01 is_secret_screen  [48,49]
  .word screen_1_is_end_screen     ; S01P01 is_end_screen     [50,51]
screen_pointers_2:
  .word screen_2_id                ; S01P02 id                [52,53]
  .word screen_2_name              ; S01P02 name              [54,55]
  .word screen_2_action1           ; S01P02 action1           [56,57]
  .word screen_2_action2           ; S01P02 action2           [58,59]
  .word screen_2_action3           ; S01P02 action3           [60,61]
  .word screen_2_action4           ; S01P02 action4           [62,63]
  .word screen_2_description       ; S01P02 description       [64,65]
  .word screen_2_ascii             ; S01P02 ascii             [66,67]
  .word screen_2_flashlight_on     ; S01P02 flashlight_on     [68,69]
  .word screen_2_flashlight_off    ; S01P02 flashlight_off    [70,71]
  .word screen_2_enemy_probability ; S01P02 enemy_probability [72,73]
  .word screen_2_is_secret_screen  ; S01P02 is_secret_screen  [74,75]
  .word screen_2_is_end_screen     ; S01P02 is_end_screen     [76,77]
screen_pointers_3:
  .word screen_3_id                ; S01P03 id                [78,79]
  .word screen_3_name              ; S01P03 name              [80,81]
  .word screen_3_action1           ; S01P03 action1           [82,83]
  .word screen_3_action2           ; S01P03 action2           [84,85]
  .word screen_3_action3           ; S01P03 action3           [86,87]
  .word screen_3_action4           ; S01P03 action4           [88,89]
  .word screen_3_description       ; S01P03 description       [90,91]
  .word screen_3_ascii             ; S01P03 ascii             [92,93]
  .word screen_3_flashlight_on     ; S01P03 flashlight_on     [94,95]
  .word screen_3_flashlight_off    ; S01P03 flashlight_off    [96,97]
  .word screen_3_enemy_probability ; S01P03 enemy_probability [98,99]
  .word screen_3_is_secret_screen  ; S01P03 is_secret_screen  [100,101]
  .word screen_3_is_end_screen     ; S01P03 is_end_screen     [102,103]
screen_pointers_4:
  .word screen_4_id                ; S01P04 id                [104,105]
  .word screen_4_name              ; S01P04 name              [106,107]
  .word screen_4_action1           ; S01P04 action1           [108,109]
  .word screen_4_action2           ; S01P04 action2           [110,111]
  .word screen_4_action3           ; S01P04 action3           [112,113]
  .word screen_4_action4           ; S01P04 action4           [114,115]
  .word screen_4_description       ; S01P04 description       [116,117]
  .word screen_4_ascii             ; S01P04 ascii             [118,119]
  .word screen_4_flashlight_on     ; S01P04 flashlight_on     [120,121]
  .word screen_4_flashlight_off    ; S01P04 flashlight_off    [122,123]
  .word screen_4_enemy_probability ; S01P04 enemy_probability [124,125]
  .word screen_4_is_secret_screen  ; S01P04 is_secret_screen  [126,127]
  .word screen_4_is_end_screen     ; S01P04 is_end_screen     [128,129]
screen_pointers_5:
  .word screen_5_id                ; S01P05 id                [130,131]
  .word screen_5_name              ; S01P05 name              [132,133]
  .word screen_5_action1           ; S01P05 action1           [134,135]
  .word screen_5_action2           ; S01P05 action2           [136,137]
  .word screen_5_action3           ; S01P05 action3           [138,139]
  .word screen_5_action4           ; S01P05 action4           [140,141]
  .word screen_5_description       ; S01P05 description       [142,143]
  .word screen_5_ascii             ; S01P05 ascii             [144,145]
  .word screen_5_flashlight_on     ; S01P05 flashlight_on     [146,147]
  .word screen_5_flashlight_off    ; S01P05 flashlight_off    [148,149]
  .word screen_5_enemy_probability ; S01P05 enemy_probability [150,151]
  .word screen_5_is_secret_screen  ; S01P05 is_secret_screen  [152,153]
  .word screen_5_is_end_screen     ; S01P05 is_end_screen     [154,155]
screen_pointers_6:
  .word screen_6_id                ; S01P06 id                [156,157]
  .word screen_6_name              ; S01P06 name              [158,159]
  .word screen_6_action1           ; S01P06 action1           [160,161]
  .word screen_6_action2           ; S01P06 action2           [162,163]
  .word screen_6_action3           ; S01P06 action3           [164,165]
  .word screen_6_action4           ; S01P06 action4           [166,167]
  .word screen_6_description       ; S01P06 description       [168,169]
  .word screen_6_ascii             ; S01P06 ascii             [170,171]
  .word screen_6_flashlight_on     ; S01P06 flashlight_on     [172,173]
  .word screen_6_flashlight_off    ; S01P06 flashlight_off    [174,175]
  .word screen_6_enemy_probability ; S01P06 enemy_probability [176,177]
  .word screen_6_is_secret_screen  ; S01P06 is_secret_screen  [178,179]
  .word screen_6_is_end_screen     ; S01P06 is_end_screen     [180,181]
screen_pointers_7:
  .word screen_7_id                ; S02P01 id                [182,183]
  .word screen_7_name              ; S02P01 name              [184,185]
  .word screen_7_action1           ; S02P01 action1           [186,187]
  .word screen_7_action2           ; S02P01 action2           [188,189]
  .word screen_7_action3           ; S02P01 action3           [190,191]
  .word screen_7_action4           ; S02P01 action4           [192,193]
  .word screen_7_description       ; S02P01 description       [194,195]
  .word screen_7_ascii             ; S02P01 ascii             [196,197]
  .word screen_7_flashlight_on     ; S02P01 flashlight_on     [198,199]
  .word screen_7_flashlight_off    ; S02P01 flashlight_off    [200,201]
  .word screen_7_enemy_probability ; S02P01 enemy_probability [202,203]
  .word screen_7_is_secret_screen  ; S02P01 is_secret_screen  [204,205]
  .word screen_7_is_end_screen     ; S02P01 is_end_screen     [206,207]
screen_pointers_8:
  .word screen_8_id                ; S02P02 id                [208,209]
  .word screen_8_name              ; S02P02 name              [210,211]
  .word screen_8_action1           ; S02P02 action1           [212,213]
  .word screen_8_action2           ; S02P02 action2           [214,215]
  .word screen_8_action3           ; S02P02 action3           [216,217]
  .word screen_8_action4           ; S02P02 action4           [218,219]
  .word screen_8_description       ; S02P02 description       [220,221]
  .word screen_8_ascii             ; S02P02 ascii             [222,223]
  .word screen_8_flashlight_on     ; S02P02 flashlight_on     [224,225]
  .word screen_8_flashlight_off    ; S02P02 flashlight_off    [226,227]
  .word screen_8_enemy_probability ; S02P02 enemy_probability [228,229]
  .word screen_8_is_secret_screen  ; S02P02 is_secret_screen  [230,231]
  .word screen_8_is_end_screen     ; S02P02 is_end_screen     [232,233]
screen_pointers_9:
  .word screen_9_id                ; S02P03 id                [234,235]
  .word screen_9_name              ; S02P03 name              [236,237]
  .word screen_9_action1           ; S02P03 action1           [238,239]
  .word screen_9_action2           ; S02P03 action2           [240,241]
  .word screen_9_action3           ; S02P03 action3           [242,243]
  .word screen_9_action4           ; S02P03 action4           [244,245]
  .word screen_9_description       ; S02P03 description       [246,247]
  .word screen_9_ascii             ; S02P03 ascii             [248,249]
  .word screen_9_flashlight_on     ; S02P03 flashlight_on     [250,251]
  .word screen_9_flashlight_off    ; S02P03 flashlight_off    [252,253]
  .word screen_9_enemy_probability ; S02P03 enemy_probability [254,255]
  .word screen_9_is_secret_screen  ; S02P03 is_secret_screen  [256,257]
  .word screen_9_is_end_screen     ; S02P03 is_end_screen     [258,259]
screen_pointers_10:
  .word screen_10_id                ; S02P04 id                [260,261]
  .word screen_10_name              ; S02P04 name              [262,263]
  .word screen_10_action1           ; S02P04 action1           [264,265]
  .word screen_10_action2           ; S02P04 action2           [266,267]
  .word screen_10_action3           ; S02P04 action3           [268,269]
  .word screen_10_action4           ; S02P04 action4           [270,271]
  .word screen_10_description       ; S02P04 description       [272,273]
  .word screen_10_ascii             ; S02P04 ascii             [274,275]
  .word screen_10_flashlight_on     ; S02P04 flashlight_on     [276,277]
  .word screen_10_flashlight_off    ; S02P04 flashlight_off    [278,279]
  .word screen_10_enemy_probability ; S02P04 enemy_probability [280,281]
  .word screen_10_is_secret_screen  ; S02P04 is_secret_screen  [282,283]
  .word screen_10_is_end_screen     ; S02P04 is_end_screen     [284,285]
screen_pointers_11:
  .word screen_11_id                ; S02P05 id                [286,287]
  .word screen_11_name              ; S02P05 name              [288,289]
  .word screen_11_action1           ; S02P05 action1           [290,291]
  .word screen_11_action2           ; S02P05 action2           [292,293]
  .word screen_11_action3           ; S02P05 action3           [294,295]
  .word screen_11_action4           ; S02P05 action4           [296,297]
  .word screen_11_description       ; S02P05 description       [298,299]
  .word screen_11_ascii             ; S02P05 ascii             [300,301]
  .word screen_11_flashlight_on     ; S02P05 flashlight_on     [302,303]
  .word screen_11_flashlight_off    ; S02P05 flashlight_off    [304,305]
  .word screen_11_enemy_probability ; S02P05 enemy_probability [306,307]
  .word screen_11_is_secret_screen  ; S02P05 is_secret_screen  [308,309]
  .word screen_11_is_end_screen     ; S02P05 is_end_screen     [310,311]
screen_pointers_12:
  .word screen_12_id                ; S02P06 id                [312,313]
  .word screen_12_name              ; S02P06 name              [314,315]
  .word screen_12_action1           ; S02P06 action1           [316,317]
  .word screen_12_action2           ; S02P06 action2           [318,319]
  .word screen_12_action3           ; S02P06 action3           [320,321]
  .word screen_12_action4           ; S02P06 action4           [322,323]
  .word screen_12_description       ; S02P06 description       [324,325]
  .word screen_12_ascii             ; S02P06 ascii             [326,327]
  .word screen_12_flashlight_on     ; S02P06 flashlight_on     [328,329]
  .word screen_12_flashlight_off    ; S02P06 flashlight_off    [330,331]
  .word screen_12_enemy_probability ; S02P06 enemy_probability [332,333]
  .word screen_12_is_secret_screen  ; S02P06 is_secret_screen  [334,335]
  .word screen_12_is_end_screen     ; S02P06 is_end_screen     [336,337]
screen_pointers_13:
  .word screen_13_id                ; S02P07 id                [338,339]
  .word screen_13_name              ; S02P07 name              [340,341]
  .word screen_13_action1           ; S02P07 action1           [342,343]
  .word screen_13_action2           ; S02P07 action2           [344,345]
  .word screen_13_action3           ; S02P07 action3           [346,347]
  .word screen_13_action4           ; S02P07 action4           [348,349]
  .word screen_13_description       ; S02P07 description       [350,351]
  .word screen_13_ascii             ; S02P07 ascii             [352,353]
  .word screen_13_flashlight_on     ; S02P07 flashlight_on     [354,355]
  .word screen_13_flashlight_off    ; S02P07 flashlight_off    [356,357]
  .word screen_13_enemy_probability ; S02P07 enemy_probability [358,359]
  .word screen_13_is_secret_screen  ; S02P07 is_secret_screen  [360,361]
  .word screen_13_is_end_screen     ; S02P07 is_end_screen     [362,363]
screen_pointers_14:
  .word screen_14_id                ; S03P01 id                [364,365]
  .word screen_14_name              ; S03P01 name              [366,367]
  .word screen_14_action1           ; S03P01 action1           [368,369]
  .word screen_14_action2           ; S03P01 action2           [370,371]
  .word screen_14_action3           ; S03P01 action3           [372,373]
  .word screen_14_action4           ; S03P01 action4           [374,375]
  .word screen_14_description       ; S03P01 description       [376,377]
  .word screen_14_ascii             ; S03P01 ascii             [378,379]
  .word screen_14_flashlight_on     ; S03P01 flashlight_on     [380,381]
  .word screen_14_flashlight_off    ; S03P01 flashlight_off    [382,383]
  .word screen_14_enemy_probability ; S03P01 enemy_probability [384,385]
  .word screen_14_is_secret_screen  ; S03P01 is_secret_screen  [386,387]
  .word screen_14_is_end_screen     ; S03P01 is_end_screen     [388,389]
screen_pointers_15:
  .word screen_15_id                ; S03P02 id                [390,391]
  .word screen_15_name              ; S03P02 name              [392,393]
  .word screen_15_action1           ; S03P02 action1           [394,395]
  .word screen_15_action2           ; S03P02 action2           [396,397]
  .word screen_15_action3           ; S03P02 action3           [398,399]
  .word screen_15_action4           ; S03P02 action4           [400,401]
  .word screen_15_description       ; S03P02 description       [402,403]
  .word screen_15_ascii             ; S03P02 ascii             [404,405]
  .word screen_15_flashlight_on     ; S03P02 flashlight_on     [406,407]
  .word screen_15_flashlight_off    ; S03P02 flashlight_off    [408,409]
  .word screen_15_enemy_probability ; S03P02 enemy_probability [410,411]
  .word screen_15_is_secret_screen  ; S03P02 is_secret_screen  [412,413]
  .word screen_15_is_end_screen     ; S03P02 is_end_screen     [414,415]
screen_pointers_16:
  .word screen_16_id                ; S03P03 id                [416,417]
  .word screen_16_name              ; S03P03 name              [418,419]
  .word screen_16_action1           ; S03P03 action1           [420,421]
  .word screen_16_action2           ; S03P03 action2           [422,423]
  .word screen_16_action3           ; S03P03 action3           [424,425]
  .word screen_16_action4           ; S03P03 action4           [426,427]
  .word screen_16_description       ; S03P03 description       [428,429]
  .word screen_16_ascii             ; S03P03 ascii             [430,431]
  .word screen_16_flashlight_on     ; S03P03 flashlight_on     [432,433]
  .word screen_16_flashlight_off    ; S03P03 flashlight_off    [434,435]
  .word screen_16_enemy_probability ; S03P03 enemy_probability [436,437]
  .word screen_16_is_secret_screen  ; S03P03 is_secret_screen  [438,439]
  .word screen_16_is_end_screen     ; S03P03 is_end_screen     [440,441]
screen_pointers_17:
  .word screen_17_id                ; S03P04 id                [442,443]
  .word screen_17_name              ; S03P04 name              [444,445]
  .word screen_17_action1           ; S03P04 action1           [446,447]
  .word screen_17_action2           ; S03P04 action2           [448,449]
  .word screen_17_action3           ; S03P04 action3           [450,451]
  .word screen_17_action4           ; S03P04 action4           [452,453]
  .word screen_17_description       ; S03P04 description       [454,455]
  .word screen_17_ascii             ; S03P04 ascii             [456,457]
  .word screen_17_flashlight_on     ; S03P04 flashlight_on     [458,459]
  .word screen_17_flashlight_off    ; S03P04 flashlight_off    [460,461]
  .word screen_17_enemy_probability ; S03P04 enemy_probability [462,463]
  .word screen_17_is_secret_screen  ; S03P04 is_secret_screen  [464,465]
  .word screen_17_is_end_screen     ; S03P04 is_end_screen     [466,467]
screen_pointers_18:
  .word screen_18_id                ; S03P05 id                [468,469]
  .word screen_18_name              ; S03P05 name              [470,471]
  .word screen_18_action1           ; S03P05 action1           [472,473]
  .word screen_18_action2           ; S03P05 action2           [474,475]
  .word screen_18_action3           ; S03P05 action3           [476,477]
  .word screen_18_action4           ; S03P05 action4           [478,479]
  .word screen_18_description       ; S03P05 description       [480,481]
  .word screen_18_ascii             ; S03P05 ascii             [482,483]
  .word screen_18_flashlight_on     ; S03P05 flashlight_on     [484,485]
  .word screen_18_flashlight_off    ; S03P05 flashlight_off    [486,487]
  .word screen_18_enemy_probability ; S03P05 enemy_probability [488,489]
  .word screen_18_is_secret_screen  ; S03P05 is_secret_screen  [490,491]
  .word screen_18_is_end_screen     ; S03P05 is_end_screen     [492,493]
screen_pointers_19:
  .word screen_19_id                ; S03P06 id                [494,495]
  .word screen_19_name              ; S03P06 name              [496,497]
  .word screen_19_action1           ; S03P06 action1           [498,499]
  .word screen_19_action2           ; S03P06 action2           [500,501]
  .word screen_19_action3           ; S03P06 action3           [502,503]
  .word screen_19_action4           ; S03P06 action4           [504,505]
  .word screen_19_description       ; S03P06 description       [506,507]
  .word screen_19_ascii             ; S03P06 ascii             [508,509]
  .word screen_19_flashlight_on     ; S03P06 flashlight_on     [510,511]
  .word screen_19_flashlight_off    ; S03P06 flashlight_off    [512,513]
  .word screen_19_enemy_probability ; S03P06 enemy_probability [514,515]
  .word screen_19_is_secret_screen  ; S03P06 is_secret_screen  [516,517]
  .word screen_19_is_end_screen     ; S03P06 is_end_screen     [518,519]
screen_pointers_20:
  .word screen_20_id                ; S04P01 id                [520,521]
  .word screen_20_name              ; S04P01 name              [522,523]
  .word screen_20_action1           ; S04P01 action1           [524,525]
  .word screen_20_action2           ; S04P01 action2           [526,527]
  .word screen_20_action3           ; S04P01 action3           [528,529]
  .word screen_20_action4           ; S04P01 action4           [530,531]
  .word screen_20_description       ; S04P01 description       [532,533]
  .word screen_20_ascii             ; S04P01 ascii             [534,535]
  .word screen_20_flashlight_on     ; S04P01 flashlight_on     [536,537]
  .word screen_20_flashlight_off    ; S04P01 flashlight_off    [538,539]
  .word screen_20_enemy_probability ; S04P01 enemy_probability [540,541]
  .word screen_20_is_secret_screen  ; S04P01 is_secret_screen  [542,543]
  .word screen_20_is_end_screen     ; S04P01 is_end_screen     [544,545]
screen_pointers_21:
  .word screen_21_id                ; S04P02 id                [546,547]
  .word screen_21_name              ; S04P02 name              [548,549]
  .word screen_21_action1           ; S04P02 action1           [550,551]
  .word screen_21_action2           ; S04P02 action2           [552,553]
  .word screen_21_action3           ; S04P02 action3           [554,555]
  .word screen_21_action4           ; S04P02 action4           [556,557]
  .word screen_21_description       ; S04P02 description       [558,559]
  .word screen_21_ascii             ; S04P02 ascii             [560,561]
  .word screen_21_flashlight_on     ; S04P02 flashlight_on     [562,563]
  .word screen_21_flashlight_off    ; S04P02 flashlight_off    [564,565]
  .word screen_21_enemy_probability ; S04P02 enemy_probability [566,567]
  .word screen_21_is_secret_screen  ; S04P02 is_secret_screen  [568,569]
  .word screen_21_is_end_screen     ; S04P02 is_end_screen     [570,571]
screen_pointers_22:
  .word screen_22_id                ; S04P03 id                [572,573]
  .word screen_22_name              ; S04P03 name              [574,575]
  .word screen_22_action1           ; S04P03 action1           [576,577]
  .word screen_22_action2           ; S04P03 action2           [578,579]
  .word screen_22_action3           ; S04P03 action3           [580,581]
  .word screen_22_action4           ; S04P03 action4           [582,583]
  .word screen_22_description       ; S04P03 description       [584,585]
  .word screen_22_ascii             ; S04P03 ascii             [586,587]
  .word screen_22_flashlight_on     ; S04P03 flashlight_on     [588,589]
  .word screen_22_flashlight_off    ; S04P03 flashlight_off    [590,591]
  .word screen_22_enemy_probability ; S04P03 enemy_probability [592,593]
  .word screen_22_is_secret_screen  ; S04P03 is_secret_screen  [594,595]
  .word screen_22_is_end_screen     ; S04P03 is_end_screen     [596,597]
screen_pointers_23:
  .word screen_23_id                ; S04P04 id                [598,599]
  .word screen_23_name              ; S04P04 name              [600,601]
  .word screen_23_action1           ; S04P04 action1           [602,603]
  .word screen_23_action2           ; S04P04 action2           [604,605]
  .word screen_23_action3           ; S04P04 action3           [606,607]
  .word screen_23_action4           ; S04P04 action4           [608,609]
  .word screen_23_description       ; S04P04 description       [610,611]
  .word screen_23_ascii             ; S04P04 ascii             [612,613]
  .word screen_23_flashlight_on     ; S04P04 flashlight_on     [614,615]
  .word screen_23_flashlight_off    ; S04P04 flashlight_off    [616,617]
  .word screen_23_enemy_probability ; S04P04 enemy_probability [618,619]
  .word screen_23_is_secret_screen  ; S04P04 is_secret_screen  [620,621]
  .word screen_23_is_end_screen     ; S04P04 is_end_screen     [622,623]
screen_pointers_24:
  .word screen_24_id                ; S05P01 id                [624,625]
  .word screen_24_name              ; S05P01 name              [626,627]
  .word screen_24_action1           ; S05P01 action1           [628,629]
  .word screen_24_action2           ; S05P01 action2           [630,631]
  .word screen_24_action3           ; S05P01 action3           [632,633]
  .word screen_24_action4           ; S05P01 action4           [634,635]
  .word screen_24_description       ; S05P01 description       [636,637]
  .word screen_24_ascii             ; S05P01 ascii             [638,639]
  .word screen_24_flashlight_on     ; S05P01 flashlight_on     [640,641]
  .word screen_24_flashlight_off    ; S05P01 flashlight_off    [642,643]
  .word screen_24_enemy_probability ; S05P01 enemy_probability [644,645]
  .word screen_24_is_secret_screen  ; S05P01 is_secret_screen  [646,647]
  .word screen_24_is_end_screen     ; S05P01 is_end_screen     [648,649]
screen_pointers_25:
  .word screen_25_id                ; S05P02 id                [650,651]
  .word screen_25_name              ; S05P02 name              [652,653]
  .word screen_25_action1           ; S05P02 action1           [654,655]
  .word screen_25_action2           ; S05P02 action2           [656,657]
  .word screen_25_action3           ; S05P02 action3           [658,659]
  .word screen_25_action4           ; S05P02 action4           [660,661]
  .word screen_25_description       ; S05P02 description       [662,663]
  .word screen_25_ascii             ; S05P02 ascii             [664,665]
  .word screen_25_flashlight_on     ; S05P02 flashlight_on     [666,667]
  .word screen_25_flashlight_off    ; S05P02 flashlight_off    [668,669]
  .word screen_25_enemy_probability ; S05P02 enemy_probability [670,671]
  .word screen_25_is_secret_screen  ; S05P02 is_secret_screen  [672,673]
  .word screen_25_is_end_screen     ; S05P02 is_end_screen     [674,675]
screen_pointers_26:
  .word screen_26_id                ; S05P03 id                [676,677]
  .word screen_26_name              ; S05P03 name              [678,679]
  .word screen_26_action1           ; S05P03 action1           [680,681]
  .word screen_26_action2           ; S05P03 action2           [682,683]
  .word screen_26_action3           ; S05P03 action3           [684,685]
  .word screen_26_action4           ; S05P03 action4           [686,687]
  .word screen_26_description       ; S05P03 description       [688,689]
  .word screen_26_ascii             ; S05P03 ascii             [690,691]
  .word screen_26_flashlight_on     ; S05P03 flashlight_on     [692,693]
  .word screen_26_flashlight_off    ; S05P03 flashlight_off    [694,695]
  .word screen_26_enemy_probability ; S05P03 enemy_probability [696,697]
  .word screen_26_is_secret_screen  ; S05P03 is_secret_screen  [698,699]
  .word screen_26_is_end_screen     ; S05P03 is_end_screen     [700,701]
screen_pointers_27:
  .word screen_27_id                ; S05P04 id                [702,703]
  .word screen_27_name              ; S05P04 name              [704,705]
  .word screen_27_action1           ; S05P04 action1           [706,707]
  .word screen_27_action2           ; S05P04 action2           [708,709]
  .word screen_27_action3           ; S05P04 action3           [710,711]
  .word screen_27_action4           ; S05P04 action4           [712,713]
  .word screen_27_description       ; S05P04 description       [714,715]
  .word screen_27_ascii             ; S05P04 ascii             [716,717]
  .word screen_27_flashlight_on     ; S05P04 flashlight_on     [718,719]
  .word screen_27_flashlight_off    ; S05P04 flashlight_off    [720,721]
  .word screen_27_enemy_probability ; S05P04 enemy_probability [722,723]
  .word screen_27_is_secret_screen  ; S05P04 is_secret_screen  [724,725]
  .word screen_27_is_end_screen     ; S05P04 is_end_screen     [726,727]
screen_pointers_28:
  .word screen_28_id                ; S05P05 id                [728,729]
  .word screen_28_name              ; S05P05 name              [730,731]
  .word screen_28_action1           ; S05P05 action1           [732,733]
  .word screen_28_action2           ; S05P05 action2           [734,735]
  .word screen_28_action3           ; S05P05 action3           [736,737]
  .word screen_28_action4           ; S05P05 action4           [738,739]
  .word screen_28_description       ; S05P05 description       [740,741]
  .word screen_28_ascii             ; S05P05 ascii             [742,743]
  .word screen_28_flashlight_on     ; S05P05 flashlight_on     [744,745]
  .word screen_28_flashlight_off    ; S05P05 flashlight_off    [746,747]
  .word screen_28_enemy_probability ; S05P05 enemy_probability [748,749]
  .word screen_28_is_secret_screen  ; S05P05 is_secret_screen  [750,751]
  .word screen_28_is_end_screen     ; S05P05 is_end_screen     [752,753]
screen_pointers_29:
  .word screen_29_id                ; S06P01 id                [754,755]
  .word screen_29_name              ; S06P01 name              [756,757]
  .word screen_29_action1           ; S06P01 action1           [758,759]
  .word screen_29_action2           ; S06P01 action2           [760,761]
  .word screen_29_action3           ; S06P01 action3           [762,763]
  .word screen_29_action4           ; S06P01 action4           [764,765]
  .word screen_29_description       ; S06P01 description       [766,767]
  .word screen_29_ascii             ; S06P01 ascii             [768,769]
  .word screen_29_flashlight_on     ; S06P01 flashlight_on     [770,771]
  .word screen_29_flashlight_off    ; S06P01 flashlight_off    [772,773]
  .word screen_29_enemy_probability ; S06P01 enemy_probability [774,775]
  .word screen_29_is_secret_screen  ; S06P01 is_secret_screen  [776,777]
  .word screen_29_is_end_screen     ; S06P01 is_end_screen     [778,779]
screen_pointers_30:
  .word screen_30_id                ; S06P02 id                [780,781]
  .word screen_30_name              ; S06P02 name              [782,783]
  .word screen_30_action1           ; S06P02 action1           [784,785]
  .word screen_30_action2           ; S06P02 action2           [786,787]
  .word screen_30_action3           ; S06P02 action3           [788,789]
  .word screen_30_action4           ; S06P02 action4           [790,791]
  .word screen_30_description       ; S06P02 description       [792,793]
  .word screen_30_ascii             ; S06P02 ascii             [794,795]
  .word screen_30_flashlight_on     ; S06P02 flashlight_on     [796,797]
  .word screen_30_flashlight_off    ; S06P02 flashlight_off    [798,799]
  .word screen_30_enemy_probability ; S06P02 enemy_probability [800,801]
  .word screen_30_is_secret_screen  ; S06P02 is_secret_screen  [802,803]
  .word screen_30_is_end_screen     ; S06P02 is_end_screen     [804,805]
screen_pointers_31:
  .word screen_31_id                ; S06P03 id                [806,807]
  .word screen_31_name              ; S06P03 name              [808,809]
  .word screen_31_action1           ; S06P03 action1           [810,811]
  .word screen_31_action2           ; S06P03 action2           [812,813]
  .word screen_31_action3           ; S06P03 action3           [814,815]
  .word screen_31_action4           ; S06P03 action4           [816,817]
  .word screen_31_description       ; S06P03 description       [818,819]
  .word screen_31_ascii             ; S06P03 ascii             [820,821]
  .word screen_31_flashlight_on     ; S06P03 flashlight_on     [822,823]
  .word screen_31_flashlight_off    ; S06P03 flashlight_off    [824,825]
  .word screen_31_enemy_probability ; S06P03 enemy_probability [826,827]
  .word screen_31_is_secret_screen  ; S06P03 is_secret_screen  [828,829]
  .word screen_31_is_end_screen     ; S06P03 is_end_screen     [830,831]
screen_pointers_32:
  .word screen_32_id                ; S07P01 id                [832,833]
  .word screen_32_name              ; S07P01 name              [834,835]
  .word screen_32_action1           ; S07P01 action1           [836,837]
  .word screen_32_action2           ; S07P01 action2           [838,839]
  .word screen_32_action3           ; S07P01 action3           [840,841]
  .word screen_32_action4           ; S07P01 action4           [842,843]
  .word screen_32_description       ; S07P01 description       [844,845]
  .word screen_32_ascii             ; S07P01 ascii             [846,847]
  .word screen_32_flashlight_on     ; S07P01 flashlight_on     [848,849]
  .word screen_32_flashlight_off    ; S07P01 flashlight_off    [850,851]
  .word screen_32_enemy_probability ; S07P01 enemy_probability [852,853]
  .word screen_32_is_secret_screen  ; S07P01 is_secret_screen  [854,855]
  .word screen_32_is_end_screen     ; S07P01 is_end_screen     [856,857]
screen_pointers_33:
  .word screen_33_id                ; S07P02 id                [858,859]
  .word screen_33_name              ; S07P02 name              [860,861]
  .word screen_33_action1           ; S07P02 action1           [862,863]
  .word screen_33_action2           ; S07P02 action2           [864,865]
  .word screen_33_action3           ; S07P02 action3           [866,867]
  .word screen_33_action4           ; S07P02 action4           [868,869]
  .word screen_33_description       ; S07P02 description       [870,871]
  .word screen_33_ascii             ; S07P02 ascii             [872,873]
  .word screen_33_flashlight_on     ; S07P02 flashlight_on     [874,875]
  .word screen_33_flashlight_off    ; S07P02 flashlight_off    [876,877]
  .word screen_33_enemy_probability ; S07P02 enemy_probability [878,879]
  .word screen_33_is_secret_screen  ; S07P02 is_secret_screen  [880,881]
  .word screen_33_is_end_screen     ; S07P02 is_end_screen     [882,883]
screen_pointers_34:
  .word screen_34_id                ; S07P03 id                [884,885]
  .word screen_34_name              ; S07P03 name              [886,887]
  .word screen_34_action1           ; S07P03 action1           [888,889]
  .word screen_34_action2           ; S07P03 action2           [890,891]
  .word screen_34_action3           ; S07P03 action3           [892,893]
  .word screen_34_action4           ; S07P03 action4           [894,895]
  .word screen_34_description       ; S07P03 description       [896,897]
  .word screen_34_ascii             ; S07P03 ascii             [898,899]
  .word screen_34_flashlight_on     ; S07P03 flashlight_on     [900,901]
  .word screen_34_flashlight_off    ; S07P03 flashlight_off    [902,903]
  .word screen_34_enemy_probability ; S07P03 enemy_probability [904,905]
  .word screen_34_is_secret_screen  ; S07P03 is_secret_screen  [906,907]
  .word screen_34_is_end_screen     ; S07P03 is_end_screen     [908,909]
screen_pointers_35:
  .word screen_35_id                ; S07P04 id                [910,911]
  .word screen_35_name              ; S07P04 name              [912,913]
  .word screen_35_action1           ; S07P04 action1           [914,915]
  .word screen_35_action2           ; S07P04 action2           [916,917]
  .word screen_35_action3           ; S07P04 action3           [918,919]
  .word screen_35_action4           ; S07P04 action4           [920,921]
  .word screen_35_description       ; S07P04 description       [922,923]
  .word screen_35_ascii             ; S07P04 ascii             [924,925]
  .word screen_35_flashlight_on     ; S07P04 flashlight_on     [926,927]
  .word screen_35_flashlight_off    ; S07P04 flashlight_off    [928,929]
  .word screen_35_enemy_probability ; S07P04 enemy_probability [930,931]
  .word screen_35_is_secret_screen  ; S07P04 is_secret_screen  [932,933]
  .word screen_35_is_end_screen     ; S07P04 is_end_screen     [934,935]
screen_pointers_36:
  .word screen_36_id                ; S07P05 id                [936,937]
  .word screen_36_name              ; S07P05 name              [938,939]
  .word screen_36_action1           ; S07P05 action1           [940,941]
  .word screen_36_action2           ; S07P05 action2           [942,943]
  .word screen_36_action3           ; S07P05 action3           [944,945]
  .word screen_36_action4           ; S07P05 action4           [946,947]
  .word screen_36_description       ; S07P05 description       [948,949]
  .word screen_36_ascii             ; S07P05 ascii             [950,951]
  .word screen_36_flashlight_on     ; S07P05 flashlight_on     [952,953]
  .word screen_36_flashlight_off    ; S07P05 flashlight_off    [954,955]
  .word screen_36_enemy_probability ; S07P05 enemy_probability [956,957]
  .word screen_36_is_secret_screen  ; S07P05 is_secret_screen  [958,959]
  .word screen_36_is_end_screen     ; S07P05 is_end_screen     [960,961]
screen_pointers_37:
  .word screen_37_id                ; S07P06 id                [962,963]
  .word screen_37_name              ; S07P06 name              [964,965]
  .word screen_37_action1           ; S07P06 action1           [966,967]
  .word screen_37_action2           ; S07P06 action2           [968,969]
  .word screen_37_action3           ; S07P06 action3           [970,971]
  .word screen_37_action4           ; S07P06 action4           [972,973]
  .word screen_37_description       ; S07P06 description       [974,975]
  .word screen_37_ascii             ; S07P06 ascii             [976,977]
  .word screen_37_flashlight_on     ; S07P06 flashlight_on     [978,979]
  .word screen_37_flashlight_off    ; S07P06 flashlight_off    [980,981]
  .word screen_37_enemy_probability ; S07P06 enemy_probability [982,983]
  .word screen_37_is_secret_screen  ; S07P06 is_secret_screen  [984,985]
  .word screen_37_is_end_screen     ; S07P06 is_end_screen     [986,987]
screen_pointers_38:
  .word screen_38_id                ; FINAL id                [988,989]
  .word screen_38_name              ; FINAL name              [990,991]
  .word screen_38_action1           ; FINAL action1           [992,993]
  .word screen_38_action2           ; FINAL action2           [994,995]
  .word screen_38_action3           ; FINAL action3           [996,997]
  .word screen_38_action4           ; FINAL action4           [998,999]
  .word screen_38_description       ; FINAL description       [1000,1001]
  .word screen_38_ascii             ; FINAL ascii             [1002,1003]
  .word screen_38_flashlight_on     ; FINAL flashlight_on     [1004,1005]
  .word screen_38_flashlight_off    ; FINAL flashlight_off    [1006,1007]
  .word screen_38_enemy_probability ; FINAL enemy_probability [1008,1009]
  .word screen_38_is_secret_screen  ; FINAL is_secret_screen  [1010,1011]
  .word screen_38_is_end_screen     ; FINAL is_end_screen     [1012,1013]
screen_pointers_39:
  .word screen_39_id                ; EndScreenSimulationTimeisUp id                [1014,1015]
  .word screen_39_name              ; EndScreenSimulationTimeisUp name              [1016,1017]
  .word screen_39_action1           ; EndScreenSimulationTimeisUp action1           [1018,1019]
  .word screen_39_action2           ; EndScreenSimulationTimeisUp action2           [1020,1021]
  .word screen_39_action3           ; EndScreenSimulationTimeisUp action3           [1022,1023]
  .word screen_39_action4           ; EndScreenSimulationTimeisUp action4           [1024,1025]
  .word screen_39_description       ; EndScreenSimulationTimeisUp description       [1026,1027]
  .word screen_39_ascii             ; EndScreenSimulationTimeisUp ascii             [1028,1029]
  .word screen_39_flashlight_on     ; EndScreenSimulationTimeisUp flashlight_on     [1030,1031]
  .word screen_39_flashlight_off    ; EndScreenSimulationTimeisUp flashlight_off    [1032,1033]
  .word screen_39_enemy_probability ; EndScreenSimulationTimeisUp enemy_probability [1034,1035]
  .word screen_39_is_secret_screen  ; EndScreenSimulationTimeisUp is_secret_screen  [1036,1037]
  .word screen_39_is_end_screen     ; EndScreenSimulationTimeisUp is_end_screen     [1038,1039]
screen_pointers_40:
  .word screen_40_id                ; endScreenByEnemy id                [1040,1041]
  .word screen_40_name              ; endScreenByEnemy name              [1042,1043]
  .word screen_40_action1           ; endScreenByEnemy action1           [1044,1045]
  .word screen_40_action2           ; endScreenByEnemy action2           [1046,1047]
  .word screen_40_action3           ; endScreenByEnemy action3           [1048,1049]
  .word screen_40_action4           ; endScreenByEnemy action4           [1050,1051]
  .word screen_40_description       ; endScreenByEnemy description       [1052,1053]
  .word screen_40_ascii             ; endScreenByEnemy ascii             [1054,1055]
  .word screen_40_flashlight_on     ; endScreenByEnemy flashlight_on     [1056,1057]
  .word screen_40_flashlight_off    ; endScreenByEnemy flashlight_off    [1058,1059]
  .word screen_40_enemy_probability ; endScreenByEnemy enemy_probability [1060,1061]
  .word screen_40_is_secret_screen  ; endScreenByEnemy is_secret_screen  [1062,1063]
  .word screen_40_is_end_screen     ; endScreenByEnemy is_end_screen     [1064,1065]
screen_pointers_41:
  .word screen_41_id                ; endScreenByActionFailed id                [1066,1067]
  .word screen_41_name              ; endScreenByActionFailed name              [1068,1069]
  .word screen_41_action1           ; endScreenByActionFailed action1           [1070,1071]
  .word screen_41_action2           ; endScreenByActionFailed action2           [1072,1073]
  .word screen_41_action3           ; endScreenByActionFailed action3           [1074,1075]
  .word screen_41_action4           ; endScreenByActionFailed action4           [1076,1077]
  .word screen_41_description       ; endScreenByActionFailed description       [1078,1079]
  .word screen_41_ascii             ; endScreenByActionFailed ascii             [1080,1081]
  .word screen_41_flashlight_on     ; endScreenByActionFailed flashlight_on     [1082,1083]
  .word screen_41_flashlight_off    ; endScreenByActionFailed flashlight_off    [1084,1085]
  .word screen_41_enemy_probability ; endScreenByActionFailed enemy_probability [1086,1087]
  .word screen_41_is_secret_screen  ; endScreenByActionFailed is_secret_screen  [1088,1089]
  .word screen_41_is_end_screen     ; endScreenByActionFailed is_end_screen     [1090,1091]
screen_action_offset:
  .byte 4  ; (byte of screen_0_action1 in screens_pointers)
screen_description_offset:
  .byte 12  ; (byte of screen_0_description in screens_pointers)
screen_ascii_offset:
  .byte 14  ; (byte of screen_0_ascii in screens_pointers)
screen_flashlight_on_offset:
  .byte 16  ; (byte of screen_0_flashlight_on in screens_pointers)
screen_flashlight_off_offset:
  .byte 18  ; (byte of screen_0_flashlight_off in screens_pointers)
screen_enemy_probability_offset:
  .byte 20  ; (byte of screen_0_enemy_probability in screens_pointers)
screen_is_secret_screen_offset:
  .byte 22  ; (byte of screen_0_is_secret_screen in screens_pointers)
screen_is_end_screen_offset:
  .byte 24  ; (byte of screen_0_is_end_screen in screens_pointers)
screen_record_length:
  .byte 26  ; (total .word bytes per screen record)

; ── Screen 0: StartScreen ──────────────────────────
screen_0_id:
  .byte 0

screen_0_name:
  .ascii "StartScreen"
  .ascii "e"

screen_0_action1:
  .byte 0  ; START-COMENZAR

screen_0_action2:
  .byte 255  ; none

screen_0_action3:
  .byte 255  ; none

screen_0_action4:
  .byte 255  ; none

screen_0_description:
  .ascii ""
  .ascii "e"

screen_0_ascii:
  .ascii "░░░░░░░░░░░░░░░░░░░░                    "
  .ascii "░░░░░░░▄▄▄▄▄▄░░░░░░░     LA CAVERNA     "
  .ascii "░░░░░░█      █░░░░░░                    "
  .ascii "░░░░░█        █░░░░░                    "
  .ascii "░░░░░█        █░░░░░  El primer juego   "
  .ascii "░░░░█          █░░░░     de la 20c      "
  .ascii "░░░░█          █░░░░                    "
  .ascii "▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒                    "
  .ascii "▒▒▒▒▒▒▓▓▓▓▓▓▓▓▒▒▒▒▒▒                    "
  .ascii "▒▒▒▒▒▒▒▓▓▓▓▓▓▒▒▒▒▒▒▒ 2026   Oso & Berdyx"
  .ascii "e"

screen_0_flashlight_on:
  .ascii ""
  .ascii "e"

screen_0_flashlight_off:
  .ascii ""
  .ascii "e"

screen_0_enemy_probability:
  .byte 0

screen_0_is_secret_screen:
  .byte 0  ; no

screen_0_is_end_screen:
  .byte 0  ; no

; ── Screen 1: S01P01 ──────────────────────────
screen_1_id:
  .byte 1

screen_1_name:
  .ascii "S01P01"
  .ascii "e"

screen_1_action1:
  .byte 1  ; S01P01-LEVANTARSE

screen_1_action2:
  .byte 255  ; none

screen_1_action3:
  .byte 255  ; none

screen_1_action4:
  .byte 255  ; none

screen_1_description:
  .ascii "Te despiertas en la oscuridad."
  .ascii "Tu ultimo recuerdo es el ruido de un derrumbe."
  .ascii "e"

screen_1_ascii:
  .ascii ""
  .ascii "e"

screen_1_flashlight_on:
  .ascii ""
  .ascii "e"

screen_1_flashlight_off:
  .ascii ""
  .ascii "e"

screen_1_enemy_probability:
  .byte 0

screen_1_is_secret_screen:
  .byte 0  ; no

screen_1_is_end_screen:
  .byte 0  ; no

; ── Screen 2: S01P02 ──────────────────────────
screen_2_id:
  .byte 2

screen_2_name:
  .ascii "S01P02"
  .ascii "e"

screen_2_action1:
  .byte 2  ; S01P02-GRITAR

screen_2_action2:
  .byte 255  ; none

screen_2_action3:
  .byte 255  ; none

screen_2_action4:
  .byte 255  ; none

screen_2_description:
  .ascii "Te incorporas. Un ruido constante invade el silencio."
  .ascii "El inconfundible ruido del agua goteando."
  .ascii "¿Tal vez alguien puede ayudarte?"
  .ascii "e"

screen_2_ascii:
  .ascii ""
  .ascii "e"

screen_2_flashlight_on:
  .ascii ""
  .ascii "e"

screen_2_flashlight_off:
  .ascii ""
  .ascii "e"

screen_2_enemy_probability:
  .byte 0

screen_2_is_secret_screen:
  .byte 0  ; no

screen_2_is_end_screen:
  .byte 0  ; no

; ── Screen 3: S01P03 ──────────────────────────
screen_3_id:
  .byte 3

screen_3_name:
  .ascii "S01P03"
  .ascii "e"

screen_3_action1:
  .byte 4  ; S01P03-EXPLORAR

screen_3_action2:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_3_action3:
  .byte 255  ; none

screen_3_action4:
  .byte 255  ; none

screen_3_description:
  .ascii "La oscuridad absoluta comienza a afectarte, tu corazon late rapidamente."
  .ascii "Con miedo y en la oscuridad, sientes que el tiempo funciona de manera diferente."
  .ascii "Tu linterna puede ayudarte con esto. No tiene mucha autonomia, esperas que sea"
  .ascii "la suficiente para salir de aqui."
  .ascii ""
  .ascii "Gota, pausa, gota. "
  .ascii "El ritmo del agua filtrandose marca que no tienes mucho tiempo."
  .ascii "Mejor explorar el lugar."
  .ascii "e"

screen_3_ascii:
  .ascii ""
  .ascii "e"

screen_3_flashlight_on:
  .ascii ""
  .ascii "e"

screen_3_flashlight_off:
  .ascii ""
  .ascii "e"

screen_3_enemy_probability:
  .byte 0

screen_3_is_secret_screen:
  .byte 0  ; no

screen_3_is_end_screen:
  .byte 0  ; no

; ── Screen 4: S01P04 ──────────────────────────
screen_4_id:
  .byte 4

screen_4_name:
  .ascii "S01P04"
  .ascii "e"

screen_4_action1:
  .byte 5  ; S01P04-REMOVER

screen_4_action2:
  .byte 6  ; S01P04-ATRAVESAR

screen_4_action3:
  .byte 8  ; S01P04-EXTRAER

screen_4_action4:
  .byte 7  ; S01P04-ILUMINAR

screen_4_description:
  .ascii "Comienzas a recorrer la caverna. Mirar atrás genera una sensación incómoda, como"
  .ascii "si la entrada no hubiera estado siempre así."
  .ascii "Te encuentras con un obstaculo. Parece ser una gran acumulacion de rocas."
  .ascii "Entre las rocas hay rendijas por donde entra aire viciado, pero ninguna lo"
  .ascii "bastante grande para pasar."
  .ascii ""
  .ascii "Puedes optar por remover lenta y seguramente las rocas para intentar pasar, o"
  .ascii "forzar tu paso empujando rocas en alguna de las rendijas."
  .ascii "Tal vez iluminar las rocas brinde mas informacion."
  .ascii ""
  .ascii "e"

screen_4_ascii:
  .ascii ""
  .ascii "e"

screen_4_flashlight_on:
  .ascii "Iluminas una roca que te llama la atencion."
  .ascii ""
  .ascii "e"

screen_4_flashlight_off:
  .ascii ""
  .ascii "e"

screen_4_enemy_probability:
  .byte 0

screen_4_is_secret_screen:
  .byte 0  ; no

screen_4_is_end_screen:
  .byte 0  ; no

; ── Screen 5: S01P05 ──────────────────────────
screen_5_id:
  .byte 5

screen_5_name:
  .ascii "S01P05"
  .ascii "e"

screen_5_action1:
  .byte 9  ; S01P056-VOLVER

screen_5_action2:
  .byte 255  ; none

screen_5_action3:
  .byte 255  ; none

screen_5_action4:
  .byte 255  ; none

screen_5_description:
  .ascii "Iluminas las rocas. "
  .ascii "No parece un derrumbe comun sino algo más inquietante: rocas antiguas, pesadas,"
  .ascii "acomodadas como si el colapso hubiera sido final, no accidental."
  .ascii "Hay marcas irregulares, como si alguien hubiera intentado mover las rocas y se"
  .ascii "hubiera detenido a mitad de camino."
  .ascii "e"

screen_5_ascii:
  .ascii ""
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░ ▄▄▄▄ ░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░ ▄▄▄ █████▌▄▄ ░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░ ▄ ████  ▀▀▀ ▄███▄ ░░░░░░░░░░░"
  .ascii "░░░░░░░░░▐███ ▀█▀▄████ ▐███▀ ▄▄ ░░░░░░░░"
  .ascii "░░░░░░ ▄▄ ▀▄███▄ ██████ ▄▄▄▐███▌░░░░░░░░"
  .ascii "░░░░░░▐███ █████▌▐███▀ ▐███ ████ ░░░░░░░"
  .ascii "░░░░ ▄▀▀ ▄▄▄▄▀▀▄▄▄▄▄ ▄█▄  ▄▄▄▄  ▄ ░░░░░░"
  .ascii "░░░░▐███▐████▌██████▌███▌█████▌█¥█ ░░░░░"
  .ascii ""
  .ascii "e"

screen_5_flashlight_on:
  .ascii ""
  .ascii "e"

screen_5_flashlight_off:
  .ascii ""
  .ascii "e"

screen_5_enemy_probability:
  .byte 0

screen_5_is_secret_screen:
  .byte 0  ; no

screen_5_is_end_screen:
  .byte 0  ; no

; ── Screen 6: S01P06 ──────────────────────────
screen_6_id:
  .byte 6

screen_6_name:
  .ascii "S01P06"
  .ascii "e"

screen_6_action1:
  .byte 9  ; S01P056-VOLVER

screen_6_action2:
  .byte 255  ; none

screen_6_action3:
  .byte 255  ; none

screen_6_action4:
  .byte 255  ; none

screen_6_description:
  .ascii ""
  .ascii "¿ESTE DIBUJO TE ES FAMILIAR?"
  .ascii "e"

screen_6_ascii:
  .ascii "¡ HAS ENCONTRADO UN SECRETO !"
  .ascii ""
  .ascii "  ██████        "
  .ascii "████  ████      "
  .ascii "██      ██      "
  .ascii "██    ██    ██  "
  .ascii "████      ████  "
  .ascii "  ████████      "
  .ascii "    ██████      "
  .ascii "    ████████  ██"
  .ascii "    █████   ██  "
  .ascii "███       ██  ██"
  .ascii "e"

screen_6_flashlight_on:
  .ascii ""
  .ascii "e"

screen_6_flashlight_off:
  .ascii ""
  .ascii "e"

screen_6_enemy_probability:
  .byte 1

screen_6_is_secret_screen:
  .byte 1  ; yes

screen_6_is_end_screen:
  .byte 0  ; no

; ── Screen 7: S02P01 ──────────────────────────
screen_7_id:
  .byte 7

screen_7_name:
  .ascii "S02P01"
  .ascii "e"

screen_7_action1:
  .byte 10  ; S02P01-CONTINUAR

screen_7_action2:
  .byte 255  ; none

screen_7_action3:
  .byte 255  ; none

screen_7_action4:
  .byte 255  ; none

screen_7_description:
  .ascii "Logras pasar el obstaculo, instantes antes de que se derrumbe por completo. Con"
  .ascii "certeza, no hay vuelta atras."
  .ascii "La experiencia altero tus sentidos. El miedo te invade."
  .ascii "e"

screen_7_ascii:
  .ascii ""
  .ascii "e"

screen_7_flashlight_on:
  .ascii ""
  .ascii "e"

screen_7_flashlight_off:
  .ascii ""
  .ascii "e"

screen_7_enemy_probability:
  .byte 0

screen_7_is_secret_screen:
  .byte 0  ; no

screen_7_is_end_screen:
  .byte 0  ; no

; ── Screen 8: S02P02 ──────────────────────────
screen_8_id:
  .byte 8

screen_8_name:
  .ascii "S02P02"
  .ascii "e"

screen_8_action1:
  .byte 12  ; S02P02-EXPLORAR

screen_8_action2:
  .byte 11  ; DESCANSAR

screen_8_action3:
  .byte 255  ; none

screen_8_action4:
  .byte 255  ; none

screen_8_description:
  .ascii "Descansar puede ayudarte a bajar tu desesperacion y que tengas otra mirada de la"
  .ascii "situacion."
  .ascii "Lamentablemente, descansar lleva tiempo, y no es un lujo que puedes permitirte a"
  .ascii "menudo."
  .ascii ""
  .ascii "La caverna se extiende frente a ti, esperando ser explorada."
  .ascii "e"

screen_8_ascii:
  .ascii ""
  .ascii "e"

screen_8_flashlight_on:
  .ascii ""
  .ascii "e"

screen_8_flashlight_off:
  .ascii ""
  .ascii "e"

screen_8_enemy_probability:
  .byte 0

screen_8_is_secret_screen:
  .byte 0  ; no

screen_8_is_end_screen:
  .byte 0  ; no

; ── Screen 9: S02P03 ──────────────────────────
screen_9_id:
  .byte 9

screen_9_name:
  .ascii "S02P03"
  .ascii "e"

screen_9_action1:
  .byte 15  ; S02P03-SALIDAS

screen_9_action2:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_9_action3:
  .byte 14  ; S02P03-SALA

screen_9_action4:
  .byte 13  ; S02P03-MARCAS

screen_9_description:
  .ascii "Recorres la sala hasta lo que parece ser el otro extremo."
  .ascii ""
  .ascii "Distingues 3 salidas, pero ninguna parece la correcta:"
  .ascii " "
  .ascii " Salida derecha: escuchas ruidos, podria ser actividad"
  .ascii " Salida centro: notas una fuente de iluminacion"
  .ascii " Salida izquierda: sientes una leve correntada de aire"
  .ascii ""
  .ascii "e"

screen_9_ascii:
  .ascii ""
  .ascii "e"

screen_9_flashlight_on:
  .ascii "Hay unas extrañas marcas debajo tuyo."
  .ascii "e"

screen_9_flashlight_off:
  .ascii ""
  .ascii "e"

screen_9_enemy_probability:
  .byte 0

screen_9_is_secret_screen:
  .byte 0  ; no

screen_9_is_end_screen:
  .byte 0  ; no

; ── Screen 10: S02P04 ──────────────────────────
screen_10_id:
  .byte 10

screen_10_name:
  .ascii "S02P04"
  .ascii "e"

screen_10_action1:
  .byte 16  ; S02P04567-VOLVER

screen_10_action2:
  .byte 255  ; none

screen_10_action3:
  .byte 255  ; none

screen_10_action4:
  .byte 255  ; none

screen_10_description:
  .ascii ""
  .ascii "e"

screen_10_ascii:
  .ascii ""
  .ascii "    ██████████     "
  .ascii "  ███        ███   "
  .ascii " ██   ██████    ██ "
  .ascii "██  ██      ███  ██"
  .ascii "██ ██    ██   ██  █"
  .ascii "██ ██  ██  ██  ██  "
  .ascii "██  ██     ██  ██  "
  .ascii " ██   █████   ██   "
  .ascii "   ██        ██    "
  .ascii "     ████████      "
  .ascii "e"

screen_10_flashlight_on:
  .ascii ""
  .ascii "e"

screen_10_flashlight_off:
  .ascii ""
  .ascii "e"

screen_10_enemy_probability:
  .byte 0

screen_10_is_secret_screen:
  .byte 0  ; no

screen_10_is_end_screen:
  .byte 0  ; no

; ── Screen 11: S02P05 ──────────────────────────
screen_11_id:
  .byte 11

screen_11_name:
  .ascii "S02P05"
  .ascii "e"

screen_11_action1:
  .byte 17  ; S02P05-EXPLORAR

screen_11_action2:
  .byte 16  ; S02P04567-VOLVER

screen_11_action3:
  .byte 255  ; none

screen_11_action4:
  .byte 255  ; none

screen_11_description:
  .ascii "La caverna se abre en una cámara amplia pero baja. El techo parece aplastarte"
  .ascii "con su peso; no amenaza caer."
  .ascii ""
  .ascii "Algo en la entrada de la sala del centro devuelve un reflejo a tu linterna."
  .ascii "e"

screen_11_ascii:
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░▄▄▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░█   █░░░░░░░▄▄▄▄░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░▐     ▌░░░░▄█    █▄░░░░▄▀▀▀▄░░░░░░░"
  .ascii "░░░░░█     █░░░░█      █░░░░▌   ▐░░░░░░░"
  .ascii "░░░░░█     █░░░░█ *    █░░░░▌   ▐░░░░░░░"
  .ascii "░░░░░█     █░░░░█      █░░░░▌   ▐░░░░░░░"
  .ascii "▒▒▒▒▒▒▓▓▓▓▓▒▒▒▒▒▒▓▓▓▓▓▓▒▒▒▒▒▒▓▓▓▒▒▒▒▒▒▒▒"
  .ascii "▒▒▒▒▒▒▒▓▓▓▒▒▒▒▒▒▒▒▓▓▓▓▒▒▒▒▒▒▒▒▓▒▒▒▒▒▒▒▒▒"
  .ascii "e"

screen_11_flashlight_on:
  .ascii ""
  .ascii "e"

screen_11_flashlight_off:
  .ascii ""
  .ascii "e"

screen_11_enemy_probability:
  .byte 0

screen_11_is_secret_screen:
  .byte 0  ; no

screen_11_is_end_screen:
  .byte 0  ; no

; ── Screen 12: S02P06 ──────────────────────────
screen_12_id:
  .byte 12

screen_12_name:
  .ascii "S02P06"
  .ascii "e"

screen_12_action1:
  .byte 16  ; S02P04567-VOLVER

screen_12_action2:
  .byte 255  ; none

screen_12_action3:
  .byte 255  ; none

screen_12_action4:
  .byte 255  ; none

screen_12_description:
  .ascii "NO ERES LA PRIMER PERSONA AQUI"
  .ascii "e"

screen_12_ascii:
  .ascii "░░░░░░░░░░░░░░░"
  .ascii "░░░░░▄▄██▄░░░░░"
  .ascii "░░▄▀░░▀██▀░▀▄░░"
  .ascii "░░░░░░░▐▌░░░░░░"
  .ascii "░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░▐▌░░░░░░"
  .ascii "░░░░░░░░░░░░░░░"
  .ascii "e"

screen_12_flashlight_on:
  .ascii ""
  .ascii "e"

screen_12_flashlight_off:
  .ascii ""
  .ascii "e"

screen_12_enemy_probability:
  .byte 0

screen_12_is_secret_screen:
  .byte 1  ; yes

screen_12_is_end_screen:
  .byte 0  ; no

; ── Screen 13: S02P07 ──────────────────────────
screen_13_id:
  .byte 13

screen_13_name:
  .ascii "S02P07"
  .ascii "e"

screen_13_action1:
  .byte 18  ; S02P07-DERECHA

screen_13_action2:
  .byte 19  ; S02P07-CENTRO

screen_13_action3:
  .byte 20  ; S02P07-IZQUIERDA

screen_13_action4:
  .byte 16  ; S02P04567-VOLVER

screen_13_description:
  .ascii "Elegir Salida"
  .ascii "e"

screen_13_ascii:
  .ascii ""
  .ascii "e"

screen_13_flashlight_on:
  .ascii ""
  .ascii "e"

screen_13_flashlight_off:
  .ascii ""
  .ascii "e"

screen_13_enemy_probability:
  .byte 0

screen_13_is_secret_screen:
  .byte 0  ; no

screen_13_is_end_screen:
  .byte 0  ; no

; ── Screen 14: S03P01 ──────────────────────────
screen_14_id:
  .byte 14

screen_14_name:
  .ascii "S03P01"
  .ascii "e"

screen_14_action1:
  .byte 21  ; S03P01-CORRER

screen_14_action2:
  .byte 11  ; DESCANSAR

screen_14_action3:
  .byte 22  ; S03P01-AVANZAR

screen_14_action4:
  .byte 255  ; none

screen_14_description:
  .ascii "El pasaje se estira hacia adelante como un corredor natural."
  .ascii "Las paredes se acercan y se alejan en suaves ondulaciones, y el techo se llena"
  .ascii "de formaciones afiladas que cuelgan sobre ti."
  .ascii ""
  .ascii "No se escucha nada. Ni siquiera tus propios movimientos parecen producir sonido."
  .ascii ""
  .ascii "Ese silencio no es ausencia: es contención. Como si el lugar estuviera"
  .ascii "escuchando en lugar de emitir ruido."
  .ascii ""
  .ascii "La desesperacion se apodera de ti."
  .ascii "e"

screen_14_ascii:
  .ascii "░░░░░▒▒▒▒▒▒▒▒▒▒░░░░░"
  .ascii "░░░░▒ ▐█▌▐█  █ ▒░░░░"
  .ascii "░░░▒▒  █  █  ▐ ▒▒░░░"
  .ascii "░░▒▒   ▌  ▌     ▒▒░░"
  .ascii "░░▒              ▒░░"
  .ascii "░░▒              ▒░░"
  .ascii "░░▒              ▒░░"
  .ascii "░░▒              ▒░░"
  .ascii "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓"
  .ascii "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓"
  .ascii "e"

screen_14_flashlight_on:
  .ascii ""
  .ascii "e"

screen_14_flashlight_off:
  .ascii ""
  .ascii "e"

screen_14_enemy_probability:
  .byte 0

screen_14_is_secret_screen:
  .byte 0  ; no

screen_14_is_end_screen:
  .byte 0  ; no

; ── Screen 15: S03P02 ──────────────────────────
screen_15_id:
  .byte 15

screen_15_name:
  .ascii "S03P02"
  .ascii "e"

screen_15_action1:
  .byte 23  ; S03P02-ENCENDER

screen_15_action2:
  .byte 24  ; S03P02-APAGAR

screen_15_action3:
  .byte 255  ; none

screen_15_action4:
  .byte 255  ; none

screen_15_description:
  .ascii "Avanzas con cuidado, la linterna comienza a parpadear y se apaga."
  .ascii "Escuchas un ruido detras tuyo."
  .ascii "e"

screen_15_ascii:
  .ascii ""
  .ascii "e"

screen_15_flashlight_on:
  .ascii ""
  .ascii "e"

screen_15_flashlight_off:
  .ascii ""
  .ascii "e"

screen_15_enemy_probability:
  .byte 0

screen_15_is_secret_screen:
  .byte 0  ; no

screen_15_is_end_screen:
  .byte 0  ; no

; ── Screen 16: S03P03 ──────────────────────────
screen_16_id:
  .byte 16

screen_16_name:
  .ascii "S03P03"
  .ascii "e"

screen_16_action1:
  .byte 25  ; S03P03-ILUMINAR

screen_16_action2:
  .byte 26  ; S03P03-DERECHA

screen_16_action3:
  .byte 27  ; S03P03-IZQUIERDA

screen_16_action4:
  .byte 255  ; none

screen_16_description:
  .ascii "Un obstaculo interfiere en tu camino. Puedes rodearlo por la derecha o la"
  .ascii "izquierda. Comienzas a rodearlo cuando sientes un temblor en el techo."
  .ascii "e"

screen_16_ascii:
  .ascii ""
  .ascii "e"

screen_16_flashlight_on:
  .ascii "Tu linterna parpadea."
  .ascii "e"

screen_16_flashlight_off:
  .ascii ""
  .ascii "e"

screen_16_enemy_probability:
  .byte 13

screen_16_is_secret_screen:
  .byte 0  ; no

screen_16_is_end_screen:
  .byte 0  ; no

; ── Screen 17: S03P04 ──────────────────────────
screen_17_id:
  .byte 17

screen_17_name:
  .ascii "S03P04"
  .ascii "e"

screen_17_action1:
  .byte 28  ; S03P04-VOLVER

screen_17_action2:
  .byte 255  ; none

screen_17_action3:
  .byte 255  ; none

screen_17_action4:
  .byte 255  ; none

screen_17_description:
  .ascii "Iluminas el techo"
  .ascii "e"

screen_17_ascii:
  .ascii "░░░░░░░░░░▐██▌░░░"
  .ascii "░░░   ░░░░░██░░░░"
  .ascii "           ▐█    "
  .ascii "            █    "
  .ascii "            ▌    "
  .ascii "e"

screen_17_flashlight_on:
  .ascii ""
  .ascii "e"

screen_17_flashlight_off:
  .ascii ""
  .ascii "e"

screen_17_enemy_probability:
  .byte 0

screen_17_is_secret_screen:
  .byte 0  ; no

screen_17_is_end_screen:
  .byte 0  ; no

; ── Screen 18: S03P05 ──────────────────────────
screen_18_id:
  .byte 18

screen_18_name:
  .ascii "S03P05"
  .ascii "e"

screen_18_action1:
  .byte 29  ; S03P05-RODEAR

screen_18_action2:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_18_action3:
  .byte 11  ; DESCANSAR

screen_18_action4:
  .byte 30  ; S03P05-ILUMINAR

screen_18_description:
  .ascii "Seguis por el pasillo, te encontras otro obstaculo."
  .ascii ""
  .ascii "Nuevamente podes rodearlo por la derecha o la izquierda. "
  .ascii ""
  .ascii "e"

screen_18_ascii:
  .ascii ""
  .ascii "e"

screen_18_flashlight_on:
  .ascii "Tu linterna parpadea. En el techo no parece haber desprendimientos si te moves"
  .ascii "con cuidado. Sin embargo vez una marca"
  .ascii "e"

screen_18_flashlight_off:
  .ascii ""
  .ascii "e"

screen_18_enemy_probability:
  .byte 13

screen_18_is_secret_screen:
  .byte 0  ; no

screen_18_is_end_screen:
  .byte 0  ; no

; ── Screen 19: S03P06 ──────────────────────────
screen_19_id:
  .byte 19

screen_19_name:
  .ascii "S03P06"
  .ascii "e"

screen_19_action1:
  .byte 31  ; S03P06-VOLVER

screen_19_action2:
  .byte 255  ; none

screen_19_action3:
  .byte 255  ; none

screen_19_action4:
  .byte 255  ; none

screen_19_description:
  .ascii "ALGO O ALGUIEN PARECE HABER SIDO ARRASTRADO AQUI"
  .ascii "e"

screen_19_ascii:
  .ascii "░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░≡░░░░░░░░"
  .ascii "░░░██░░░≡░░▐█▌░░"
  .ascii "   ▐▌       █   "
  .ascii "    ▌       ▌   "
  .ascii "e"

screen_19_flashlight_on:
  .ascii ""
  .ascii "e"

screen_19_flashlight_off:
  .ascii ""
  .ascii "e"

screen_19_enemy_probability:
  .byte 0

screen_19_is_secret_screen:
  .byte 1  ; yes

screen_19_is_end_screen:
  .byte 0  ; no

; ── Screen 20: S04P01 ──────────────────────────
screen_20_id:
  .byte 20

screen_20_name:
  .ascii "S04P01"
  .ascii "e"

screen_20_action1:
  .byte 32  ; S04P01-SALIENTES

screen_20_action2:
  .byte 33  ; S04P01-SINSALIENTES

screen_20_action3:
  .byte 11  ; DESCANSAR

screen_20_action4:
  .byte 255  ; none

screen_20_description:
  .ascii "El suelo se interrumpe de golpe. "
  .ascii "Enciendes la linterna."
  .ascii "Un pozo profundo se abre frente a ti, tan oscuro que no puedes estimar su"
  .ascii "profundidad."
  .ascii ""
  .ascii "Una soga sobresale del pozo y desciende mas alla de tu vision. "
  .ascii "Las paredes del pozo están marcadas con grietas y salientes irregulares. Las"
  .ascii "salientes pueden ayudarte. "
  .ascii "Un descenso seguro llevaria mas tiempo. Un descenso rapido puede ser riesgoso."
  .ascii ""
  .ascii "El agua sigue corriendo."
  .ascii "e"

screen_20_ascii:
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▓▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░"
  .ascii "░░░░░░░░▒▒▒        ║          ▒▒▒░░░░░░░"
  .ascii "░░░░░░▒▒           │   ≡≡≡≡      ▒▒░░░░░"
  .ascii "░░░░░░▒     ≡≡≡≡   ║              ▒░░░░░"
  .ascii "░░░░░░▒            │     ≡≡≡≡     ▒░░░░░"
  .ascii "░░░░░░▒▒           ║             ▒▒░░░░░"
  .ascii "░░░░░░░░▒▒▒    ≡≡≡≡│          ▒▒▒░░░░░░░"
  .ascii "░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "e"

screen_20_flashlight_on:
  .ascii ""
  .ascii "e"

screen_20_flashlight_off:
  .ascii ""
  .ascii "e"

screen_20_enemy_probability:
  .byte 0

screen_20_is_secret_screen:
  .byte 0  ; no

screen_20_is_end_screen:
  .byte 0  ; no

; ── Screen 21: S04P02 ──────────────────────────
screen_21_id:
  .byte 21

screen_21_name:
  .ascii "S04P02"
  .ascii "e"

screen_21_action1:
  .byte 34  ; S04P02-SALIENTES

screen_21_action2:
  .byte 35  ; S04P02-SINSALIENTES

screen_21_action3:
  .byte 36  ; S04P02-EXPLORAR

screen_21_action4:
  .byte 11  ; DESCANSAR

screen_21_description:
  .ascii "Llegas a una gran saliente. Podes explorar la zona o seguir."
  .ascii "e"

screen_21_ascii:
  .ascii ""
  .ascii "e"

screen_21_flashlight_on:
  .ascii ""
  .ascii "e"

screen_21_flashlight_off:
  .ascii ""
  .ascii "e"

screen_21_enemy_probability:
  .byte 0

screen_21_is_secret_screen:
  .byte 0  ; no

screen_21_is_end_screen:
  .byte 0  ; no

; ── Screen 22: S04P03 ──────────────────────────
screen_22_id:
  .byte 22

screen_22_name:
  .ascii "S04P03"
  .ascii "e"

screen_22_action1:
  .byte 37  ; S04P03-SALIENTES

screen_22_action2:
  .byte 38  ; S04P03-SINSALIENTES

screen_22_action3:
  .byte 39  ; S04P03-EXPLORAR

screen_22_action4:
  .byte 11  ; DESCANSAR

screen_22_description:
  .ascii "Llegas a otra zona de descanzo. Puedes explorar la zona o seguir descendiendo."
  .ascii "El fondo parece estar mas cerca."
  .ascii "e"

screen_22_ascii:
  .ascii ""
  .ascii "e"

screen_22_flashlight_on:
  .ascii ""
  .ascii "e"

screen_22_flashlight_off:
  .ascii ""
  .ascii "e"

screen_22_enemy_probability:
  .byte 0

screen_22_is_secret_screen:
  .byte 0  ; no

screen_22_is_end_screen:
  .byte 0  ; no

; ── Screen 23: S04P04 ──────────────────────────
screen_23_id:
  .byte 23

screen_23_name:
  .ascii "S04P04"
  .ascii "e"

screen_23_action1:
  .byte 40  ; S04P04-VOLVER

screen_23_action2:
  .byte 255  ; none

screen_23_action3:
  .byte 255  ; none

screen_23_action4:
  .byte 255  ; none

screen_23_description:
  .ascii "EL CORTE NO PARECE HABER SIDO HECHO DE MANERA NATURAL"
  .ascii "e"

screen_23_ascii:
  .ascii "░░░░║║░░░░"
  .ascii "░░░░││░░░░"
  .ascii "░░░░║║░░░░"
  .ascii "░░░░││░░░░"
  .ascii "░░░░║║░░░░"
  .ascii "░░░░││░░░░"
  .ascii "░░░░║║░░░░"
  .ascii "░░░░│└░░░░"
  .ascii "░░░░│░░░░░"
  .ascii "░░░░░░░░░░"
  .ascii "e"

screen_23_flashlight_on:
  .ascii ""
  .ascii "e"

screen_23_flashlight_off:
  .ascii ""
  .ascii "e"

screen_23_enemy_probability:
  .byte 0

screen_23_is_secret_screen:
  .byte 1  ; yes

screen_23_is_end_screen:
  .byte 0  ; no

; ── Screen 24: S05P01 ──────────────────────────
screen_24_id:
  .byte 24

screen_24_name:
  .ascii "S05P01"
  .ascii "e"

screen_24_action1:
  .byte 41  ; S05P01-SUELO

screen_24_action2:
  .byte 42  ; S05P01-PARED

screen_24_action3:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_24_action4:
  .byte 255  ; none

screen_24_description:
  .ascii "La caverna cambia de textura."
  .ascii "El suelo está cubierto de tierra blanda mezclada con piedra. Cada paso se siente"
  .ascii "amortiguado, como si el lugar absorbiera el peso."
  .ascii "Raíces gruesas y finas atraviesan el suelo y las paredes."
  .ascii "e"

screen_24_ascii:
  .ascii ""
  .ascii "e"

screen_24_flashlight_on:
  .ascii "Tu linterna parpadea."
  .ascii "e"

screen_24_flashlight_off:
  .ascii "Sientes que algo se mueve entre las raices."
  .ascii "e"

screen_24_enemy_probability:
  .byte 0

screen_24_is_secret_screen:
  .byte 0  ; no

screen_24_is_end_screen:
  .byte 0  ; no

; ── Screen 25: S05P02 ──────────────────────────
screen_25_id:
  .byte 25

screen_25_name:
  .ascii "S05P02"
  .ascii "e"

screen_25_action1:
  .byte 43  ; S05P0234-VOLVER

screen_25_action2:
  .byte 44  ; S05P02-EXTRAER

screen_25_action3:
  .byte 255  ; none

screen_25_action4:
  .byte 255  ; none

screen_25_description:
  .ascii "Exploras el suelo."
  .ascii "e"

screen_25_ascii:
  .ascii ""
  .ascii "e"

screen_25_flashlight_on:
  .ascii "Encuentras algo oculto entre las raices."
  .ascii "e"

screen_25_flashlight_off:
  .ascii "No encuentras nada que llame tu atencion."
  .ascii "e"

screen_25_enemy_probability:
  .byte 25

screen_25_is_secret_screen:
  .byte 0  ; no

screen_25_is_end_screen:
  .byte 0  ; no

; ── Screen 26: S05P03 ──────────────────────────
screen_26_id:
  .byte 26

screen_26_name:
  .ascii "S05P03"
  .ascii "e"

screen_26_action1:
  .byte 43  ; S05P0234-VOLVER

screen_26_action2:
  .byte 255  ; none

screen_26_action3:
  .byte 255  ; none

screen_26_action4:
  .byte 255  ; none

screen_26_description:
  .ascii "LA INSCRIPCION DICE \"R.C - 1874-1928\""
  .ascii "e"

screen_26_ascii:
  .ascii "   ▄▄▀▀▀▀▀▀▀▀▀▄▄   "
  .ascii " ▄▀ ░░░░R.C░░░░ ▀▄ "
  .ascii "▄▀░             ░▀▄"
  .ascii "█                 █"
  .ascii "▀█▄▄           ▄▄█▀"
  .ascii " ▀████▄▄▄▄▄▄▄████▀ "
  .ascii "   ▀▀1874-1928▀▀   "
  .ascii "e"

screen_26_flashlight_on:
  .ascii ""
  .ascii "e"

screen_26_flashlight_off:
  .ascii ""
  .ascii "e"

screen_26_enemy_probability:
  .byte 0

screen_26_is_secret_screen:
  .byte 1  ; yes

screen_26_is_end_screen:
  .byte 0  ; no

; ── Screen 27: S05P04 ──────────────────────────
screen_27_id:
  .byte 27

screen_27_name:
  .ascii "S05P04"
  .ascii "e"

screen_27_action1:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_27_action2:
  .byte 43  ; S05P0234-VOLVER

screen_27_action3:
  .byte 46  ; S05P045-CHICAS

screen_27_action4:
  .byte 45  ; S05P04-GRANDES

screen_27_description:
  .ascii ""
  .ascii "e"

screen_27_ascii:
  .ascii "▀▄░░░░▄▀▀▀▄▄░░░░░░░░░░▄▄▀▀░░░░░░░"
  .ascii "░░▀▄▄▀░░░░░░▀▄░░░▄▄▀▀▀░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░▄▀▀▀▄░░░░░░░░▄▀▀▄░░░"
  .ascii "░░░░▄▀▀▀▄░░▄▀░░░░░▀▀▄░░░░█░░░░▀▄░"
  .ascii "▄ ▄▀░░░░░▀▄▀░░░░░░░░░▀▀▄▀▄░░░░░░░"
  .ascii " ▀░░░░░░░▄█░░░░░░░░░▄▄▀░░█░░░░░░░"
  .ascii "░░▄▀▀▄░░█░░▀▄░░░░░▄▀░░░░░░▀▄░░░░░"
  .ascii "░▄▀░░░▀▀░░░░░▀▄▄░░░█░░░░░░░░█░░░░"
  .ascii "█░░░░░░░░░░▄▄▀░░▀▄░░▀▄░░░░░░█░░░░"
  .ascii "░░░░░░░░▄▀▀░░░░░░░▀▄░░█░░░░░░▀▄▀░"
  .ascii "e"

screen_27_flashlight_on:
  .ascii "La pared esta cubierta de raices grandes y pequeñas. Al iluminarlas con la"
  .ascii "linterna, reaccionan."
  .ascii "Tu linterna parpadea."
  .ascii "e"

screen_27_flashlight_off:
  .ascii "La pared esta cubierta de raices de diferentes tamaños. "
  .ascii "Crees sentir un movimiento, que no viene ni de las raices ni de ti."
  .ascii "e"

screen_27_enemy_probability:
  .byte 25

screen_27_is_secret_screen:
  .byte 0  ; no

screen_27_is_end_screen:
  .byte 0  ; no

; ── Screen 28: S05P05 ──────────────────────────
screen_28_id:
  .byte 28

screen_28_name:
  .ascii "S05P05"
  .ascii "e"

screen_28_action1:
  .byte 46  ; S05P045-CHICAS

screen_28_action2:
  .byte 47  ; S05P05-GRANDES

screen_28_action3:
  .byte 255  ; none

screen_28_action4:
  .byte 255  ; none

screen_28_description:
  .ascii "Las raices se abren, pero aun no lo suficiente para que pases."
  .ascii "Debes deecidir cuales iluminar."
  .ascii "e"

screen_28_ascii:
  .ascii ""
  .ascii "e"

screen_28_flashlight_on:
  .ascii ""
  .ascii "e"

screen_28_flashlight_off:
  .ascii ""
  .ascii "e"

screen_28_enemy_probability:
  .byte 25

screen_28_is_secret_screen:
  .byte 0  ; no

screen_28_is_end_screen:
  .byte 0  ; no

; ── Screen 29: S06P01 ──────────────────────────
screen_29_id:
  .byte 29

screen_29_name:
  .ascii "S06P01"
  .ascii "e"

screen_29_action1:
  .byte 48  ; S06P01-RAPIDO

screen_29_action2:
  .byte 11  ; DESCANSAR

screen_29_action3:
  .byte 49  ; S06P01-LENTO

screen_29_action4:
  .byte 255  ; none

screen_29_description:
  .ascii "Abandonas la sala."
  .ascii "El pasaje desciende y se llena de agua oscura. No refleja, pero se mueve."
  .ascii "Tendras que nadar, solo hay una direccion, el tiempo apremia."
  .ascii ""
  .ascii "Calculas que podras atravesar el tunel en 2 esfuerzos, con una pausa para"
  .ascii "respirar en el medio. "
  .ascii "Puedes intentar llegar a la burbuja de aire a un ritmo rapido o lento."
  .ascii ""
  .ascii "La linterna no funcionara debajo del agua. El solo pensar en eso te genera"
  .ascii "incomodidad."
  .ascii "e"

screen_29_ascii:
  .ascii "░░░░░░░░░░░░░▄▄▄▄▄▄▄▄▄▄▄▄▄░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░████▀▀▀▀▀▀▀▀▀████░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░██▀             ▀██░░░░░░░░░░░"
  .ascii "░░░░░░░░░██      ≈  ≈       ██░░░░░░░░░░"
  .ascii "░░░░░░░░███                 ███░░░░░░░░░"
  .ascii "░░░░░░░░██░   ≈    ≈     ≈  ░██░░░░░░░░░"
  .ascii "▒▒▒▒▒▒▒▒░░                   ░░▒▒▒▒▒▒▒▒▒"
  .ascii "▒▒▒▒▒▒▒░░                     ░░▒▒▒▒▒▒▒▒"
  .ascii "▒▒▒▒▒▒░░      ≈       ≈        ░░▒▒▒▒▒▒▒"
  .ascii "▒▒▒▒▒░░                         ░░▒▒▒▒▒▒"
  .ascii "e"

screen_29_flashlight_on:
  .ascii ""
  .ascii "e"

screen_29_flashlight_off:
  .ascii ""
  .ascii "e"

screen_29_enemy_probability:
  .byte 0

screen_29_is_secret_screen:
  .byte 0  ; no

screen_29_is_end_screen:
  .byte 0  ; no

; ── Screen 30: S06P02 ──────────────────────────
screen_30_id:
  .byte 30

screen_30_name:
  .ascii "S06P02"
  .ascii "e"

screen_30_action1:
  .byte 50  ; S06P02-RAPIDO

screen_30_action2:
  .byte 51  ; S06P02-LENTO

screen_30_action3:
  .byte 52  ; S06P02-EXPLORAR

screen_30_action4:
  .byte 255  ; none

screen_30_description:
  .ascii "Llegas a una burbuja de aire. "
  .ascii "Aun te falta un tramo para llegar al final del tunel. "
  .ascii "No puedes descansar, no tienes donde. Mantenerte a flote es primordial."
  .ascii "Algo llama tu atencion debajo del agua."
  .ascii "e"

screen_30_ascii:
  .ascii ""
  .ascii "e"

screen_30_flashlight_on:
  .ascii ""
  .ascii "e"

screen_30_flashlight_off:
  .ascii ""
  .ascii "e"

screen_30_enemy_probability:
  .byte 0

screen_30_is_secret_screen:
  .byte 0  ; no

screen_30_is_end_screen:
  .byte 0  ; no

; ── Screen 31: S06P03 ──────────────────────────
screen_31_id:
  .byte 31

screen_31_name:
  .ascii "S06P03"
  .ascii "e"

screen_31_action1:
  .byte 53  ; S06P03-VOLVER

screen_31_action2:
  .byte 255  ; none

screen_31_action3:
  .byte 255  ; none

screen_31_action4:
  .byte 255  ; none

screen_31_description:
  .ascii "UNA LINTERNA SIMILAR A LA TUYA, ENCENDIDA BAJO EL AGUA. "
  .ascii "OTRAS COSAS TAMBIEN BRILLAN AHI."
  .ascii ""
  .ascii "¿ES ACASO ESTO UN SUEÑO?"
  .ascii "e"

screen_31_ascii:
  .ascii "             ≈                   ≈      "
  .ascii "                   ♦    ♦               "
  .ascii "     ≈               ≈        ≈         "
  .ascii "          ▄▀▀█▀▀▀▄                      "
  .ascii "         █▓▓▓▓█   █▀▀▀▀▀▀▀▀▀▀▄      ≈   "
  .ascii " ≈      █▓▓▓▓▓▓█              █         "
  .ascii "         █▓▓▓▓█   █▄▄▄▄▄▄▄▄▄▄▀          "
  .ascii "          ▀▄▄█▄▄▄▀                      "
  .ascii "   ≈                 ≈           ≈      "
  .ascii "                                        "
  .ascii "e"

screen_31_flashlight_on:
  .ascii ""
  .ascii "e"

screen_31_flashlight_off:
  .ascii ""
  .ascii "e"

screen_31_enemy_probability:
  .byte 0

screen_31_is_secret_screen:
  .byte 1  ; yes

screen_31_is_end_screen:
  .byte 0  ; no

; ── Screen 32: S07P01 ──────────────────────────
screen_32_id:
  .byte 32

screen_32_name:
  .ascii "S07P01"
  .ascii "e"

screen_32_action1:
  .byte 54  ; S07P01-ILUMINAR

screen_32_action2:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_32_action3:
  .byte 11  ; DESCANSAR

screen_32_action4:
  .byte 255  ; none

screen_32_description:
  .ascii "Logras cruzar el tunel sumergido y llegas a una sala."
  .ascii "No logras visualizar ninguna salida."
  .ascii "e"

screen_32_ascii:
  .ascii ""
  .ascii "e"

screen_32_flashlight_on:
  .ascii "El espacio se abre en una sala circular, claramente distinta al resto de la"
  .ascii "caverna."
  .ascii "Las paredes son más regulares. El suelo está nivelado. En el centro hay una"
  .ascii "estructura de piedra baja, erosionada pero intencional, como un altar olvidado."
  .ascii "Tu linterna parpadea."
  .ascii "e"

screen_32_flashlight_off:
  .ascii "Las paredes de la sala no tienen relieve que marque una salida. "
  .ascii "Hay un pequeño pilar en el interior."
  .ascii "e"

screen_32_enemy_probability:
  .byte 0

screen_32_is_secret_screen:
  .byte 0  ; no

screen_32_is_end_screen:
  .byte 0  ; no

; ── Screen 33: S07P02 ──────────────────────────
screen_33_id:
  .byte 33

screen_33_name:
  .ascii "S07P02"
  .ascii "e"

screen_33_action1:
  .byte 55  ; S07P02-SIMBOLOS

screen_33_action2:
  .byte 56  ; S07P02-ESTRELLA

screen_33_action3:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_33_action4:
  .byte 11  ; DESCANSAR

screen_33_description:
  .ascii "Estar en el centro de la sala genera una sensación de exposición, como si el"
  .ascii "lugar hubiera sido diseñado para observar lo que ocurre ahí."
  .ascii "El pilar contiene simbolos que pueden ser presionados."
  .ascii "e"

screen_33_ascii:
  .ascii "███████████████████████████████"
  .ascii "██RECUERDA TU CAMINO.██████████"
  .ascii "██EL FINAL SE ACERCA.███┌───┐██"
  .ascii "████████████████████████│ ☼ │██"
  .ascii "██┌────┐ ┌───┐ ┌───┐████└───┘██"
  .ascii "██│ ▲▼ │ │ ║ │ │ ≈ │███████████"
  .ascii "██└────┘ └───┘ └───┘███████████"
  .ascii "███████████████████████████████"
  .ascii "e"

screen_33_flashlight_on:
  .ascii "Tu linterna parpadea"
  .ascii "e"

screen_33_flashlight_off:
  .ascii ""
  .ascii "e"

screen_33_enemy_probability:
  .byte 40

screen_33_is_secret_screen:
  .byte 0  ; no

screen_33_is_end_screen:
  .byte 0  ; no

; ── Screen 34: S07P03 ──────────────────────────
screen_34_id:
  .byte 34

screen_34_name:
  .ascii "S07P03"
  .ascii "e"

screen_34_action1:
  .byte 58  ; S07P03-LINEA

screen_34_action2:
  .byte 59  ; S07P03-ONDAS

screen_34_action3:
  .byte 57  ; S07P03-TRIANGULOS

screen_34_action4:
  .byte 60  ; S07P345-VOLVER

screen_34_description:
  .ascii "Estas frente a los simbolos."
  .ascii "Debes elegir cuales presionar."
  .ascii "e"

screen_34_ascii:
  .ascii ""
  .ascii "e"

screen_34_flashlight_on:
  .ascii ""
  .ascii "e"

screen_34_flashlight_off:
  .ascii ""
  .ascii "e"

screen_34_enemy_probability:
  .byte 40

screen_34_is_secret_screen:
  .byte 0  ; no

screen_34_is_end_screen:
  .byte 0  ; no

; ── Screen 35: S07P04 ──────────────────────────
screen_35_id:
  .byte 35

screen_35_name:
  .ascii "S07P04"
  .ascii "e"

screen_35_action1:
  .byte 61  ; S07P04-LINEA

screen_35_action2:
  .byte 62  ; S07P04-ONDAS

screen_35_action3:
  .byte 63  ; S07P04-TRIANGULOS

screen_35_action4:
  .byte 60  ; S07P345-VOLVER

screen_35_description:
  .ascii "Se produjo un cambio en la sala."
  .ascii "La pared se agrieta, dejando entrar una hendija de luz."
  .ascii ""
  .ascii "Estas frente a los simbolos."
  .ascii "Debes elegir cuales presionar."
  .ascii "e"

screen_35_ascii:
  .ascii ""
  .ascii "e"

screen_35_flashlight_on:
  .ascii ""
  .ascii "e"

screen_35_flashlight_off:
  .ascii ""
  .ascii "e"

screen_35_enemy_probability:
  .byte 40

screen_35_is_secret_screen:
  .byte 0  ; no

screen_35_is_end_screen:
  .byte 0  ; no

; ── Screen 36: S07P05 ──────────────────────────
screen_36_id:
  .byte 36

screen_36_name:
  .ascii "S07P05"
  .ascii "e"

screen_36_action1:
  .byte 65  ; S07P05-LINEA

screen_36_action2:
  .byte 64  ; S07P05-ONDAS

screen_36_action3:
  .byte 66  ; S07P05-TRIANGULOS

screen_36_action4:
  .byte 60  ; S07P345-VOLVER

screen_36_description:
  .ascii "Se produjo un nuevo cambio en la sala."
  .ascii "La grieta comienza a crecer, aun no lo suficiente para que pases a traves de"
  .ascii "ella."
  .ascii ""
  .ascii "Estas frente a los simbolos."
  .ascii "Debes elegir cuales presionar."
  .ascii "e"

screen_36_ascii:
  .ascii ""
  .ascii "e"

screen_36_flashlight_on:
  .ascii ""
  .ascii "e"

screen_36_flashlight_off:
  .ascii ""
  .ascii "e"

screen_36_enemy_probability:
  .byte 40

screen_36_is_secret_screen:
  .byte 0  ; no

screen_36_is_end_screen:
  .byte 0  ; no

; ── Screen 37: S07P06 ──────────────────────────
screen_37_id:
  .byte 37

screen_37_name:
  .ascii "S07P06"
  .ascii "e"

screen_37_action1:
  .byte 67  ; S07P06-CONTINUAR

screen_37_action2:
  .byte 255  ; none

screen_37_action3:
  .byte 255  ; none

screen_37_action4:
  .byte 255  ; none

screen_37_description:
  .ascii "EN EL CENTRO DE LA ESTRELLA APARECE UN OJO Y UNA LEYENDA SE IMPRIME EN TU MENTE."
  .ascii "EL MIEDO SE APODERA DE TI. LO QUE LEISTE FUE DEMASIADO PARA TU CORDURA."
  .ascii ""
  .ascii "e"

screen_37_ascii:
  .ascii "              ██               "
  .ascii "             ████              "
  .ascii "            ▄████▄             "
  .ascii "        ████░░░░░░████         "
  .ascii "         ▀█░░░0δ░░░█▀          "
  .ascii "           █░░░░░░█            "
  .ascii "          ██▀▀  ▀▀██           "
  .ascii "         ██        ██          "
  .ascii "                               "
  .ascii "Y'bthnk...H 'ehye n'grkdl'lh..."
  .ascii "e"

screen_37_flashlight_on:
  .ascii ""
  .ascii "e"

screen_37_flashlight_off:
  .ascii ""
  .ascii "e"

screen_37_enemy_probability:
  .byte 0

screen_37_is_secret_screen:
  .byte 1  ; yes

screen_37_is_end_screen:
  .byte 0  ; no

; ── Screen 38: FINAL ──────────────────────────
screen_38_id:
  .byte 38

screen_38_name:
  .ascii "FINAL"
  .ascii "e"

screen_38_action1:
  .byte 255  ; none

screen_38_action2:
  .byte 255  ; none

screen_38_action3:
  .byte 255  ; none

screen_38_action4:
  .byte 255  ; none

screen_38_description:
  .ascii "Pasas a traves de la grieta con mucho esfuerzo."
  .ascii "Lo primero que notas es que respiras aire fresco. Luego, el abrazo de la luz"
  .ascii "solar."
  .ascii ""
  .ascii "Con el resto de tus fuerzas, continuas arrastrandote hasta terminar de salir."
  .ascii ""
  .ascii "El agua no te sigue."
  .ascii "La caverna no se derrumba."
  .ascii "Simplemente deja de importarte..."
  .ascii "e"

screen_38_ascii:
  .ascii "    .     .     .   "
  .ascii "  ◄    .            "
  .ascii "     .     .  .  .  "
  .ascii "  .     .           "
  .ascii "    .       .  .    "
  .ascii "       ░░░          "
  .ascii "   ░░░░░░░░         "
  .ascii " ░░░░░░░░░░░░       "
  .ascii "░░░░░░░░░º░░░░  ¥ ¥ "
  .ascii "▒▒▒▒▒▒▒▒▓▓▓▒▒▒▒▒▒▒▒▒"
  .ascii "▒▒▒▒▒▒▒▒▒▓▓▓▒▒▒▒▒▒▒▒"
  .ascii "▒▒▒▒▒▒▒▒▒▒▒▓▓▒▒▒▒▒▒▒"
  .ascii "                    "
  .ascii " ESCAPASTE DE       "
  .ascii " LA CAVERNA         "
  .ascii "                    "
  .ascii " TU HUMANIDAD QUEDO "
  .ascii " ENTERRADA ALLI     "
  .ascii "e"

screen_38_flashlight_on:
  .ascii ""
  .ascii "e"

screen_38_flashlight_off:
  .ascii ""
  .ascii "e"

screen_38_enemy_probability:
  .byte 0

screen_38_is_secret_screen:
  .byte 0  ; no

screen_38_is_end_screen:
  .byte 0  ; no

; ── Screen 39: EndScreenSimulationTimeisUp ──────────────────────────
screen_39_id:
  .byte 39

screen_39_name:
  .ascii "EndScreenSimulationTimeisUp"
  .ascii "e"

screen_39_action1:
  .byte 68  ; TERMINAR EL JUEGO

screen_39_action2:
  .byte 255  ; none

screen_39_action3:
  .byte 255  ; none

screen_39_action4:
  .byte 255  ; none

screen_39_description:
  .ascii ""
  .ascii "e"

screen_39_ascii:
  .ascii "█████████████"
  .ascii "█▄▄▄▄▄▄▄▄▄▄▄█"
  .ascii " █         █ "
  .ascii "  ▀▄     ▄▀  "
  .ascii "    ▀▄ ▄▀    "
  .ascii "     █ █     "
  .ascii "   ▄▀ ▄ ▀▄   "
  .ascii " ▄▀ ▄ ▄ ▄ ▀▄ "
  .ascii "▄█▄█▄█▄█▄█▄█▄"
  .ascii "█▄▄▄▄▄▄▄▄▄▄▄█"
  .ascii "▀▀▀▀▀▀▀▀▀▀▀▀▀"
  .ascii "             "
  .ascii "EL AGUA INUND"
  .ascii "             "
  .ascii " LA CAVERNA  "
  .ascii "e"

screen_39_flashlight_on:
  .ascii ""
  .ascii "e"

screen_39_flashlight_off:
  .ascii ""
  .ascii "e"

screen_39_enemy_probability:
  .byte 0

screen_39_is_secret_screen:
  .byte 0  ; no

screen_39_is_end_screen:
  .byte 1  ; yes

; ── Screen 40: endScreenByEnemy ──────────────────────────
screen_40_id:
  .byte 40

screen_40_name:
  .ascii "endScreenByEnemy"
  .ascii "e"

screen_40_action1:
  .byte 68  ; TERMINAR EL JUEGO

screen_40_action2:
  .byte 255  ; none

screen_40_action3:
  .byte 255  ; none

screen_40_action4:
  .byte 255  ; none

screen_40_description:
  .ascii ""
  .ascii "e"

screen_40_ascii:
  .ascii "    ♦     ♦    "
  .ascii "               "
  .ascii "               "
  .ascii "               "
  .ascii "               "
  .ascii "               "
  .ascii "               "
  .ascii "               "
  .ascii "               "
  .ascii "TIENES COMPAÑIA"
  .ascii "               "
  .ascii " EN LA CAVERNA "
  .ascii "e"

screen_40_flashlight_on:
  .ascii ""
  .ascii "e"

screen_40_flashlight_off:
  .ascii ""
  .ascii "e"

screen_40_enemy_probability:
  .byte 0

screen_40_is_secret_screen:
  .byte 0  ; no

screen_40_is_end_screen:
  .byte 1  ; yes

; ── Screen 41: endScreenByActionFailed ──────────────────────────
screen_41_id:
  .byte 41

screen_41_name:
  .ascii "endScreenByActionFailed"
  .ascii "e"

screen_41_action1:
  .byte 68  ; TERMINAR EL JUEGO

screen_41_action2:
  .byte 255  ; none

screen_41_action3:
  .byte 255  ; none

screen_41_action4:
  .byte 255  ; none

screen_41_description:
  .ascii ""
  .ascii "e"

screen_41_ascii:
  .ascii "  ▄▄▄▄▄▄▄▄▄  "
  .ascii " ███████████ "
  .ascii "█████████████"
  .ascii "███  ███  ███"
  .ascii "█████████████"
  .ascii " █████ █████ "
  .ascii "  █████████  "
  .ascii "   █ █ █ █   "
  .ascii "   ███████   "
  .ascii "    ▀▀▀▀▀    "
  .ascii "             "
  .ascii " LA CAVERNA  "
  .ascii "             "
  .ascii "   DECIDIO   "
  .ascii "             "
  .ascii " TU DESTINO  "
  .ascii "e"

screen_41_flashlight_on:
  .ascii ""
  .ascii "e"

screen_41_flashlight_off:
  .ascii ""
  .ascii "e"

screen_41_enemy_probability:
  .byte 0

screen_41_is_secret_screen:
  .byte 0  ; no

screen_41_is_end_screen:
  .byte 1  ; yes

; ── Total screen count ──────────────────────────────────────
screen_count:
  .byte 42

; ── Total secret screens count ──────────────────────────────
screens_with_secrets:
  .byte 7
