import json
import os
import sys
sys.stdout.reconfigure(encoding='utf-8')

JSON_FILE  = "acs_actions.json"
ASM_BANK0  = "acs_actions_bank0.asm"
ASM_BANK1  = "acs_actions_headers_bank1.asm"


def ascii_lines(text):
    """
    Split text on real newline characters and return a list of .ascii directive strings.
    Each segment becomes its own .ascii line; a .ascii "\\n" line is inserted between
    segments so the newline character is preserved in the assembled output.
    Lines are wrapped at a maximum of 80 characters without cutting words in half.
    """
    segments = text.split("\n")
    out = []
    for seg in segments:
        while len(seg) > 80:
            # Find the last space at or before position 80
            cut = seg.rfind(" ", 0, 81)
            if cut <= 0:
                # No space found — force cut at 80 to avoid infinite loop
                cut = 80
            out.append(f'  .ascii "{seg[:cut]}"')
            seg = seg[cut:].lstrip(" ")
        out.append(f'  .ascii "{seg}"')
    return out


def sanitize_id(name):
    """Turn an action name into a safe ASM label prefix (lowercase, spaces→_)."""
    return name.strip().lower().replace(" ", "_").replace("-", "_")


def to_asm(actions):
    """
    Returns a tuple (bank0_asm, bank1_asm).
      bank0 = full original output                    (acs_actions_bank0.asm)
      bank1 = header offsets, record length, count     (acs_actions_headers_bank1.asm)
    """

    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Actions — auto-generated by acs_actions_to_asm.py")
    lines.append("; ============================================================")
    lines.append("")

    # ── Action index table (pointer to the start of each action record) ──────
    lines.append("actions_index:")
    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        name   = act.get("Name", key)
        lines.append(f"  .word action_pointer_{act_id}  ; {name}")
    lines.append(f"actions_index_record_length:")
    lines.append(f"  .byte 2  ; each actions_index entry is 1 .word (2 bytes)")
    lines.append("")

    # ── Pointer table ────────────────────────────────────────
    lines.append("actions_pointers:")
    offset = 0

    # Captured from action 0 for offset labels emitted after all entries
    act0_name_offset              = None
    act0_alias_offset             = None
    act0_sensor_id_offset         = None
    act0_sensor_active_offset     = None
    act0_description_offset       = None
    act0_desc_failed_offset       = None
    act0_screen_offset            = None
    act0_cost_offset              = None
    act0_enemy_probability_offset = None
    act0_reset_enemy_prob_offset  = None
    act0_death_probability_offset = None
    act0_hide_water_offset        = None
    act0_hide_fear_offset         = None
    act0_hide_flashlight_offset   = None
    act0_record_length            = None

    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        label  = f"action_{act_id}"
        name   = act.get("Name", key)

        start_offset = offset

        lines.append(f"action_pointer_{act_id}:")
        lines.append(f"  .word {label}_id            ; {name} id            [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_name          ; {name} name          [{offset},{offset+1}]") ; _nam = offset ; offset += 2
        lines.append(f"  .word {label}_alias         ; {name} alias         [{offset},{offset+1}]") ; _ali = offset ; offset += 2
        lines.append(f"  .word {label}_sensor_id     ; {name} sensor_id     [{offset},{offset+1}]") ; _sid = offset ; offset += 2
        lines.append(f"  .word {label}_sensor_active ; {name} sensor_active [{offset},{offset+1}]") ; _act = offset ;offset += 2
        lines.append(f"  .word {label}_screen        ; {name} screen        [{offset},{offset+1}]") ; _scr = offset ; offset += 2
        lines.append(f"  .word {label}_cost              ; {name} cost              [{offset},{offset+1}]") ; _cst = offset ; offset += 2
        lines.append(f"  .word {label}_enemy_probability ; {name} enemy_probability [{offset},{offset+1}]") ; _enm = offset ; offset += 2
        lines.append(f"  .word {label}_reset_enemy_prob  ; {name} reset_enemy_prob  [{offset},{offset+1}]") ; _rep = offset ; offset += 2
        lines.append(f"  .word {label}_death_probability ; {name} death_probability [{offset},{offset+1}]") ; _dth = offset ; offset += 2
        lines.append(f"  .word {label}_description       ; {name} description       [{offset},{offset+1}]") ; _dsc = offset ; offset += 2
        lines.append(f"  .word {label}_desc_action_failed ; {name} desc_action_failed [{offset},{offset+1}]") ; _daf = offset ; offset += 2
        lines.append(f"  .word {label}_hide_water         ; {name} hide_water         [{offset},{offset+1}]") ; _swt = offset ; offset += 2
        lines.append(f"  .word {label}_hide_fear          ; {name} hide_fear          [{offset},{offset+1}]") ; _sfr = offset ; offset += 2
        lines.append(f"  .word {label}_hide_flashlight    ; {name} hide_flashlight    [{offset},{offset+1}]") ; _sfl = offset ; offset += 2

        if index == 0:
            act0_name_offset              = _nam
            act0_alias_offset             = _ali
            act0_sensor_id_offset         = _sid
            act0_sensor_active_offset     = _act
            act0_screen_offset            = _scr
            act0_cost_offset              = _cst
            act0_enemy_probability_offset = _enm
            act0_reset_enemy_prob_offset  = _rep
            act0_death_probability_offset = _dth
            act0_description_offset       = _dsc
            act0_desc_failed_offset       = _daf
            act0_hide_water_offset        = _swt
            act0_hide_fear_offset         = _sfr
            act0_hide_flashlight_offset   = _sfl
            act0_record_length            = offset - start_offset

    # -- Offset labels, placed after all action entries
    lines.append(f"action_name_offset:")
    lines.append(f"  .byte {act0_name_offset}  ; (byte of action_0_name in actions_pointers)")
    lines.append(f"action_alias_offset:")
    lines.append(f"  .byte {act0_alias_offset}  ; (byte of action_0_alias in actions_pointers)")
    lines.append(f"action_sensor_id_offset:")
    lines.append(f"  .byte {act0_sensor_id_offset}  ; (byte of action_0_sensor_id in actions_pointers)")
    lines.append(f"action_sensor_active_offset:")
    lines.append(f"  .byte {act0_sensor_active_offset}  ; (byte of action_0_sensor_active in actions_pointers)")
    lines.append(f"action_screen_offset:")
    lines.append(f"  .byte {act0_screen_offset}  ; (byte of action_0_screen in actions_pointers)")
    lines.append(f"action_cost_offset:")
    lines.append(f"  .byte {act0_cost_offset}  ; (byte of action_0_cost in actions_pointers)")
    lines.append(f"action_enemy_probability_offset:")
    lines.append(f"  .byte {act0_enemy_probability_offset}  ; (byte of action_0_enemy_probability in actions_pointers)")
    lines.append(f"action_reset_enemy_prob_offset:")
    lines.append(f"  .byte {act0_reset_enemy_prob_offset}  ; (byte of action_0_reset_enemy_prob in actions_pointers)")
    lines.append(f"action_death_probability_offset:")
    lines.append(f"  .byte {act0_death_probability_offset}  ; (byte of action_0_death_probability in actions_pointers)")
    lines.append(f"action_description_offset:")
    lines.append(f"  .byte {act0_description_offset}  ; (byte of action_0_description in actions_pointers)")
    lines.append(f"action_desc_action_failed_offset:")
    lines.append(f"  .byte {act0_desc_failed_offset}  ; (byte of action_0_desc_action_failed in actions_pointers)")
    lines.append(f"action_hide_water_offset:")
    lines.append(f"  .byte {act0_hide_water_offset}  ; (byte of action_0_hide_water in actions_pointers)")
    lines.append(f"action_hide_fear_offset:")
    lines.append(f"  .byte {act0_hide_fear_offset}  ; (byte of action_0_hide_fear in actions_pointers)")
    lines.append(f"action_hide_flashlight_offset:")
    lines.append(f"  .byte {act0_hide_flashlight_offset}  ; (byte of action_0_hide_flashlight in actions_pointers)")
    lines.append(f"action_record_length:")
    lines.append(f"  .byte {act0_record_length}  ; (total .word bytes per action record)")
    lines.append("")

    for index, (key, act) in enumerate(actions.items()):
        act_id     = act.get("ID",          str(index)).strip()
        label      = f"action_{act_id}"
        name_str   = act.get("Name",        "").replace('"', '\\"')
        desc_str   = act.get("Description", "").replace('"', '\\"')

        # Sensor ID — stored as SensorID in JSON, 255 = no sensor
        try:
            sensor_id_val = int(act.get("SensorID", 255))
        except (ValueError, TypeError):
            sensor_id_val = 255
        if sensor_id_val < 0 or sensor_id_val > 254:
            sensor_id_val = 255

        # SensorActive — boolean stored as SensorActive in JSON
        sensor_active_raw = act.get("SensorActive", False)
        if isinstance(sensor_active_raw, bool):
            sensor_active_val = 1 if sensor_active_raw else 0
        elif isinstance(sensor_active_raw, str):
            sensor_active_val = 1 if sensor_active_raw.lower() in ("true", "1", "yes") else 0
        else:
            sensor_active_val = 1 if sensor_active_raw else 0

        sensor_name_comment = act.get("Sensor", "none") or "none"

        lines.append(f"; ── Action {act_id}: {act.get('Name', key)} ──────────────────────────")

        # ID
        lines.append(f"{label}_id:")
        lines.append(f"  .byte {act_id}")
        lines.append("")

        # Name
        lines.append(f"{label}_name:")
        lines.extend(ascii_lines(name_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # Alias
        alias_str = act.get("Alias", "").replace('"', '\\"')
        lines.append(f"{label}_alias:")
        lines.extend(ascii_lines(alias_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # Sensor ID
        lines.append(f"{label}_sensor_id:")
        lines.append(f"  .byte {sensor_id_val}  ; {sensor_name_comment}")
        lines.append("")

        # Sensor Active
        lines.append(f"{label}_sensor_active:")
        lines.append(f"  .byte {sensor_active_val}  ; {'on' if sensor_active_val else 'off'}")
        lines.append("")

        # Screen ID
        try:
            screen_id_val = int(act.get("ScreenID", 255))
        except (ValueError, TypeError):
            screen_id_val = 255
        if screen_id_val < 0 or screen_id_val > 254:
            screen_id_val = 255
        lines.append(f"{label}_screen:")
        lines.append(f"  .byte {screen_id_val}  ; screen id")
        lines.append("")

        # Cost
        cost_val = act.get("Cost", 0)
        try:
            cost_val = int(cost_val)
            cost_val = max(0, min(256, cost_val))
        except (ValueError, TypeError):
            cost_val = 0
        lines.append(f"{label}_cost:")
        lines.append(f"  .byte {cost_val}")
        lines.append("")

        # Enemy Probability
        try:
            enemy_prob_val = int(act.get("EnemyProbability", 0))
            enemy_prob_val = max(0, min(255, enemy_prob_val))
        except (ValueError, TypeError):
            enemy_prob_val = 0
        lines.append(f"{label}_enemy_probability:")
        lines.append(f"  .byte {enemy_prob_val}")
        lines.append("")

        # Reset Enemy Probability
        try:
            reset_enemy_val = int(act.get("ResetEnemyProbability", 0))
            reset_enemy_val = 1 if reset_enemy_val else 0
        except (ValueError, TypeError):
            reset_enemy_val = 0
        lines.append(f"{label}_reset_enemy_prob:")
        lines.append(f"  .byte {reset_enemy_val}  ; {'on' if reset_enemy_val else 'off'}")
        lines.append("")

        # Death Probability
        try:
            death_prob_val = int(act.get("DeathProbability", 0))
            death_prob_val = max(0, min(255, death_prob_val))
        except (ValueError, TypeError):
            death_prob_val = 0
        lines.append(f"{label}_death_probability:")
        lines.append(f"  .byte {death_prob_val}")
        lines.append("")

        # Description
        lines.append(f"{label}_description:")
        lines.extend(ascii_lines(desc_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # Description Action Failed
        desc_failed_str = act.get("DescriptionActionFailed", "").replace('"', '\\"')
        lines.append(f"{label}_desc_action_failed:")
        lines.extend(ascii_lines(desc_failed_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # Hide on Water Level High
        try:
            hide_water_val = int(act.get("HideOnWaterLevelHigh", 0))
            hide_water_val = 1 if hide_water_val else 0
        except (ValueError, TypeError):
            hide_water_val = 0
        lines.append(f"{label}_hide_water:")
        lines.append(f"  .byte {hide_water_val}  ; {'on' if hide_water_val else 'off'}")
        lines.append("")

        # Hide on Fear Level High
        try:
            hide_fear_val = int(act.get("HideOnFearLevelHigh", 0))
            hide_fear_val = 1 if hide_fear_val else 0
        except (ValueError, TypeError):
            hide_fear_val = 0
        lines.append(f"{label}_hide_fear:")
        lines.append(f"  .byte {hide_fear_val}  ; {'on' if hide_fear_val else 'off'}")
        lines.append("")

        # Hide with Flashlight Off
        try:
            hide_flashlight_val = int(act.get("HideWithFlashlightOff", 0))
            hide_flashlight_val = 1 if hide_flashlight_val else 0
        except (ValueError, TypeError):
            hide_flashlight_val = 0
        lines.append(f"{label}_hide_flashlight:")
        lines.append(f"  .byte {hide_flashlight_val}  ; {'on' if hide_flashlight_val else 'off'}")
        lines.append("")

    # ── Action count constant ─────────────────────────────────
    lines.append("; ── Total action count ──────────────────────────────────────")
    lines.append("action_count:")
    lines.append(f"  .byte {len(actions)}")
    lines.append("")

    bank0_asm = "\n".join(lines)

    # ==================================================================
    #  Bank 1 — headers only (offsets, record length, count)
    # ==================================================================
    hdr = []
    hdr.append("; ============================================================")
    hdr.append(";  ACS Actions — auto-generated by acs_actions_to_asm.py")
    hdr.append("; ============================================================")
    hdr.append("")
    hdr.append(f"actions_index_record_length:")
    hdr.append(f"  .byte 2  ; each actions_index entry is 1 .word (2 bytes)")
    hdr.append(f"action_name_offset:")
    hdr.append(f"  .byte {act0_name_offset}  ; (byte of action_0_name in actions_pointers)")
    hdr.append(f"action_alias_offset:")
    hdr.append(f"  .byte {act0_alias_offset}  ; (byte of action_0_alias in actions_pointers)")
    hdr.append(f"action_sensor_id_offset:")
    hdr.append(f"  .byte {act0_sensor_id_offset}  ; (byte of action_0_sensor_id in actions_pointers)")
    hdr.append(f"action_sensor_active_offset:")
    hdr.append(f"  .byte {act0_sensor_active_offset}  ; (byte of action_0_sensor_active in actions_pointers)")
    hdr.append(f"action_screen_offset:")
    hdr.append(f"  .byte {act0_screen_offset}  ; (byte of action_0_screen in actions_pointers)")
    hdr.append(f"action_cost_offset:")
    hdr.append(f"  .byte {act0_cost_offset}  ; (byte of action_0_cost in actions_pointers)")
    hdr.append(f"action_enemy_probability_offset:")
    hdr.append(f"  .byte {act0_enemy_probability_offset}  ; (byte of action_0_enemy_probability in actions_pointers)")
    hdr.append(f"action_reset_enemy_prob_offset:")
    hdr.append(f"  .byte {act0_reset_enemy_prob_offset}  ; (byte of action_0_reset_enemy_prob in actions_pointers)")
    hdr.append(f"action_death_probability_offset:")
    hdr.append(f"  .byte {act0_death_probability_offset}  ; (byte of action_0_death_probability in actions_pointers)")
    hdr.append(f"action_description_offset:")
    hdr.append(f"  .byte {act0_description_offset}  ; (byte of action_0_description in actions_pointers)")
    hdr.append(f"action_desc_action_failed_offset:")
    hdr.append(f"  .byte {act0_desc_failed_offset}  ; (byte of action_0_desc_action_failed in actions_pointers)")
    hdr.append(f"action_hide_water_offset:")
    hdr.append(f"  .byte {act0_hide_water_offset}  ; (byte of action_0_hide_water in actions_pointers)")
    hdr.append(f"action_hide_fear_offset:")
    hdr.append(f"  .byte {act0_hide_fear_offset}  ; (byte of action_0_hide_fear in actions_pointers)")
    hdr.append(f"action_hide_flashlight_offset:")
    hdr.append(f"  .byte {act0_hide_flashlight_offset}  ; (byte of action_0_hide_flashlight in actions_pointers)")
    hdr.append(f"action_record_length:")
    hdr.append(f"  .byte {act0_record_length}  ; (total .word bytes per action record)")
    hdr.append("; ── Total action count ──────────────────────────────────────")
    hdr.append("action_count:")
    hdr.append(f"  .byte {len(actions)}")
    hdr.append("")

    bank1_asm = "\n".join(hdr)

    return bank0_asm, bank1_asm


def main():
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found. Run the ACS editor first.")
        return

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        actions = json.load(f)

    if not actions:
        print("[WARNING] No actions found in the JSON file.")
        return

    actions = dict(sorted(actions.items(), key=lambda item: int(item[1].get("ID", 0))))

    bank0_asm, bank1_asm = to_asm(actions)

    with open(ASM_BANK0, "w", encoding="utf-8") as f:
        f.write(bank0_asm)

    with open(ASM_BANK1, "w", encoding="utf-8") as f:
        f.write(bank1_asm)

    print(f"[OK] Generated '{ASM_BANK0}' (data) and '{ASM_BANK1}' (headers) with {len(actions)} action(s).")


if __name__ == "__main__":
    main()
