; ============================================================
;  ACS Actions — auto-generated by acs_actions_to_asm.py
; ============================================================

actions_index_record_length:
  .byte 2  ; each actions_index entry is 1 .word (2 bytes)
action_name_offset:
  .byte 2  ; (byte of action_0_name in actions_pointers)
action_alias_offset:
  .byte 4  ; (byte of action_0_alias in actions_pointers)
action_sensor_id_offset:
  .byte 6  ; (byte of action_0_sensor_id in actions_pointers)
action_sensor_active_offset:
  .byte 8  ; (byte of action_0_sensor_active in actions_pointers)
action_screen_offset:
  .byte 10  ; (byte of action_0_screen in actions_pointers)
action_cost_offset:
  .byte 12  ; (byte of action_0_cost in actions_pointers)
action_enemy_probability_offset:
  .byte 14  ; (byte of action_0_enemy_probability in actions_pointers)
action_reset_enemy_prob_offset:
  .byte 16  ; (byte of action_0_reset_enemy_prob in actions_pointers)
action_death_probability_offset:
  .byte 18  ; (byte of action_0_death_probability in actions_pointers)
action_description_offset:
  .byte 20  ; (byte of action_0_description in actions_pointers)
action_desc_action_failed_offset:
  .byte 22  ; (byte of action_0_desc_action_failed in actions_pointers)
action_hide_water_offset:
  .byte 24  ; (byte of action_0_hide_water in actions_pointers)
action_hide_fear_offset:
  .byte 26  ; (byte of action_0_hide_fear in actions_pointers)
action_hide_flashlight_offset:
  .byte 28  ; (byte of action_0_hide_flashlight in actions_pointers)
action_record_length:
  .byte 30  ; (total .word bytes per action record)
; ── Total action count ──────────────────────────────────────
action_count:
  .byte 69
