import json
import os
import sys
import sys
sys.stdout.reconfigure(encoding='utf-8')

JSON_FILE    = "acs_screens.json"
PUZZLES_FILE = "acs_puzzles.json"
ACTIONS_FILE = "acs_actions.json"
ASM_FILE     = "acs_screens.asm"


def load_name_to_id(filepath, id_field="ID", name_field="Name"):
    """Load a JSON file and return a dict { name -> id }."""
    if not os.path.exists(filepath):
        print(f"[ERROR] '{filepath}' not found.")
        sys.exit(1)
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    mapping = {}
    for entry in data.values():
        name = entry.get(name_field, "").strip()
        eid  = entry.get(id_field,   "").strip()
        if name and eid:
            mapping[name] = int(eid)
    return mapping


def resolve(name, mapping, label, optional=False):
    """Resolve a name to its numeric ID. If optional and empty, return 255 (no ref)."""
    name = name.strip()
    if not name:
        if optional:
            return 255
        return 255   # empty slot → 0xFF sentinel
    if name not in mapping:
        print(f"[ERROR] '{name}' not found in {label}. Available: {list(mapping.keys())}")
        sys.exit(1)
    return mapping[name]


def ascii_lines(text):
    """
    Split text on real newline characters and return a list of .ascii directive strings.
    Each segment becomes its own .ascii line; a .ascii "\\n" line is inserted between
    segments so the newline character is preserved in the assembled output.
    Lines are wrapped at a maximum of 80 characters without cutting words in half.
    """
    segments = text.split("\n")
    out = []
    for seg in segments:
        while len(seg) > 80:
            # Find the last space at or before position 80
            cut = seg.rfind(" ", 0, 81)
            if cut <= 0:
                # No space found — force cut at 80 to avoid infinite loop
                cut = 80
            out.append(f'  .ascii "{seg[:cut]}"')
            seg = seg[cut:].lstrip(" ")
        out.append(f'  .ascii "{seg}"')
    return out


def to_asm(screens, action_ids):
    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Screens — auto-generated by acs_screens_to_asm.py")
    lines.append("; ============================================================")
    lines.append("")

    # ── Screen index table (pointer to the start of each screen record) ──────
    lines.append("screens_index:")
    for index, (key, scr) in enumerate(screens.items()):
        scr_id = scr.get("ID", str(index)).strip()
        name   = scr.get("Name", key)
        lines.append(f"  .word screen_pointers_{scr_id}  ; {name}")
    lines.append(f"screens_index_record_length:")
    lines.append(f"  .byte 2  ; each screens_index entry is 1 .word (2 bytes)")
    lines.append("")

    # ── Pointer table ────────────────────────────────────────
    lines.append("screens_pointers:")
    offset = 0
    screen_0_action1_byte        = None
    screen_0_description_byte    = None
    screen_0_ascii_byte          = None
    screen_0_flashlight_on_byte  = None
    screen_0_flashlight_off_byte = None
    screen_0_enemy_prob_byte     = None
    screen_0_is_secret_byte      = None
    screen_0_is_end_byte         = None
    screen_0_record_length       = None
    screen_0_name                = None
    for index, (key, scr) in enumerate(screens.items()):
        scr_id = scr.get("ID", str(index)).strip()
        label  = f"screen_{scr_id}"
        name   = scr.get("Name", key)

        start_offset  = offset

        lines.append(f"screen_pointers_{scr_id}:")
        lines.append(f"  .word {label}_id                ; {name} id                [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_name              ; {name} name              [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_action1           ; {name} action1           [{offset},{offset+1}]") ; _act1 = offset ; offset += 2
        lines.append(f"  .word {label}_action2           ; {name} action2           [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_action3           ; {name} action3           [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_action4           ; {name} action4           [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_description       ; {name} description       [{offset},{offset+1}]") ; _desc = offset ; offset += 2
        lines.append(f"  .word {label}_ascii             ; {name} ascii             [{offset},{offset+1}]") ; _asc  = offset ; offset += 2
        lines.append(f"  .word {label}_flashlight_on     ; {name} flashlight_on     [{offset},{offset+1}]") ; _flon = offset ; offset += 2
        lines.append(f"  .word {label}_flashlight_off    ; {name} flashlight_off    [{offset},{offset+1}]") ; _floff = offset ; offset += 2
        lines.append(f"  .word {label}_enemy_probability ; {name} enemy_probability [{offset},{offset+1}]") ; _enm = offset ; offset += 2
        lines.append(f"  .word {label}_is_secret_screen  ; {name} is_secret_screen  [{offset},{offset+1}]") ; _sec = offset ; offset += 2
        lines.append(f"  .word {label}_is_end_screen     ; {name} is_end_screen     [{offset},{offset+1}]") ; _end = offset ; offset += 2

        if index == 0:
            screen_0_action1_byte        = _act1
            screen_0_description_byte    = _desc
            screen_0_ascii_byte          = _asc
            screen_0_flashlight_on_byte  = _flon
            screen_0_flashlight_off_byte = _floff
            screen_0_enemy_prob_byte     = _enm
            screen_0_is_secret_byte      = _sec
            screen_0_is_end_byte         = _end
            screen_0_record_length       = offset - start_offset
            screen_0_name                = name

    # ── Extra fields for screen 0, placed after all screen entries ────────────
    lines.append(f"screen_action_offset:")
    lines.append(f"  .byte {screen_0_action1_byte}  ; (byte of screen_0_action1 in screens_pointers)")
    lines.append(f"screen_description_offset:")
    lines.append(f"  .byte {screen_0_description_byte}  ; (byte of screen_0_description in screens_pointers)")
    lines.append(f"screen_ascii_offset:")
    lines.append(f"  .byte {screen_0_ascii_byte}  ; (byte of screen_0_ascii in screens_pointers)")
    lines.append(f"screen_flashlight_on_offset:")
    lines.append(f"  .byte {screen_0_flashlight_on_byte}  ; (byte of screen_0_flashlight_on in screens_pointers)")
    lines.append(f"screen_flashlight_off_offset:")
    lines.append(f"  .byte {screen_0_flashlight_off_byte}  ; (byte of screen_0_flashlight_off in screens_pointers)")
    lines.append(f"screen_enemy_probability_offset:")
    lines.append(f"  .byte {screen_0_enemy_prob_byte}  ; (byte of screen_0_enemy_probability in screens_pointers)")
    lines.append(f"screen_is_secret_screen_offset:")
    lines.append(f"  .byte {screen_0_is_secret_byte}  ; (byte of screen_0_is_secret_screen in screens_pointers)")
    lines.append(f"screen_is_end_screen_offset:")
    lines.append(f"  .byte {screen_0_is_end_byte}  ; (byte of screen_0_is_end_screen in screens_pointers)")
    lines.append(f"screen_record_length:")
    lines.append(f"  .byte {screen_0_record_length}  ; (total .word bytes per screen record)")
    lines.append("")

    for index, (key, scr) in enumerate(screens.items()):
        scr_id    = scr.get("ID",          str(index)).strip()
        label     = f"screen_{scr_id}"
        name_str  = scr.get("Name",        "").replace('"', '\\"')
        desc_str  = scr.get("Description", "").replace('"', '\\"')
        ascii_str = scr.get("AsciiDrawing","").replace('"', '\\"')

        # actions → numeric IDs (255 = empty slot)
        act_ids = [
            resolve(scr.get(f"Action{i}", ""), action_ids, ACTIONS_FILE, optional=True)
            for i in range(1, 5)
        ]

        lines.append(f"; ── Screen {scr_id}: {scr.get('Name', key)} ──────────────────────────")

        # ID
        lines.append(f"{label}_id:")
        lines.append(f"  .byte {scr_id}")
        lines.append("")

        # Name
        lines.append(f"{label}_name:")
        lines.extend(ascii_lines(name_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # Actions → numeric IDs
        for i, aid in enumerate(act_ids, 1):
            act_name = scr.get(f"Action{i}", "") or "none"
            lines.append(f"{label}_action{i}:")
            lines.append(f"  .byte {aid}  ; {act_name}")
            lines.append("")

        # Description
        lines.append(f"{label}_description:")
        lines.extend(ascii_lines(desc_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # AsciiDrawing
        lines.append(f"{label}_ascii:")
        lines.extend(ascii_lines(ascii_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # FlashlightOn
        flashlight_on_str  = scr.get("FlashlightOn",  "").replace('"', '\\"')
        lines.append(f"{label}_flashlight_on:")
        lines.extend(ascii_lines(flashlight_on_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # FlashlightOff
        flashlight_off_str = scr.get("FlashlightOff", "").replace('"', '\\"')
        lines.append(f"{label}_flashlight_off:")
        lines.extend(ascii_lines(flashlight_off_str))
        lines.append('  .ascii "e"')
        lines.append("")

        # Enemy Probability
        try:
            enemy_prob_val = int(scr.get("EnemyProbability", 0))
            enemy_prob_val = max(0, min(255, enemy_prob_val))
        except (ValueError, TypeError):
            enemy_prob_val = 0
        lines.append(f"{label}_enemy_probability:")
        lines.append(f"  .byte {enemy_prob_val}")
        lines.append("")

        # IsSecretScreen
        try:
            is_secret_val = int(scr.get("IsSecretScreen", 0))
            is_secret_val = 1 if is_secret_val else 0
        except (ValueError, TypeError):
            is_secret_val = 0
        lines.append(f"{label}_is_secret_screen:")
        lines.append(f"  .byte {is_secret_val}  ; {'yes' if is_secret_val else 'no'}")
        lines.append("")

        # IsEndScreen
        try:
            is_end_val = int(scr.get("IsEndScreen", 0))
            is_end_val = 1 if is_end_val else 0
        except (ValueError, TypeError):
            is_end_val = 0
        lines.append(f"{label}_is_end_screen:")
        lines.append(f"  .byte {is_end_val}  ; {'yes' if is_end_val else 'no'}")
        lines.append("")

    # ── Screen count constant ─────────────────────────────────
    lines.append("; ── Total screen count ──────────────────────────────────────")
    lines.append("screen_count:")
    lines.append(f"  .byte {len(screens)}")
    lines.append("")

    # ── Secret screens count ──────────────────────────────────
    secret_count = 0
    for scr in screens.values():
        try:
            if int(scr.get("IsSecretScreen", 0)):
                secret_count += 1
        except (ValueError, TypeError):
            pass
    lines.append("; ── Total secret screens count ──────────────────────────────")
    lines.append("screens_with_secrets:")
    lines.append(f"  .byte {secret_count}")
    lines.append("")

    return "\n".join(lines)


def main():
    # ── Load lookup tables ────────────────────────────────────
    action_ids = load_name_to_id(ACTIONS_FILE, id_field="ID", name_field="Name")

    # ── Load screens ──────────────────────────────────────────
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found. Run the ACS editor first.")
        return

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        screens = json.load(f)

    if not screens:
        print("[WARNING] No screens found in the JSON file.")
        return

    screens = dict(sorted(screens.items(), key=lambda item: int(item[1].get("ID", 0))))

    asm = to_asm(screens, action_ids)

    with open(ASM_FILE, "w", encoding="utf-8") as f:
        f.write(asm)

    print(f"[OK] Generated '{ASM_FILE}' with {len(screens)} screen(s).")
    print("-" * 50)
    print(asm)


if __name__ == "__main__":
    main()