import json
import os
import sys
sys.stdout.reconfigure(encoding='utf-8')

JSON_FILE = "acs_dashboard.json"
ASM_FILE  = "acs_dashboard.asm"


def to_asm(dashboards):
    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Dashboard — auto-generated by acs_parser_dashboard.py")
    lines.append("; ============================================================")
    lines.append("")

    # ── Dashboard index table (pointer to the start of each record) ───────
    lines.append("dashboard_index:")
    for index, (key, rec) in enumerate(dashboards.items()):
        rec_id = rec.get("ID", str(index)).strip()
        name   = rec.get("Name", key)
        lines.append(f"  .word dashboard_pointer_{rec_id}  ; {name}")
    lines.append("dashboard_index_record_length:")
    lines.append("  .byte 2  ; each dashboard_index entry is 1 .word (2 bytes)")
    lines.append("")

    # ── Pointer table ─────────────────────────────────────────────────────
    lines.append("dashboard_pointers:")
    offset = 0

    rec0_name_offset        = None
    rec0_start_screen_offset = None
    rec0_high_water_offset  = None
    rec0_high_heart_offset  = None
    rec0_total_sim_offset   = None
    rec0_total_flash_offset = None
    rec0_water_offsets       = {}
    rec0_extra_water_offset = None
    rec0_extra_heart_offset = None
    rec0_extra_flash_offset = None
    rec0_death_water_offset = None
    rec0_death_heart_offset = None
    rec0_death_flash_offset = None
    rec0_enemy_flash_on_offset = None
    rec0_end_screen_default_offset = None
    rec0_end_screen_enemy_offset   = None
    rec0_end_screen_timeup_offset  = None
    rec0_end_screen_enemy_af_offset = None
    rec0_record_length      = None

    for index, (key, rec) in enumerate(dashboards.items()):
        rec_id = rec.get("ID", str(index)).strip()
        label  = f"dashboard_{rec_id}"
        name   = rec.get("Name", key)

        start_offset = offset

        lines.append(f"dashboard_pointer_{rec_id}:")
        lines.append(f"  .word {label}_id               ; {name} id               [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_name             ; {name} name             [{offset},{offset+1}]") ; _nam = offset ; offset += 2
        lines.append(f"  .word {label}_start_screen     ; {name} start_screen     [{offset},{offset+1}]") ; _ss = offset ; offset += 2
        lines.append(f"  .word {label}_high_water_level ; {name} high_water_level [{offset},{offset+1}]") ; _hw = offset ; offset += 2
        lines.append(f"  .word {label}_high_heart_level ; {name} high_heart_level [{offset},{offset+1}]") ; _hh = offset ; offset += 2
        lines.append(f"  .word {label}_total_sim_time   ; {name} total_sim_time   [{offset},{offset+1}]") ; _tst = offset ; offset += 2
        lines.append(f"  .word {label}_total_flash_time ; {name} total_flash_time [{offset},{offset+1}]") ; _tft = offset ; offset += 2
        _water_offsets = {}
        for _wi in range(10):
            lines.append(f"  .word {label}_water_level{_wi}     ; {name} water_level{_wi}     [{offset},{offset+1}]") ; _water_offsets[_wi] = offset ; offset += 2
        lines.append(f"  .word {label}_extra_water      ; {name} extra_water      [{offset},{offset+1}]") ; _ew = offset ; offset += 2
        lines.append(f"  .word {label}_extra_heartrate  ; {name} extra_heartrate  [{offset},{offset+1}]") ; _eh = offset ; offset += 2
        lines.append(f"  .word {label}_extra_flashlight ; {name} extra_flashlight [{offset},{offset+1}]") ; _ef = offset ; offset += 2
        lines.append(f"  .word {label}_death_water      ; {name} death_water      [{offset},{offset+1}]") ; _dw = offset ; offset += 2
        lines.append(f"  .word {label}_death_heartrate  ; {name} death_heartrate  [{offset},{offset+1}]") ; _dh = offset ; offset += 2
        lines.append(f"  .word {label}_death_flashlight ; {name} death_flashlight [{offset},{offset+1}]") ; _df = offset ; offset += 2
        lines.append(f"  .word {label}_enemy_flash_on   ; {name} enemy_flash_on   [{offset},{offset+1}]") ; _efo = offset ; offset += 2
        lines.append(f"  .word {label}_end_screen_default ; {name} end_screen_default [{offset},{offset+1}]") ; _esd = offset ; offset += 2
        lines.append(f"  .word {label}_end_screen_enemy  ; {name} end_screen_enemy  [{offset},{offset+1}]") ; _ese = offset ; offset += 2
        lines.append(f"  .word {label}_end_screen_timeup ; {name} end_screen_timeup [{offset},{offset+1}]") ; _est = offset ; offset += 2
        lines.append(f"  .word {label}_end_screen_enemy_af ; {name} end_screen_enemy_af [{offset},{offset+1}]") ; _esaf = offset ; offset += 2

        if index == 0:
            rec0_name_offset        = _nam
            rec0_start_screen_offset = _ss
            rec0_high_water_offset  = _hw
            rec0_high_heart_offset  = _hh
            rec0_total_sim_offset   = _tst
            rec0_total_flash_offset = _tft
            rec0_water_offsets      = dict(_water_offsets)
            rec0_extra_water_offset = _ew
            rec0_extra_heart_offset = _eh
            rec0_extra_flash_offset = _ef
            rec0_death_water_offset = _dw
            rec0_death_heart_offset = _dh
            rec0_death_flash_offset = _df
            rec0_enemy_flash_on_offset = _efo
            rec0_end_screen_default_offset = _esd
            rec0_end_screen_enemy_offset   = _ese
            rec0_end_screen_timeup_offset  = _est
            rec0_end_screen_enemy_af_offset = _esaf
            rec0_record_length      = offset - start_offset

    # ── Offset labels ─────────────────────────────────────────────────────
    lines.append(f"dashboard_name_offset:")
    lines.append(f"  .byte {rec0_name_offset}  ; (byte of dashboard_0_name in pointers)")
    lines.append(f"dashboard_start_screen_offset:")
    lines.append(f"  .byte {rec0_start_screen_offset}  ; (byte of dashboard_0_start_screen in pointers)")
    lines.append(f"dashboard_high_water_level_offset:")
    lines.append(f"  .byte {rec0_high_water_offset}  ; (byte of dashboard_0_high_water_level in pointers)")
    lines.append(f"dashboard_high_heart_level_offset:")
    lines.append(f"  .byte {rec0_high_heart_offset}  ; (byte of dashboard_0_high_heart_level in pointers)")
    lines.append(f"dashboard_total_sim_time_offset:")
    lines.append(f"  .byte {rec0_total_sim_offset}  ; (byte of dashboard_0_total_sim_time in pointers)")
    lines.append(f"dashboard_total_flash_time_offset:")
    lines.append(f"  .byte {rec0_total_flash_offset}  ; (byte of dashboard_0_total_flash_time in pointers)")
    for _wi in range(10):
        lines.append(f"dashboard_water_level{_wi}_offset:")
        lines.append(f"  .byte {rec0_water_offsets[_wi]}  ; (byte of dashboard_0_water_level{_wi} in pointers)")
    lines.append(f"dashboard_extra_water_offset:")
    lines.append(f"  .byte {rec0_extra_water_offset}  ; (byte of dashboard_0_extra_water in pointers)")
    lines.append(f"dashboard_extra_heartrate_offset:")
    lines.append(f"  .byte {rec0_extra_heart_offset}  ; (byte of dashboard_0_extra_heartrate in pointers)")
    lines.append(f"dashboard_extra_flashlight_offset:")
    lines.append(f"  .byte {rec0_extra_flash_offset}  ; (byte of dashboard_0_extra_flashlight in pointers)")
    lines.append(f"dashboard_death_water_offset:")
    lines.append(f"  .byte {rec0_death_water_offset}  ; (byte of dashboard_0_death_water in pointers)")
    lines.append(f"dashboard_death_heartrate_offset:")
    lines.append(f"  .byte {rec0_death_heart_offset}  ; (byte of dashboard_0_death_heartrate in pointers)")
    lines.append(f"dashboard_death_flashlight_offset:")
    lines.append(f"  .byte {rec0_death_flash_offset}  ; (byte of dashboard_0_death_flashlight in pointers)")
    lines.append(f"dashboard_enemy_flash_on_offset:")
    lines.append(f"  .byte {rec0_enemy_flash_on_offset}  ; (byte of dashboard_0_enemy_flash_on in pointers)")
    lines.append(f"dashboard_end_screen_default_offset:")
    lines.append(f"  .byte {rec0_end_screen_default_offset}  ; (byte of dashboard_0_end_screen_default in pointers)")
    lines.append(f"dashboard_end_screen_enemy_offset:")
    lines.append(f"  .byte {rec0_end_screen_enemy_offset}  ; (byte of dashboard_0_end_screen_enemy in pointers)")
    lines.append(f"dashboard_end_screen_timeup_offset:")
    lines.append(f"  .byte {rec0_end_screen_timeup_offset}  ; (byte of dashboard_0_end_screen_timeup in pointers)")
    lines.append(f"dashboard_end_screen_enemy_af_offset:")
    lines.append(f"  .byte {rec0_end_screen_enemy_af_offset}  ; (byte of dashboard_0_end_screen_enemy_af in pointers)")
    lines.append(f"dashboard_record_length:")
    lines.append(f"  .byte {rec0_record_length}  ; (total .word bytes per record)")
    lines.append("")

    # ── Per-record data blocks ────────────────────────────────────────────
    for index, (key, rec) in enumerate(dashboards.items()):
        rec_id   = rec.get("ID",   str(index)).strip()
        label    = f"dashboard_{rec_id}"
        name_str = rec.get("Name", "").replace('"', '\\"')

        lines.append(f"; ── Dashboard {rec_id}: {rec.get('Name', key)} ──────────────────────────")

        # ID
        lines.append(f"{label}_id:")
        lines.append(f"  .byte {rec_id}")
        lines.append("")

        # Name
        lines.append(f"{label}_name:")
        lines.append(f'  .ascii "{name_str}"')
        lines.append('  .ascii "e"')
        lines.append("")

        # Start Screen ID
        try:
            start_scr_val = int(rec.get("StartScreenID", 255))
        except (ValueError, TypeError):
            start_scr_val = 255
        if start_scr_val < 0 or start_scr_val > 254:
            start_scr_val = 255
        lines.append(f"{label}_start_screen:")
        lines.append(f"  .byte {start_scr_val}  ; start screen id")
        lines.append("")

        # High Water Level (0-3)
        try:
            hw_val = int(rec.get("HighWaterLevel", 5))
            hw_val = max(0, min(9, hw_val))
        except (ValueError, TypeError):
            hw_val = 2
        lines.append(f"{label}_high_water_level:")
        lines.append(f"  .byte {hw_val}")
        lines.append("")

        # High HeartRate Level (0-1)
        try:
            hh_val = int(rec.get("HighHeartRateLevel", 1))
            hh_val = max(0, min(1, hh_val))
        except (ValueError, TypeError):
            hh_val = 1
        lines.append(f"{label}_high_heart_level:")
        lines.append(f"  .byte {hh_val}")
        lines.append("")

        # Total Simulation Time (stored as 2-byte hex, high byte first)
        try:
            tsim_val = int(rec.get("TotalSimulationTime", 0))
            tsim_val = max(0, min(1023, tsim_val))
        except (ValueError, TypeError):
            tsim_val = 0
        hi = (tsim_val >> 8) & 0xFF
        lo = tsim_val & 0xFF
        lines.append(f"{label}_total_sim_time:")
        lines.append(f"  .byte ${hi:02X}  ; high byte  (decimal {tsim_val})")
        lines.append(f"  .byte ${lo:02X}  ; low byte")
        lines.append("")

        # Total Flashlight Time (stored as 2-byte hex, high byte first)
        try:
            tflash_val = int(rec.get("TotalFlashlightTime", 0))
            tflash_val = max(0, min(1023, tflash_val))
        except (ValueError, TypeError):
            tflash_val = 0
        hi = (tflash_val >> 8) & 0xFF
        lo = tflash_val & 0xFF
        lines.append(f"{label}_total_flash_time:")
        lines.append(f"  .byte ${hi:02X}  ; high byte  (decimal {tflash_val})")
        lines.append(f"  .byte ${lo:02X}  ; low byte")
        lines.append("")

        # Water Levels 0–9 (stored as 2-byte hex, high byte first)
        for i in range(10):
            wl_key = f"WaterLevel{i}"
            try:
                wl_val = int(rec.get(wl_key, 0))
                wl_val = max(0, min(1023, wl_val))
            except (ValueError, TypeError):
                wl_val = 0
            hi = (wl_val >> 8) & 0xFF
            lo = wl_val & 0xFF
            lines.append(f"{label}_water_level{i}:")
            lines.append(f"  .byte ${hi:02X}  ; high byte  (decimal {wl_val})")
            lines.append(f"  .byte ${lo:02X}  ; low byte")
            lines.append("")

        # Extra Seconds fields (stored as 2-byte hex, high byte first)
        for field_key, asm_label in [
            ("ExtraSecondsWaterLevel",   "extra_water"),
            ("ExtraSecondsHighHeartRate", "extra_heartrate"),
            ("ExtraSecondsFlashlightOff", "extra_flashlight"),
        ]:
            try:
                ex_val = int(rec.get(field_key, 0))
                ex_val = max(0, min(1023, ex_val))
            except (ValueError, TypeError):
                ex_val = 0
            hi = (ex_val >> 8) & 0xFF
            lo = ex_val & 0xFF
            lines.append(f"{label}_{asm_label}:")
            lines.append(f"  .byte ${hi:02X}  ; high byte  (decimal {ex_val})")
            lines.append(f"  .byte ${lo:02X}  ; low byte")
            lines.append("")

        # Death Probability fields (0–255, stored as single byte)
        for field_key, asm_label in [
            ("DeathProbWaterLevel",    "death_water"),
            ("DeathProbHighHeartRate", "death_heartrate"),
            ("DeathProbFlashlightOff", "death_flashlight"),
        ]:
            try:
                dp_val = int(rec.get(field_key, 0))
                dp_val = max(0, min(255, dp_val))
            except (ValueError, TypeError):
                dp_val = 0
            lines.append(f"{label}_{asm_label}:")
            lines.append(f"  .byte {dp_val}")
            lines.append("")

        # Enemy Probability fields (0–255, stored as single byte)
        for field_key, asm_label in [
            ("EnemyProbFlashlightOn", "enemy_flash_on"),
        ]:
            try:
                ep_val = int(rec.get(field_key, 0))
                ep_val = max(0, min(255, ep_val))
            except (ValueError, TypeError):
                ep_val = 0
            lines.append(f"{label}_{asm_label}:")
            lines.append(f"  .byte {ep_val}")
            lines.append("")

        # End Screen fields (stored as single byte, screen ID 0–254, 255 = none)
        for field_key, asm_label in [
            ("EndScreenDefaultID", "end_screen_default"),
            ("EndScreenEnemyID",   "end_screen_enemy"),
            ("EndScreenTimeUpID",  "end_screen_timeup"),
            ("EndScreenEnemyActionFailedID", "end_screen_enemy_af"),
        ]:
            try:
                es_val = int(rec.get(field_key, 255))
            except (ValueError, TypeError):
                es_val = 255
            if es_val < 0 or es_val > 254:
                es_val = 255
            lines.append(f"{label}_{asm_label}:")
            lines.append(f"  .byte {es_val}  ; screen id")
            lines.append("")

    # ── Record count constant ─────────────────────────────────────────────
    lines.append("; ── Total dashboard count ──────────────────────────────────────")
    lines.append("dashboard_count:")
    lines.append(f"  .byte {len(dashboards)}")
    lines.append("")

    return "\n".join(lines)


def main():
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found. Run the ACS editor first.")
        return

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        dashboards = json.load(f)

    if not dashboards:
        print("[WARNING] No dashboard records found in the JSON file.")
        return

    dashboards = dict(sorted(dashboards.items(), key=lambda item: int(item[1].get("ID", 0))))

    asm = to_asm(dashboards)

    with open(ASM_FILE, "w", encoding="utf-8") as f:
        f.write(asm)

    print(f"[OK] Generated '{ASM_FILE}' with {len(dashboards)} record(s).")
    print("-" * 50)
    print(asm)


if __name__ == "__main__":
    main()
