; ============================================================
;  ACS Screens — auto-generated by acs_screens_to_asm.py
; ============================================================

screens_index:
  .word screen_pointers_0  ; StartScreen
  .word screen_pointers_1  ; S01P01
  .word screen_pointers_2  ; S01P02
  .word screen_pointers_3  ; S01P03
  .word screen_pointers_4  ; S01P04
  .word screen_pointers_5  ; S01P05
  .word screen_pointers_6  ; S01P06
  .word screen_pointers_7  ; S01P07
  .word screen_pointers_8  ; S02P01
  .word screen_pointers_9  ; S02P02
  .word screen_pointers_10  ; S02P03
  .word screen_pointers_11  ; S02P04
  .word screen_pointers_12  ; S02P05
  .word screen_pointers_13  ; S02P06
  .word screen_pointers_14  ; S02P07
  .word screen_pointers_15  ; S03P01
  .word screen_pointers_16  ; S03P02
  .word screen_pointers_17  ; S03P03
  .word screen_pointers_18  ; S03P04
  .word screen_pointers_19  ; S03P05
  .word screen_pointers_20  ; S03P06
  .word screen_pointers_21  ; S03P07
  .word screen_pointers_22  ; S03P08
  .word screen_pointers_23  ; S03P09
  .word screen_pointers_24  ; S04P01
  .word screen_pointers_25  ; S04P02
  .word screen_pointers_26  ; S04P03
  .word screen_pointers_27  ; S04P04
  .word screen_pointers_28  ; S04P05
  .word screen_pointers_29  ; FINAL
  .word screen_pointers_30  ; EndScreenSimulationTimeisUp
  .word screen_pointers_31  ; endScreenByEnemy
  .word screen_pointers_32  ; endScreenByActionFailed
screens_index_record_length:
  .byte 2  ; each screens_index entry is 1 .word (2 bytes)

screens_pointers:
screen_pointers_0:
  .word screen_0_id                ; StartScreen id                [0,1]
  .word screen_0_name              ; StartScreen name              [2,3]
  .word screen_0_action1           ; StartScreen action1           [4,5]
  .word screen_0_action2           ; StartScreen action2           [6,7]
  .word screen_0_action3           ; StartScreen action3           [8,9]
  .word screen_0_action4           ; StartScreen action4           [10,11]
  .word screen_0_description       ; StartScreen description       [12,13]
  .word screen_0_ascii             ; StartScreen ascii             [14,15]
  .word screen_0_flashlight_on     ; StartScreen flashlight_on     [16,17]
  .word screen_0_flashlight_off    ; StartScreen flashlight_off    [18,19]
  .word screen_0_enemy_probability ; StartScreen enemy_probability [20,21]
  .word screen_0_is_secret_screen  ; StartScreen is_secret_screen  [22,23]
  .word screen_0_is_end_screen     ; StartScreen is_end_screen     [24,25]
screen_pointers_1:
  .word screen_1_id                ; S01P01 id                [26,27]
  .word screen_1_name              ; S01P01 name              [28,29]
  .word screen_1_action1           ; S01P01 action1           [30,31]
  .word screen_1_action2           ; S01P01 action2           [32,33]
  .word screen_1_action3           ; S01P01 action3           [34,35]
  .word screen_1_action4           ; S01P01 action4           [36,37]
  .word screen_1_description       ; S01P01 description       [38,39]
  .word screen_1_ascii             ; S01P01 ascii             [40,41]
  .word screen_1_flashlight_on     ; S01P01 flashlight_on     [42,43]
  .word screen_1_flashlight_off    ; S01P01 flashlight_off    [44,45]
  .word screen_1_enemy_probability ; S01P01 enemy_probability [46,47]
  .word screen_1_is_secret_screen  ; S01P01 is_secret_screen  [48,49]
  .word screen_1_is_end_screen     ; S01P01 is_end_screen     [50,51]
screen_pointers_2:
  .word screen_2_id                ; S01P02 id                [52,53]
  .word screen_2_name              ; S01P02 name              [54,55]
  .word screen_2_action1           ; S01P02 action1           [56,57]
  .word screen_2_action2           ; S01P02 action2           [58,59]
  .word screen_2_action3           ; S01P02 action3           [60,61]
  .word screen_2_action4           ; S01P02 action4           [62,63]
  .word screen_2_description       ; S01P02 description       [64,65]
  .word screen_2_ascii             ; S01P02 ascii             [66,67]
  .word screen_2_flashlight_on     ; S01P02 flashlight_on     [68,69]
  .word screen_2_flashlight_off    ; S01P02 flashlight_off    [70,71]
  .word screen_2_enemy_probability ; S01P02 enemy_probability [72,73]
  .word screen_2_is_secret_screen  ; S01P02 is_secret_screen  [74,75]
  .word screen_2_is_end_screen     ; S01P02 is_end_screen     [76,77]
screen_pointers_3:
  .word screen_3_id                ; S01P03 id                [78,79]
  .word screen_3_name              ; S01P03 name              [80,81]
  .word screen_3_action1           ; S01P03 action1           [82,83]
  .word screen_3_action2           ; S01P03 action2           [84,85]
  .word screen_3_action3           ; S01P03 action3           [86,87]
  .word screen_3_action4           ; S01P03 action4           [88,89]
  .word screen_3_description       ; S01P03 description       [90,91]
  .word screen_3_ascii             ; S01P03 ascii             [92,93]
  .word screen_3_flashlight_on     ; S01P03 flashlight_on     [94,95]
  .word screen_3_flashlight_off    ; S01P03 flashlight_off    [96,97]
  .word screen_3_enemy_probability ; S01P03 enemy_probability [98,99]
  .word screen_3_is_secret_screen  ; S01P03 is_secret_screen  [100,101]
  .word screen_3_is_end_screen     ; S01P03 is_end_screen     [102,103]
screen_pointers_4:
  .word screen_4_id                ; S01P04 id                [104,105]
  .word screen_4_name              ; S01P04 name              [106,107]
  .word screen_4_action1           ; S01P04 action1           [108,109]
  .word screen_4_action2           ; S01P04 action2           [110,111]
  .word screen_4_action3           ; S01P04 action3           [112,113]
  .word screen_4_action4           ; S01P04 action4           [114,115]
  .word screen_4_description       ; S01P04 description       [116,117]
  .word screen_4_ascii             ; S01P04 ascii             [118,119]
  .word screen_4_flashlight_on     ; S01P04 flashlight_on     [120,121]
  .word screen_4_flashlight_off    ; S01P04 flashlight_off    [122,123]
  .word screen_4_enemy_probability ; S01P04 enemy_probability [124,125]
  .word screen_4_is_secret_screen  ; S01P04 is_secret_screen  [126,127]
  .word screen_4_is_end_screen     ; S01P04 is_end_screen     [128,129]
screen_pointers_5:
  .word screen_5_id                ; S01P05 id                [130,131]
  .word screen_5_name              ; S01P05 name              [132,133]
  .word screen_5_action1           ; S01P05 action1           [134,135]
  .word screen_5_action2           ; S01P05 action2           [136,137]
  .word screen_5_action3           ; S01P05 action3           [138,139]
  .word screen_5_action4           ; S01P05 action4           [140,141]
  .word screen_5_description       ; S01P05 description       [142,143]
  .word screen_5_ascii             ; S01P05 ascii             [144,145]
  .word screen_5_flashlight_on     ; S01P05 flashlight_on     [146,147]
  .word screen_5_flashlight_off    ; S01P05 flashlight_off    [148,149]
  .word screen_5_enemy_probability ; S01P05 enemy_probability [150,151]
  .word screen_5_is_secret_screen  ; S01P05 is_secret_screen  [152,153]
  .word screen_5_is_end_screen     ; S01P05 is_end_screen     [154,155]
screen_pointers_6:
  .word screen_6_id                ; S01P06 id                [156,157]
  .word screen_6_name              ; S01P06 name              [158,159]
  .word screen_6_action1           ; S01P06 action1           [160,161]
  .word screen_6_action2           ; S01P06 action2           [162,163]
  .word screen_6_action3           ; S01P06 action3           [164,165]
  .word screen_6_action4           ; S01P06 action4           [166,167]
  .word screen_6_description       ; S01P06 description       [168,169]
  .word screen_6_ascii             ; S01P06 ascii             [170,171]
  .word screen_6_flashlight_on     ; S01P06 flashlight_on     [172,173]
  .word screen_6_flashlight_off    ; S01P06 flashlight_off    [174,175]
  .word screen_6_enemy_probability ; S01P06 enemy_probability [176,177]
  .word screen_6_is_secret_screen  ; S01P06 is_secret_screen  [178,179]
  .word screen_6_is_end_screen     ; S01P06 is_end_screen     [180,181]
screen_pointers_7:
  .word screen_7_id                ; S01P07 id                [182,183]
  .word screen_7_name              ; S01P07 name              [184,185]
  .word screen_7_action1           ; S01P07 action1           [186,187]
  .word screen_7_action2           ; S01P07 action2           [188,189]
  .word screen_7_action3           ; S01P07 action3           [190,191]
  .word screen_7_action4           ; S01P07 action4           [192,193]
  .word screen_7_description       ; S01P07 description       [194,195]
  .word screen_7_ascii             ; S01P07 ascii             [196,197]
  .word screen_7_flashlight_on     ; S01P07 flashlight_on     [198,199]
  .word screen_7_flashlight_off    ; S01P07 flashlight_off    [200,201]
  .word screen_7_enemy_probability ; S01P07 enemy_probability [202,203]
  .word screen_7_is_secret_screen  ; S01P07 is_secret_screen  [204,205]
  .word screen_7_is_end_screen     ; S01P07 is_end_screen     [206,207]
screen_pointers_8:
  .word screen_8_id                ; S02P01 id                [208,209]
  .word screen_8_name              ; S02P01 name              [210,211]
  .word screen_8_action1           ; S02P01 action1           [212,213]
  .word screen_8_action2           ; S02P01 action2           [214,215]
  .word screen_8_action3           ; S02P01 action3           [216,217]
  .word screen_8_action4           ; S02P01 action4           [218,219]
  .word screen_8_description       ; S02P01 description       [220,221]
  .word screen_8_ascii             ; S02P01 ascii             [222,223]
  .word screen_8_flashlight_on     ; S02P01 flashlight_on     [224,225]
  .word screen_8_flashlight_off    ; S02P01 flashlight_off    [226,227]
  .word screen_8_enemy_probability ; S02P01 enemy_probability [228,229]
  .word screen_8_is_secret_screen  ; S02P01 is_secret_screen  [230,231]
  .word screen_8_is_end_screen     ; S02P01 is_end_screen     [232,233]
screen_pointers_9:
  .word screen_9_id                ; S02P02 id                [234,235]
  .word screen_9_name              ; S02P02 name              [236,237]
  .word screen_9_action1           ; S02P02 action1           [238,239]
  .word screen_9_action2           ; S02P02 action2           [240,241]
  .word screen_9_action3           ; S02P02 action3           [242,243]
  .word screen_9_action4           ; S02P02 action4           [244,245]
  .word screen_9_description       ; S02P02 description       [246,247]
  .word screen_9_ascii             ; S02P02 ascii             [248,249]
  .word screen_9_flashlight_on     ; S02P02 flashlight_on     [250,251]
  .word screen_9_flashlight_off    ; S02P02 flashlight_off    [252,253]
  .word screen_9_enemy_probability ; S02P02 enemy_probability [254,255]
  .word screen_9_is_secret_screen  ; S02P02 is_secret_screen  [256,257]
  .word screen_9_is_end_screen     ; S02P02 is_end_screen     [258,259]
screen_pointers_10:
  .word screen_10_id                ; S02P03 id                [260,261]
  .word screen_10_name              ; S02P03 name              [262,263]
  .word screen_10_action1           ; S02P03 action1           [264,265]
  .word screen_10_action2           ; S02P03 action2           [266,267]
  .word screen_10_action3           ; S02P03 action3           [268,269]
  .word screen_10_action4           ; S02P03 action4           [270,271]
  .word screen_10_description       ; S02P03 description       [272,273]
  .word screen_10_ascii             ; S02P03 ascii             [274,275]
  .word screen_10_flashlight_on     ; S02P03 flashlight_on     [276,277]
  .word screen_10_flashlight_off    ; S02P03 flashlight_off    [278,279]
  .word screen_10_enemy_probability ; S02P03 enemy_probability [280,281]
  .word screen_10_is_secret_screen  ; S02P03 is_secret_screen  [282,283]
  .word screen_10_is_end_screen     ; S02P03 is_end_screen     [284,285]
screen_pointers_11:
  .word screen_11_id                ; S02P04 id                [286,287]
  .word screen_11_name              ; S02P04 name              [288,289]
  .word screen_11_action1           ; S02P04 action1           [290,291]
  .word screen_11_action2           ; S02P04 action2           [292,293]
  .word screen_11_action3           ; S02P04 action3           [294,295]
  .word screen_11_action4           ; S02P04 action4           [296,297]
  .word screen_11_description       ; S02P04 description       [298,299]
  .word screen_11_ascii             ; S02P04 ascii             [300,301]
  .word screen_11_flashlight_on     ; S02P04 flashlight_on     [302,303]
  .word screen_11_flashlight_off    ; S02P04 flashlight_off    [304,305]
  .word screen_11_enemy_probability ; S02P04 enemy_probability [306,307]
  .word screen_11_is_secret_screen  ; S02P04 is_secret_screen  [308,309]
  .word screen_11_is_end_screen     ; S02P04 is_end_screen     [310,311]
screen_pointers_12:
  .word screen_12_id                ; S02P05 id                [312,313]
  .word screen_12_name              ; S02P05 name              [314,315]
  .word screen_12_action1           ; S02P05 action1           [316,317]
  .word screen_12_action2           ; S02P05 action2           [318,319]
  .word screen_12_action3           ; S02P05 action3           [320,321]
  .word screen_12_action4           ; S02P05 action4           [322,323]
  .word screen_12_description       ; S02P05 description       [324,325]
  .word screen_12_ascii             ; S02P05 ascii             [326,327]
  .word screen_12_flashlight_on     ; S02P05 flashlight_on     [328,329]
  .word screen_12_flashlight_off    ; S02P05 flashlight_off    [330,331]
  .word screen_12_enemy_probability ; S02P05 enemy_probability [332,333]
  .word screen_12_is_secret_screen  ; S02P05 is_secret_screen  [334,335]
  .word screen_12_is_end_screen     ; S02P05 is_end_screen     [336,337]
screen_pointers_13:
  .word screen_13_id                ; S02P06 id                [338,339]
  .word screen_13_name              ; S02P06 name              [340,341]
  .word screen_13_action1           ; S02P06 action1           [342,343]
  .word screen_13_action2           ; S02P06 action2           [344,345]
  .word screen_13_action3           ; S02P06 action3           [346,347]
  .word screen_13_action4           ; S02P06 action4           [348,349]
  .word screen_13_description       ; S02P06 description       [350,351]
  .word screen_13_ascii             ; S02P06 ascii             [352,353]
  .word screen_13_flashlight_on     ; S02P06 flashlight_on     [354,355]
  .word screen_13_flashlight_off    ; S02P06 flashlight_off    [356,357]
  .word screen_13_enemy_probability ; S02P06 enemy_probability [358,359]
  .word screen_13_is_secret_screen  ; S02P06 is_secret_screen  [360,361]
  .word screen_13_is_end_screen     ; S02P06 is_end_screen     [362,363]
screen_pointers_14:
  .word screen_14_id                ; S02P07 id                [364,365]
  .word screen_14_name              ; S02P07 name              [366,367]
  .word screen_14_action1           ; S02P07 action1           [368,369]
  .word screen_14_action2           ; S02P07 action2           [370,371]
  .word screen_14_action3           ; S02P07 action3           [372,373]
  .word screen_14_action4           ; S02P07 action4           [374,375]
  .word screen_14_description       ; S02P07 description       [376,377]
  .word screen_14_ascii             ; S02P07 ascii             [378,379]
  .word screen_14_flashlight_on     ; S02P07 flashlight_on     [380,381]
  .word screen_14_flashlight_off    ; S02P07 flashlight_off    [382,383]
  .word screen_14_enemy_probability ; S02P07 enemy_probability [384,385]
  .word screen_14_is_secret_screen  ; S02P07 is_secret_screen  [386,387]
  .word screen_14_is_end_screen     ; S02P07 is_end_screen     [388,389]
screen_pointers_15:
  .word screen_15_id                ; S03P01 id                [390,391]
  .word screen_15_name              ; S03P01 name              [392,393]
  .word screen_15_action1           ; S03P01 action1           [394,395]
  .word screen_15_action2           ; S03P01 action2           [396,397]
  .word screen_15_action3           ; S03P01 action3           [398,399]
  .word screen_15_action4           ; S03P01 action4           [400,401]
  .word screen_15_description       ; S03P01 description       [402,403]
  .word screen_15_ascii             ; S03P01 ascii             [404,405]
  .word screen_15_flashlight_on     ; S03P01 flashlight_on     [406,407]
  .word screen_15_flashlight_off    ; S03P01 flashlight_off    [408,409]
  .word screen_15_enemy_probability ; S03P01 enemy_probability [410,411]
  .word screen_15_is_secret_screen  ; S03P01 is_secret_screen  [412,413]
  .word screen_15_is_end_screen     ; S03P01 is_end_screen     [414,415]
screen_pointers_16:
  .word screen_16_id                ; S03P02 id                [416,417]
  .word screen_16_name              ; S03P02 name              [418,419]
  .word screen_16_action1           ; S03P02 action1           [420,421]
  .word screen_16_action2           ; S03P02 action2           [422,423]
  .word screen_16_action3           ; S03P02 action3           [424,425]
  .word screen_16_action4           ; S03P02 action4           [426,427]
  .word screen_16_description       ; S03P02 description       [428,429]
  .word screen_16_ascii             ; S03P02 ascii             [430,431]
  .word screen_16_flashlight_on     ; S03P02 flashlight_on     [432,433]
  .word screen_16_flashlight_off    ; S03P02 flashlight_off    [434,435]
  .word screen_16_enemy_probability ; S03P02 enemy_probability [436,437]
  .word screen_16_is_secret_screen  ; S03P02 is_secret_screen  [438,439]
  .word screen_16_is_end_screen     ; S03P02 is_end_screen     [440,441]
screen_pointers_17:
  .word screen_17_id                ; S03P03 id                [442,443]
  .word screen_17_name              ; S03P03 name              [444,445]
  .word screen_17_action1           ; S03P03 action1           [446,447]
  .word screen_17_action2           ; S03P03 action2           [448,449]
  .word screen_17_action3           ; S03P03 action3           [450,451]
  .word screen_17_action4           ; S03P03 action4           [452,453]
  .word screen_17_description       ; S03P03 description       [454,455]
  .word screen_17_ascii             ; S03P03 ascii             [456,457]
  .word screen_17_flashlight_on     ; S03P03 flashlight_on     [458,459]
  .word screen_17_flashlight_off    ; S03P03 flashlight_off    [460,461]
  .word screen_17_enemy_probability ; S03P03 enemy_probability [462,463]
  .word screen_17_is_secret_screen  ; S03P03 is_secret_screen  [464,465]
  .word screen_17_is_end_screen     ; S03P03 is_end_screen     [466,467]
screen_pointers_18:
  .word screen_18_id                ; S03P04 id                [468,469]
  .word screen_18_name              ; S03P04 name              [470,471]
  .word screen_18_action1           ; S03P04 action1           [472,473]
  .word screen_18_action2           ; S03P04 action2           [474,475]
  .word screen_18_action3           ; S03P04 action3           [476,477]
  .word screen_18_action4           ; S03P04 action4           [478,479]
  .word screen_18_description       ; S03P04 description       [480,481]
  .word screen_18_ascii             ; S03P04 ascii             [482,483]
  .word screen_18_flashlight_on     ; S03P04 flashlight_on     [484,485]
  .word screen_18_flashlight_off    ; S03P04 flashlight_off    [486,487]
  .word screen_18_enemy_probability ; S03P04 enemy_probability [488,489]
  .word screen_18_is_secret_screen  ; S03P04 is_secret_screen  [490,491]
  .word screen_18_is_end_screen     ; S03P04 is_end_screen     [492,493]
screen_pointers_19:
  .word screen_19_id                ; S03P05 id                [494,495]
  .word screen_19_name              ; S03P05 name              [496,497]
  .word screen_19_action1           ; S03P05 action1           [498,499]
  .word screen_19_action2           ; S03P05 action2           [500,501]
  .word screen_19_action3           ; S03P05 action3           [502,503]
  .word screen_19_action4           ; S03P05 action4           [504,505]
  .word screen_19_description       ; S03P05 description       [506,507]
  .word screen_19_ascii             ; S03P05 ascii             [508,509]
  .word screen_19_flashlight_on     ; S03P05 flashlight_on     [510,511]
  .word screen_19_flashlight_off    ; S03P05 flashlight_off    [512,513]
  .word screen_19_enemy_probability ; S03P05 enemy_probability [514,515]
  .word screen_19_is_secret_screen  ; S03P05 is_secret_screen  [516,517]
  .word screen_19_is_end_screen     ; S03P05 is_end_screen     [518,519]
screen_pointers_20:
  .word screen_20_id                ; S03P06 id                [520,521]
  .word screen_20_name              ; S03P06 name              [522,523]
  .word screen_20_action1           ; S03P06 action1           [524,525]
  .word screen_20_action2           ; S03P06 action2           [526,527]
  .word screen_20_action3           ; S03P06 action3           [528,529]
  .word screen_20_action4           ; S03P06 action4           [530,531]
  .word screen_20_description       ; S03P06 description       [532,533]
  .word screen_20_ascii             ; S03P06 ascii             [534,535]
  .word screen_20_flashlight_on     ; S03P06 flashlight_on     [536,537]
  .word screen_20_flashlight_off    ; S03P06 flashlight_off    [538,539]
  .word screen_20_enemy_probability ; S03P06 enemy_probability [540,541]
  .word screen_20_is_secret_screen  ; S03P06 is_secret_screen  [542,543]
  .word screen_20_is_end_screen     ; S03P06 is_end_screen     [544,545]
screen_pointers_21:
  .word screen_21_id                ; S03P07 id                [546,547]
  .word screen_21_name              ; S03P07 name              [548,549]
  .word screen_21_action1           ; S03P07 action1           [550,551]
  .word screen_21_action2           ; S03P07 action2           [552,553]
  .word screen_21_action3           ; S03P07 action3           [554,555]
  .word screen_21_action4           ; S03P07 action4           [556,557]
  .word screen_21_description       ; S03P07 description       [558,559]
  .word screen_21_ascii             ; S03P07 ascii             [560,561]
  .word screen_21_flashlight_on     ; S03P07 flashlight_on     [562,563]
  .word screen_21_flashlight_off    ; S03P07 flashlight_off    [564,565]
  .word screen_21_enemy_probability ; S03P07 enemy_probability [566,567]
  .word screen_21_is_secret_screen  ; S03P07 is_secret_screen  [568,569]
  .word screen_21_is_end_screen     ; S03P07 is_end_screen     [570,571]
screen_pointers_22:
  .word screen_22_id                ; S03P08 id                [572,573]
  .word screen_22_name              ; S03P08 name              [574,575]
  .word screen_22_action1           ; S03P08 action1           [576,577]
  .word screen_22_action2           ; S03P08 action2           [578,579]
  .word screen_22_action3           ; S03P08 action3           [580,581]
  .word screen_22_action4           ; S03P08 action4           [582,583]
  .word screen_22_description       ; S03P08 description       [584,585]
  .word screen_22_ascii             ; S03P08 ascii             [586,587]
  .word screen_22_flashlight_on     ; S03P08 flashlight_on     [588,589]
  .word screen_22_flashlight_off    ; S03P08 flashlight_off    [590,591]
  .word screen_22_enemy_probability ; S03P08 enemy_probability [592,593]
  .word screen_22_is_secret_screen  ; S03P08 is_secret_screen  [594,595]
  .word screen_22_is_end_screen     ; S03P08 is_end_screen     [596,597]
screen_pointers_23:
  .word screen_23_id                ; S03P09 id                [598,599]
  .word screen_23_name              ; S03P09 name              [600,601]
  .word screen_23_action1           ; S03P09 action1           [602,603]
  .word screen_23_action2           ; S03P09 action2           [604,605]
  .word screen_23_action3           ; S03P09 action3           [606,607]
  .word screen_23_action4           ; S03P09 action4           [608,609]
  .word screen_23_description       ; S03P09 description       [610,611]
  .word screen_23_ascii             ; S03P09 ascii             [612,613]
  .word screen_23_flashlight_on     ; S03P09 flashlight_on     [614,615]
  .word screen_23_flashlight_off    ; S03P09 flashlight_off    [616,617]
  .word screen_23_enemy_probability ; S03P09 enemy_probability [618,619]
  .word screen_23_is_secret_screen  ; S03P09 is_secret_screen  [620,621]
  .word screen_23_is_end_screen     ; S03P09 is_end_screen     [622,623]
screen_pointers_24:
  .word screen_24_id                ; S04P01 id                [624,625]
  .word screen_24_name              ; S04P01 name              [626,627]
  .word screen_24_action1           ; S04P01 action1           [628,629]
  .word screen_24_action2           ; S04P01 action2           [630,631]
  .word screen_24_action3           ; S04P01 action3           [632,633]
  .word screen_24_action4           ; S04P01 action4           [634,635]
  .word screen_24_description       ; S04P01 description       [636,637]
  .word screen_24_ascii             ; S04P01 ascii             [638,639]
  .word screen_24_flashlight_on     ; S04P01 flashlight_on     [640,641]
  .word screen_24_flashlight_off    ; S04P01 flashlight_off    [642,643]
  .word screen_24_enemy_probability ; S04P01 enemy_probability [644,645]
  .word screen_24_is_secret_screen  ; S04P01 is_secret_screen  [646,647]
  .word screen_24_is_end_screen     ; S04P01 is_end_screen     [648,649]
screen_pointers_25:
  .word screen_25_id                ; S04P02 id                [650,651]
  .word screen_25_name              ; S04P02 name              [652,653]
  .word screen_25_action1           ; S04P02 action1           [654,655]
  .word screen_25_action2           ; S04P02 action2           [656,657]
  .word screen_25_action3           ; S04P02 action3           [658,659]
  .word screen_25_action4           ; S04P02 action4           [660,661]
  .word screen_25_description       ; S04P02 description       [662,663]
  .word screen_25_ascii             ; S04P02 ascii             [664,665]
  .word screen_25_flashlight_on     ; S04P02 flashlight_on     [666,667]
  .word screen_25_flashlight_off    ; S04P02 flashlight_off    [668,669]
  .word screen_25_enemy_probability ; S04P02 enemy_probability [670,671]
  .word screen_25_is_secret_screen  ; S04P02 is_secret_screen  [672,673]
  .word screen_25_is_end_screen     ; S04P02 is_end_screen     [674,675]
screen_pointers_26:
  .word screen_26_id                ; S04P03 id                [676,677]
  .word screen_26_name              ; S04P03 name              [678,679]
  .word screen_26_action1           ; S04P03 action1           [680,681]
  .word screen_26_action2           ; S04P03 action2           [682,683]
  .word screen_26_action3           ; S04P03 action3           [684,685]
  .word screen_26_action4           ; S04P03 action4           [686,687]
  .word screen_26_description       ; S04P03 description       [688,689]
  .word screen_26_ascii             ; S04P03 ascii             [690,691]
  .word screen_26_flashlight_on     ; S04P03 flashlight_on     [692,693]
  .word screen_26_flashlight_off    ; S04P03 flashlight_off    [694,695]
  .word screen_26_enemy_probability ; S04P03 enemy_probability [696,697]
  .word screen_26_is_secret_screen  ; S04P03 is_secret_screen  [698,699]
  .word screen_26_is_end_screen     ; S04P03 is_end_screen     [700,701]
screen_pointers_27:
  .word screen_27_id                ; S04P04 id                [702,703]
  .word screen_27_name              ; S04P04 name              [704,705]
  .word screen_27_action1           ; S04P04 action1           [706,707]
  .word screen_27_action2           ; S04P04 action2           [708,709]
  .word screen_27_action3           ; S04P04 action3           [710,711]
  .word screen_27_action4           ; S04P04 action4           [712,713]
  .word screen_27_description       ; S04P04 description       [714,715]
  .word screen_27_ascii             ; S04P04 ascii             [716,717]
  .word screen_27_flashlight_on     ; S04P04 flashlight_on     [718,719]
  .word screen_27_flashlight_off    ; S04P04 flashlight_off    [720,721]
  .word screen_27_enemy_probability ; S04P04 enemy_probability [722,723]
  .word screen_27_is_secret_screen  ; S04P04 is_secret_screen  [724,725]
  .word screen_27_is_end_screen     ; S04P04 is_end_screen     [726,727]
screen_pointers_28:
  .word screen_28_id                ; S04P05 id                [728,729]
  .word screen_28_name              ; S04P05 name              [730,731]
  .word screen_28_action1           ; S04P05 action1           [732,733]
  .word screen_28_action2           ; S04P05 action2           [734,735]
  .word screen_28_action3           ; S04P05 action3           [736,737]
  .word screen_28_action4           ; S04P05 action4           [738,739]
  .word screen_28_description       ; S04P05 description       [740,741]
  .word screen_28_ascii             ; S04P05 ascii             [742,743]
  .word screen_28_flashlight_on     ; S04P05 flashlight_on     [744,745]
  .word screen_28_flashlight_off    ; S04P05 flashlight_off    [746,747]
  .word screen_28_enemy_probability ; S04P05 enemy_probability [748,749]
  .word screen_28_is_secret_screen  ; S04P05 is_secret_screen  [750,751]
  .word screen_28_is_end_screen     ; S04P05 is_end_screen     [752,753]
screen_pointers_29:
  .word screen_29_id                ; FINAL id                [754,755]
  .word screen_29_name              ; FINAL name              [756,757]
  .word screen_29_action1           ; FINAL action1           [758,759]
  .word screen_29_action2           ; FINAL action2           [760,761]
  .word screen_29_action3           ; FINAL action3           [762,763]
  .word screen_29_action4           ; FINAL action4           [764,765]
  .word screen_29_description       ; FINAL description       [766,767]
  .word screen_29_ascii             ; FINAL ascii             [768,769]
  .word screen_29_flashlight_on     ; FINAL flashlight_on     [770,771]
  .word screen_29_flashlight_off    ; FINAL flashlight_off    [772,773]
  .word screen_29_enemy_probability ; FINAL enemy_probability [774,775]
  .word screen_29_is_secret_screen  ; FINAL is_secret_screen  [776,777]
  .word screen_29_is_end_screen     ; FINAL is_end_screen     [778,779]
screen_pointers_30:
  .word screen_30_id                ; EndScreenSimulationTimeisUp id                [780,781]
  .word screen_30_name              ; EndScreenSimulationTimeisUp name              [782,783]
  .word screen_30_action1           ; EndScreenSimulationTimeisUp action1           [784,785]
  .word screen_30_action2           ; EndScreenSimulationTimeisUp action2           [786,787]
  .word screen_30_action3           ; EndScreenSimulationTimeisUp action3           [788,789]
  .word screen_30_action4           ; EndScreenSimulationTimeisUp action4           [790,791]
  .word screen_30_description       ; EndScreenSimulationTimeisUp description       [792,793]
  .word screen_30_ascii             ; EndScreenSimulationTimeisUp ascii             [794,795]
  .word screen_30_flashlight_on     ; EndScreenSimulationTimeisUp flashlight_on     [796,797]
  .word screen_30_flashlight_off    ; EndScreenSimulationTimeisUp flashlight_off    [798,799]
  .word screen_30_enemy_probability ; EndScreenSimulationTimeisUp enemy_probability [800,801]
  .word screen_30_is_secret_screen  ; EndScreenSimulationTimeisUp is_secret_screen  [802,803]
  .word screen_30_is_end_screen     ; EndScreenSimulationTimeisUp is_end_screen     [804,805]
screen_pointers_31:
  .word screen_31_id                ; endScreenByEnemy id                [806,807]
  .word screen_31_name              ; endScreenByEnemy name              [808,809]
  .word screen_31_action1           ; endScreenByEnemy action1           [810,811]
  .word screen_31_action2           ; endScreenByEnemy action2           [812,813]
  .word screen_31_action3           ; endScreenByEnemy action3           [814,815]
  .word screen_31_action4           ; endScreenByEnemy action4           [816,817]
  .word screen_31_description       ; endScreenByEnemy description       [818,819]
  .word screen_31_ascii             ; endScreenByEnemy ascii             [820,821]
  .word screen_31_flashlight_on     ; endScreenByEnemy flashlight_on     [822,823]
  .word screen_31_flashlight_off    ; endScreenByEnemy flashlight_off    [824,825]
  .word screen_31_enemy_probability ; endScreenByEnemy enemy_probability [826,827]
  .word screen_31_is_secret_screen  ; endScreenByEnemy is_secret_screen  [828,829]
  .word screen_31_is_end_screen     ; endScreenByEnemy is_end_screen     [830,831]
screen_pointers_32:
  .word screen_32_id                ; endScreenByActionFailed id                [832,833]
  .word screen_32_name              ; endScreenByActionFailed name              [834,835]
  .word screen_32_action1           ; endScreenByActionFailed action1           [836,837]
  .word screen_32_action2           ; endScreenByActionFailed action2           [838,839]
  .word screen_32_action3           ; endScreenByActionFailed action3           [840,841]
  .word screen_32_action4           ; endScreenByActionFailed action4           [842,843]
  .word screen_32_description       ; endScreenByActionFailed description       [844,845]
  .word screen_32_ascii             ; endScreenByActionFailed ascii             [846,847]
  .word screen_32_flashlight_on     ; endScreenByActionFailed flashlight_on     [848,849]
  .word screen_32_flashlight_off    ; endScreenByActionFailed flashlight_off    [850,851]
  .word screen_32_enemy_probability ; endScreenByActionFailed enemy_probability [852,853]
  .word screen_32_is_secret_screen  ; endScreenByActionFailed is_secret_screen  [854,855]
  .word screen_32_is_end_screen     ; endScreenByActionFailed is_end_screen     [856,857]
screen_action_offset:
  .byte 4  ; (byte of screen_0_action1 in screens_pointers)
screen_description_offset:
  .byte 12  ; (byte of screen_0_description in screens_pointers)
screen_ascii_offset:
  .byte 14  ; (byte of screen_0_ascii in screens_pointers)
screen_flashlight_on_offset:
  .byte 16  ; (byte of screen_0_flashlight_on in screens_pointers)
screen_flashlight_off_offset:
  .byte 18  ; (byte of screen_0_flashlight_off in screens_pointers)
screen_enemy_probability_offset:
  .byte 20  ; (byte of screen_0_enemy_probability in screens_pointers)
screen_is_secret_screen_offset:
  .byte 22  ; (byte of screen_0_is_secret_screen in screens_pointers)
screen_is_end_screen_offset:
  .byte 24  ; (byte of screen_0_is_end_screen in screens_pointers)
screen_record_length:
  .byte 26  ; (total .word bytes per screen record)

; ── Screen 0: StartScreen ──────────────────────────
screen_0_id:
  .byte 0

screen_0_name:
  .ascii "StartScreen"
  .ascii "e"

screen_0_action1:
  .byte 0  ; START-COMENZAR

screen_0_action2:
  .byte 255  ; none

screen_0_action3:
  .byte 255  ; none

screen_0_action4:
  .byte 255  ; none

screen_0_description:
  .ascii "BIENVENIDX A LA PRIMER AVENTURA DE LA 20C"
  .ascii "e"

screen_0_ascii:
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#########░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#         ##░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#             #░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#                ##░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░######                   #####░░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░#     #                   #    #░░░░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░##     #                     #  # ###░░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░#     #                      # #     #░░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░░░#    #########                #####    #░░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░░#######         #       ########      #   #░░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░░░#                 #######     ##        #   #░░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░░##                  ##           ##        #   #░░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░░░#                     ###           #       ######░░░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░░##                      ##             ##     ###   ##░░░░░░░░░░░░"
  .ascii "░░░░░░░░░░░░░#####                    #                #   ##       ##░░░░░░░░░░"
  .ascii "░░░░░░░░░░░#      #    ####         ###                ###            #░░░░░░░░░"
  .ascii "░░░░░░░░░░#        ## #    #       #########        ###  #            #░░░░░░░░░"
  .ascii "░░░░░░░░░#          ##      #   ###         ##     #   ########       #░░░░░░░░░"
  .ascii "░░░░░░░░░#         #         ###              ##  #####        ##      #░░░░░░░░"
  .ascii "░░░░░░░░░#        #            #                ##              ##    #░░░░░░░░░"
  .ascii "░░░░░░░░░#       #              #               #                ##   #░░░░░░░░░"
  .ascii "░░░░░░░░░░#     #                #             #                  #  #░░░░░░░░░░"
  .ascii "░░░░░░░░░##    #                 #            #                    # #░░░░░░░░░░"
  .ascii "░░░░░░░░##    ##                 ##            #                  #   #░░░░░░░░░"
  .ascii "e"

screen_0_flashlight_on:
  .ascii ""
  .ascii "e"

screen_0_flashlight_off:
  .ascii ""
  .ascii "e"

screen_0_enemy_probability:
  .byte 0

screen_0_is_secret_screen:
  .byte 0  ; no

screen_0_is_end_screen:
  .byte 0  ; no

; ── Screen 1: S01P01 ──────────────────────────
screen_1_id:
  .byte 1

screen_1_name:
  .ascii "S01P01"
  .ascii "e"

screen_1_action1:
  .byte 1  ; S01P01-LEVANTARSE

screen_1_action2:
  .byte 255  ; none

screen_1_action3:
  .byte 255  ; none

screen_1_action4:
  .byte 255  ; none

screen_1_description:
  .ascii "TE DESPERTAS EN LA OSCURIDAD."
  .ascii "e"

screen_1_ascii:
  .ascii ""
  .ascii "e"

screen_1_flashlight_on:
  .ascii ""
  .ascii "e"

screen_1_flashlight_off:
  .ascii ""
  .ascii "e"

screen_1_enemy_probability:
  .byte 0

screen_1_is_secret_screen:
  .byte 0  ; no

screen_1_is_end_screen:
  .byte 0  ; no

; ── Screen 2: S01P02 ──────────────────────────
screen_2_id:
  .byte 2

screen_2_name:
  .ascii "S01P02"
  .ascii "e"

screen_2_action1:
  .byte 2  ; S01P02-GRITARPORAYUDA

screen_2_action2:
  .byte 255  ; none

screen_2_action3:
  .byte 255  ; none

screen_2_action4:
  .byte 255  ; none

screen_2_description:
  .ascii "ESTAS EN LA OSCURIDAD Y SENTIS EL AGUA. GRITAS POR AYUDA."
  .ascii "e"

screen_2_ascii:
  .ascii ""
  .ascii "e"

screen_2_flashlight_on:
  .ascii ""
  .ascii "e"

screen_2_flashlight_off:
  .ascii ""
  .ascii "e"

screen_2_enemy_probability:
  .byte 0

screen_2_is_secret_screen:
  .byte 0  ; no

screen_2_is_end_screen:
  .byte 0  ; no

; ── Screen 3: S01P03 ──────────────────────────
screen_3_id:
  .byte 3

screen_3_name:
  .ascii "S01P03"
  .ascii "e"

screen_3_action1:
  .byte 4  ; S01P03-EXPLORAR

screen_3_action2:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_3_action3:
  .byte 255  ; none

screen_3_action4:
  .byte 255  ; none

screen_3_description:
  .ascii "RECORDAS QUE TENES LA LINTERNA. NO TIENE MUCHA BATERIA. PODES CONTINUAR COMENZAR"
  .ascii " A EXPLORAR O USARLA. EL TIEMPO PASA."
  .ascii "e"

screen_3_ascii:
  .ascii ""
  .ascii "e"

screen_3_flashlight_on:
  .ascii ""
  .ascii "e"

screen_3_flashlight_off:
  .ascii ""
  .ascii "e"

screen_3_enemy_probability:
  .byte 0

screen_3_is_secret_screen:
  .byte 0  ; no

screen_3_is_end_screen:
  .byte 0  ; no

; ── Screen 4: S01P04 ──────────────────────────
screen_4_id:
  .byte 4

screen_4_name:
  .ascii "S01P04"
  .ascii "e"

screen_4_action1:
  .byte 5  ; S01P04-ROCASLINTERNA

screen_4_action2:
  .byte 6  ; S01P04-ROCASOSCURIDAD

screen_4_action3:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_4_action4:
  .byte 255  ; none

screen_4_description:
  .ascii ""
  .ascii "e"

screen_4_ascii:
  .ascii ""
  .ascii "e"

screen_4_flashlight_on:
  .ascii "ILUMINAS ROCAS (TENES LINTERNA)"
  .ascii "e"

screen_4_flashlight_off:
  .ascii "TOCAS ROCAS (ESTAS A OSCURAS)"
  .ascii "e"

screen_4_enemy_probability:
  .byte 0

screen_4_is_secret_screen:
  .byte 0  ; no

screen_4_is_end_screen:
  .byte 0  ; no

; ── Screen 5: S01P05 ──────────────────────────
screen_5_id:
  .byte 5

screen_5_name:
  .ascii "S01P05"
  .ascii "e"

screen_5_action1:
  .byte 7  ; S01P05-EXTRAERROCA

screen_5_action2:
  .byte 8  ; S01P05-IGNORAR

screen_5_action3:
  .byte 255  ; none

screen_5_action4:
  .byte 255  ; none

screen_5_description:
  .ascii "HAY UNA ROCA QUE TE LLAMA LA ATENCION. PODES MOVERLA, PERO SE TE PUEDE CAER TODO"
  .ascii " ENCIMA."
  .ascii "e"

screen_5_ascii:
  .ascii ""
  .ascii "e"

screen_5_flashlight_on:
  .ascii ""
  .ascii "e"

screen_5_flashlight_off:
  .ascii ""
  .ascii "e"

screen_5_enemy_probability:
  .byte 0

screen_5_is_secret_screen:
  .byte 0  ; no

screen_5_is_end_screen:
  .byte 0  ; no

; ── Screen 6: S01P06 ──────────────────────────
screen_6_id:
  .byte 6

screen_6_name:
  .ascii "S01P06"
  .ascii "e"

screen_6_action1:
  .byte 9  ; S01P06-CONTINUAR

screen_6_action2:
  .byte 255  ; none

screen_6_action3:
  .byte 255  ; none

screen_6_action4:
  .byte 255  ; none

screen_6_description:
  .ascii "ENCONTRAS UN SECRETO"
  .ascii "e"

screen_6_ascii:
  .ascii ""
  .ascii ""
  .ascii "PPPPPP  II  TTTTTT  FFFFFF   AAAA   LL      LL  "
  .ascii "PP  PP  II  TTTTTT  FFF     AA  AA  LL      LL"
  .ascii "PP  PP  II    TT    FFF     AA  AA  LL      LL"
  .ascii "PPPPPP  II    TT    FFFFFF  AAAAAA  LL      LL"
  .ascii "PP      II    TT    FF      AA  AA  LL      LL"
  .ascii "PP      II    TT    FF      AA  AA  LL      LL"
  .ascii "PP      II    TT    FF      AA  AA  LLLLLL  LLLLLL"
  .ascii "e"

screen_6_flashlight_on:
  .ascii ""
  .ascii "e"

screen_6_flashlight_off:
  .ascii ""
  .ascii "e"

screen_6_enemy_probability:
  .byte 0

screen_6_is_secret_screen:
  .byte 1  ; yes

screen_6_is_end_screen:
  .byte 0  ; no

; ── Screen 7: S01P07 ──────────────────────────
screen_7_id:
  .byte 7

screen_7_name:
  .ascii "S01P07"
  .ascii "e"

screen_7_action1:
  .byte 10  ; S01P07-ROCASSEGURO

screen_7_action2:
  .byte 11  ; S01P07-ROCASRAPIDO

screen_7_action3:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_7_action4:
  .byte 255  ; none

screen_7_description:
  .ascii "ESTAS ENCERRADO, TENES QUE TOMAR UNA DECISION. RETIRAR ROCAS DE MANERA SEGURA O "
  .ascii "HACERLO A LA FUERZA. EL TIEMPO APREMIA."
  .ascii "e"

screen_7_ascii:
  .ascii ""
  .ascii "e"

screen_7_flashlight_on:
  .ascii ""
  .ascii "e"

screen_7_flashlight_off:
  .ascii ""
  .ascii "e"

screen_7_enemy_probability:
  .byte 0

screen_7_is_secret_screen:
  .byte 0  ; no

screen_7_is_end_screen:
  .byte 0  ; no

; ── Screen 8: S02P01 ──────────────────────────
screen_8_id:
  .byte 8

screen_8_name:
  .ascii "S02P01"
  .ascii "e"

screen_8_action1:
  .byte 12  ; S02P01-CONTINUAR

screen_8_action2:
  .byte 255  ; none

screen_8_action3:
  .byte 255  ; none

screen_8_action4:
  .byte 255  ; none

screen_8_description:
  .ascii "Sobreviviste a la experiencia. El agua sigue corriendo. "
  .ascii "e"

screen_8_ascii:
  .ascii ""
  .ascii "e"

screen_8_flashlight_on:
  .ascii ""
  .ascii "e"

screen_8_flashlight_off:
  .ascii ""
  .ascii "e"

screen_8_enemy_probability:
  .byte 0

screen_8_is_secret_screen:
  .byte 0  ; no

screen_8_is_end_screen:
  .byte 0  ; no

; ── Screen 9: S02P02 ──────────────────────────
screen_9_id:
  .byte 9

screen_9_name:
  .ascii "S02P02"
  .ascii "e"

screen_9_action1:
  .byte 13  ; S02P02-DESCANSAR

screen_9_action2:
  .byte 14  ; S02P02-CORRER

screen_9_action3:
  .byte 255  ; none

screen_9_action4:
  .byte 255  ; none

screen_9_description:
  .ascii "Detras tuyo se derrumba el paso.  Esto te altera. Descansar puede ayudar a que n"
  .ascii "o te desesperes y veas con otra optica las cosas."
  .ascii "e"

screen_9_ascii:
  .ascii ""
  .ascii "e"

screen_9_flashlight_on:
  .ascii "Iluminas la habitacion. Parece ser grande."
  .ascii "e"

screen_9_flashlight_off:
  .ascii "Gritas en la habitacion. El eco tarda en llegar. Parece ser una grande."
  .ascii "e"

screen_9_enemy_probability:
  .byte 0

screen_9_is_secret_screen:
  .byte 0  ; no

screen_9_is_end_screen:
  .byte 0  ; no

; ── Screen 10: S02P03 ──────────────────────────
screen_10_id:
  .byte 10

screen_10_name:
  .ascii "S02P03"
  .ascii "e"

screen_10_action1:
  .byte 16  ; S02P03-ANALIZARMARCAS

screen_10_action2:
  .byte 17  ; S02P03-ELEGIR SALIDA

screen_10_action3:
  .byte 18  ; S02P03-EXPLORARREFLEJO

screen_10_action4:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_10_description:
  .ascii "Las opciones parecen tener mas claridad"
  .ascii "e"

screen_10_ascii:
  .ascii ""
  .ascii "e"

screen_10_flashlight_on:
  .ascii "Te encontras en un espacio grande, 3 salidas se ven al fondo. Hay unas extrañas "
  .ascii "marcas debajo tuyo."
  .ascii ""
  .ascii "Cerca de una de la salida derecha algo devuelve el reflejo."
  .ascii "e"

screen_10_flashlight_off:
  .ascii "Exploras la sala, encontras que hay 3 salidas/entradas al otro lado. Sentis unas"
  .ascii " marcas  debajo tuyo."
  .ascii "e"

screen_10_enemy_probability:
  .byte 0

screen_10_is_secret_screen:
  .byte 0  ; no

screen_10_is_end_screen:
  .byte 0  ; no

; ── Screen 11: S02P04 ──────────────────────────
screen_11_id:
  .byte 11

screen_11_name:
  .ascii "S02P04"
  .ascii "e"

screen_11_action1:
  .byte 19  ; S02P0456-VOLVER

screen_11_action2:
  .byte 255  ; none

screen_11_action3:
  .byte 255  ; none

screen_11_action4:
  .byte 255  ; none

screen_11_description:
  .ascii ""
  .ascii "e"

screen_11_ascii:
  .ascii ""
  .ascii "e"

screen_11_flashlight_on:
  .ascii "Ves la siguiente forma (patron viento)"
  .ascii "e"

screen_11_flashlight_off:
  .ascii "Al tacto sentis un patron de forma espiralada"
  .ascii "e"

screen_11_enemy_probability:
  .byte 0

screen_11_is_secret_screen:
  .byte 0  ; no

screen_11_is_end_screen:
  .byte 0  ; no

; ── Screen 12: S02P05 ──────────────────────────
screen_12_id:
  .byte 12

screen_12_name:
  .ascii "S02P05"
  .ascii "e"

screen_12_action1:
  .byte 19  ; S02P0456-VOLVER

screen_12_action2:
  .byte 255  ; none

screen_12_action3:
  .byte 255  ; none

screen_12_action4:
  .byte 255  ; none

screen_12_description:
  .ascii "¡ENCONTRAS UN SECRETO!"
  .ascii "e"

screen_12_ascii:
  .ascii "Herramienta rota clavada en la pared."
  .ascii ""
  .ascii "NO SOS LA PRIMER PERSONA AQUI"
  .ascii "e"

screen_12_flashlight_on:
  .ascii ""
  .ascii "e"

screen_12_flashlight_off:
  .ascii ""
  .ascii "e"

screen_12_enemy_probability:
  .byte 0

screen_12_is_secret_screen:
  .byte 1  ; yes

screen_12_is_end_screen:
  .byte 0  ; no

; ── Screen 13: S02P06 ──────────────────────────
screen_13_id:
  .byte 13

screen_13_name:
  .ascii "S02P06"
  .ascii "e"

screen_13_action1:
  .byte 20  ; S02P06-ANALIZARSALIDAS

screen_13_action2:
  .byte 21  ; S02P06-PROBARSUERTE

screen_13_action3:
  .byte 15  ; DESCANSAR

screen_13_action4:
  .byte 19  ; S02P0456-VOLVER

screen_13_description:
  .ascii "El agua sigue corriendo, la desesperacion apremia."
  .ascii ""
  .ascii "Podes analizar las salidas o probar tu suerte."
  .ascii "e"

screen_13_ascii:
  .ascii ""
  .ascii "e"

screen_13_flashlight_on:
  .ascii ""
  .ascii "e"

screen_13_flashlight_off:
  .ascii ""
  .ascii "e"

screen_13_enemy_probability:
  .byte 0

screen_13_is_secret_screen:
  .byte 0  ; no

screen_13_is_end_screen:
  .byte 0  ; no

; ── Screen 14: S02P07 ──────────────────────────
screen_14_id:
  .byte 14

screen_14_name:
  .ascii "S02P07"
  .ascii "e"

screen_14_action1:
  .byte 22  ; S02P07-SALIDADERECHA

screen_14_action2:
  .byte 23  ; S02P07-SALIDACENTRO

screen_14_action3:
  .byte 24  ; S02P07-SALIDAIZQUIERDA

screen_14_action4:
  .byte 25  ; S02P07-VOLVER

screen_14_description:
  .ascii "Examinas las opciones."
  .ascii ""
  .ascii "Salida derecha: escuchas ruidos, podria ser actividad"
  .ascii ""
  .ascii "Salida centro: parece haber iluminacion"
  .ascii ""
  .ascii "Salida izquierda: sentis una leve correntada de aire"
  .ascii "e"

screen_14_ascii:
  .ascii ""
  .ascii "e"

screen_14_flashlight_on:
  .ascii ""
  .ascii "e"

screen_14_flashlight_off:
  .ascii ""
  .ascii "e"

screen_14_enemy_probability:
  .byte 0

screen_14_is_secret_screen:
  .byte 0  ; no

screen_14_is_end_screen:
  .byte 0  ; no

; ── Screen 15: S03P01 ──────────────────────────
screen_15_id:
  .byte 15

screen_15_name:
  .ascii "S03P01"
  .ascii "e"

screen_15_action1:
  .byte 26  ; S03P01-AVANZARCUIDADO

screen_15_action2:
  .byte 27  ; S03P01-AVANZARCORRIENDO

screen_15_action3:
  .byte 15  ; DESCANSAR

screen_15_action4:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_15_description:
  .ascii "La caverna parece interminable."
  .ascii "e"

screen_15_ascii:
  .ascii ""
  .ascii "e"

screen_15_flashlight_on:
  .ascii "[LINTERNA]"
  .ascii ""
  .ascii "Pasillo largo y extrecho. Estalactitas en el techo. Mucho silencio."
  .ascii "e"

screen_15_flashlight_off:
  .ascii "[OSCURIDAD]"
  .ascii ""
  .ascii "Silencio antinatural, ningun eco responde"
  .ascii "e"

screen_15_enemy_probability:
  .byte 0

screen_15_is_secret_screen:
  .byte 0  ; no

screen_15_is_end_screen:
  .byte 0  ; no

; ── Screen 16: S03P02 ──────────────────────────
screen_16_id:
  .byte 16

screen_16_name:
  .ascii "S03P02"
  .ascii "e"

screen_16_action1:
  .byte 28  ; S03P02-ENCENDERLINTERNA

screen_16_action2:
  .byte 29  ; S03P02-MANTENERAPAGADA

screen_16_action3:
  .byte 255  ; none

screen_16_action4:
  .byte 255  ; none

screen_16_description:
  .ascii "Te encontras con un obstaculo."
  .ascii ""
  .ascii "Escuchas algo detras tuyo."
  .ascii "e"

screen_16_ascii:
  .ascii ""
  .ascii "e"

screen_16_flashlight_on:
  .ascii ""
  .ascii "e"

screen_16_flashlight_off:
  .ascii ""
  .ascii "e"

screen_16_enemy_probability:
  .byte 0

screen_16_is_secret_screen:
  .byte 0  ; no

screen_16_is_end_screen:
  .byte 0  ; no

; ── Screen 17: S03P03 ──────────────────────────
screen_17_id:
  .byte 17

screen_17_name:
  .ascii "S03P03"
  .ascii "e"

screen_17_action1:
  .byte 30  ; S03P03-ILUMINARTECHO

screen_17_action2:
  .byte 31  ; S03P03-ELEGIRCAMINO

screen_17_action3:
  .byte 15  ; DESCANSAR

screen_17_action4:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_17_description:
  .ascii "El obstaculo interfiere en tu camino. Podes rodearlo por la derecha o la izquier"
  .ascii "da. Estas por comenzar a rodearlo cuando sentis un temblor en el techo."
  .ascii "e"

screen_17_ascii:
  .ascii ""
  .ascii "e"

screen_17_flashlight_on:
  .ascii "[LINTERNA]"
  .ascii ""
  .ascii "Tu linterna parpadea"
  .ascii "e"

screen_17_flashlight_off:
  .ascii ""
  .ascii "e"

screen_17_enemy_probability:
  .byte 25

screen_17_is_secret_screen:
  .byte 0  ; no

screen_17_is_end_screen:
  .byte 0  ; no

; ── Screen 18: S03P04 ──────────────────────────
screen_18_id:
  .byte 18

screen_18_name:
  .ascii "S03P04"
  .ascii "e"

screen_18_action1:
  .byte 32  ; S03P04-VOLVER

screen_18_action2:
  .byte 255  ; none

screen_18_action3:
  .byte 255  ; none

screen_18_action4:
  .byte 255  ; none

screen_18_description:
  .ascii "Dibujo que muestra una estalactita a la derecha y un hueco a la izquierda."
  .ascii "e"

screen_18_ascii:
  .ascii ""
  .ascii "e"

screen_18_flashlight_on:
  .ascii ""
  .ascii "e"

screen_18_flashlight_off:
  .ascii ""
  .ascii "e"

screen_18_enemy_probability:
  .byte 0

screen_18_is_secret_screen:
  .byte 0  ; no

screen_18_is_end_screen:
  .byte 0  ; no

; ── Screen 19: S03P05 ──────────────────────────
screen_19_id:
  .byte 19

screen_19_name:
  .ascii "S03P05"
  .ascii "e"

screen_19_action1:
  .byte 33  ; S03P05-ELEGIRDERECHA

screen_19_action2:
  .byte 34  ; S03P05-ELEGIRIZQUIERDA

screen_19_action3:
  .byte 255  ; none

screen_19_action4:
  .byte 255  ; none

screen_19_description:
  .ascii "Elegis el camino a seguir."
  .ascii ""
  .ascii ""
  .ascii "e"

screen_19_ascii:
  .ascii ""
  .ascii "e"

screen_19_flashlight_on:
  .ascii ""
  .ascii "e"

screen_19_flashlight_off:
  .ascii ""
  .ascii "e"

screen_19_enemy_probability:
  .byte 0

screen_19_is_secret_screen:
  .byte 0  ; no

screen_19_is_end_screen:
  .byte 0  ; no

; ── Screen 20: S03P06 ──────────────────────────
screen_20_id:
  .byte 20

screen_20_name:
  .ascii "S03P06"
  .ascii "e"

screen_20_action1:
  .byte 35  ; S03P06-ILUMINARTECHO

screen_20_action2:
  .byte 36  ; S03P06-ELEGIRCAMINO

screen_20_action3:
  .byte 15  ; DESCANSAR

screen_20_action4:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_20_description:
  .ascii "Seguis por el pasillo, te encontras otro obstaculo."
  .ascii ""
  .ascii "Nuevamente podes rodearlo por la derecha o la izquierda."
  .ascii "e"

screen_20_ascii:
  .ascii ""
  .ascii "e"

screen_20_flashlight_on:
  .ascii ""
  .ascii "e"

screen_20_flashlight_off:
  .ascii ""
  .ascii "e"

screen_20_enemy_probability:
  .byte 0

screen_20_is_secret_screen:
  .byte 0  ; no

screen_20_is_end_screen:
  .byte 0  ; no

; ── Screen 21: S03P07 ──────────────────────────
screen_21_id:
  .byte 21

screen_21_name:
  .ascii "S03P07"
  .ascii "e"

screen_21_action1:
  .byte 37  ; S03P07-ILUMINARMARCAS

screen_21_action2:
  .byte 38  ; S03P07-VOLVER

screen_21_action3:
  .byte 255  ; none

screen_21_action4:
  .byte 255  ; none

screen_21_description:
  .ascii "Dibujo que muestra un techo liso. Unas marcas llaman la atencion en la parte sup"
  .ascii "erior del obstaculo"
  .ascii "e"

screen_21_ascii:
  .ascii ""
  .ascii "e"

screen_21_flashlight_on:
  .ascii ""
  .ascii "e"

screen_21_flashlight_off:
  .ascii ""
  .ascii "e"

screen_21_enemy_probability:
  .byte 0

screen_21_is_secret_screen:
  .byte 0  ; no

screen_21_is_end_screen:
  .byte 0  ; no

; ── Screen 22: S03P08 ──────────────────────────
screen_22_id:
  .byte 22

screen_22_name:
  .ascii "S03P08"
  .ascii "e"

screen_22_action1:
  .byte 39  ; S03P08-VOLVER

screen_22_action2:
  .byte 255  ; none

screen_22_action3:
  .byte 255  ; none

screen_22_action4:
  .byte 255  ; none

screen_22_description:
  .ascii "¡ENCONTRAS UN SECRETO!"
  .ascii "e"

screen_22_ascii:
  .ascii "Secreto: Marcas que suben hasta perderse en el techo."
  .ascii ""
  .ascii "ALGO O ALGUIEN PARECE HABER SIDO ARRASTRADO"
  .ascii "e"

screen_22_flashlight_on:
  .ascii ""
  .ascii "e"

screen_22_flashlight_off:
  .ascii ""
  .ascii "e"

screen_22_enemy_probability:
  .byte 25

screen_22_is_secret_screen:
  .byte 1  ; yes

screen_22_is_end_screen:
  .byte 0  ; no

; ── Screen 23: S03P09 ──────────────────────────
screen_23_id:
  .byte 23

screen_23_name:
  .ascii "S03P09"
  .ascii "e"

screen_23_action1:
  .byte 40  ; S03P09-ELEGIRDERECHA

screen_23_action2:
  .byte 41  ; S03P09-ELEGIRIZQUIERDA

screen_23_action3:
  .byte 255  ; none

screen_23_action4:
  .byte 255  ; none

screen_23_description:
  .ascii "Elegis el camino a seguir."
  .ascii "e"

screen_23_ascii:
  .ascii ""
  .ascii "e"

screen_23_flashlight_on:
  .ascii ""
  .ascii "e"

screen_23_flashlight_off:
  .ascii ""
  .ascii "e"

screen_23_enemy_probability:
  .byte 0

screen_23_is_secret_screen:
  .byte 0  ; no

screen_23_is_end_screen:
  .byte 0  ; no

; ── Screen 24: S04P01 ──────────────────────────
screen_24_id:
  .byte 24

screen_24_name:
  .ascii "S04P01"
  .ascii "e"

screen_24_action1:
  .byte 42  ; S04P01-DESCENDER

screen_24_action2:
  .byte 15  ; DESCANSAR

screen_24_action3:
  .byte 3  ; LINTERNACORAZON-TOGGLE

screen_24_action4:
  .byte 255  ; none

screen_24_description:
  .ascii "El camino se ve interrumpido por un agujero."
  .ascii "e"

screen_24_ascii:
  .ascii ""
  .ascii "e"

screen_24_flashlight_on:
  .ascii "[LINTERNA]"
  .ascii ""
  .ascii "Es un pozo vertical sin fondo visible. Hay una soga que sobresale y desciende."
  .ascii "e"

screen_24_flashlight_off:
  .ascii "[OSCURIDAD]"
  .ascii ""
  .ascii "Tiras una piedra y no escuchas cuando toca el fondo."
  .ascii "e"

screen_24_enemy_probability:
  .byte 0

screen_24_is_secret_screen:
  .byte 0  ; no

screen_24_is_end_screen:
  .byte 0  ; no

; ── Screen 25: S04P02 ──────────────────────────
screen_25_id:
  .byte 25

screen_25_name:
  .ascii "S04P02"
  .ascii "e"

screen_25_action1:
  .byte 43  ; S04P02-USARSALIENTE

screen_25_action2:
  .byte 44  ; S04P02-NOUSARSALIENTES

screen_25_action3:
  .byte 255  ; none

screen_25_action4:
  .byte 255  ; none

screen_25_description:
  .ascii "Encontras que el pozo tiene algunas salientes que pueden ayudarte. Un descenso s"
  .ascii "eguro llevaria mas tiempo. Por otro lado, no sabes por que esa soga se encuentra"
  .ascii " alli. Un descenso rapido puede ser riesgoso."
  .ascii "e"

screen_25_ascii:
  .ascii ""
  .ascii "e"

screen_25_flashlight_on:
  .ascii ""
  .ascii "e"

screen_25_flashlight_off:
  .ascii ""
  .ascii "e"

screen_25_enemy_probability:
  .byte 0

screen_25_is_secret_screen:
  .byte 0  ; no

screen_25_is_end_screen:
  .byte 0  ; no

; ── Screen 26: S04P03 ──────────────────────────
screen_26_id:
  .byte 26

screen_26_name:
  .ascii "S04P03"
  .ascii "e"

screen_26_action1:
  .byte 45  ; S04P03-EXPLORARZONA

screen_26_action2:
  .byte 46  ; S04P03-USARSALIENTES

screen_26_action3:
  .byte 47  ; S04P03-NOUSARSALIENTES

screen_26_action4:
  .byte 15  ; DESCANSAR

screen_26_description:
  .ascii "Llegas a la saliente. Podes explorar la zona o seguir."
  .ascii "e"

screen_26_ascii:
  .ascii ""
  .ascii "e"

screen_26_flashlight_on:
  .ascii ""
  .ascii "e"

screen_26_flashlight_off:
  .ascii ""
  .ascii "e"

screen_26_enemy_probability:
  .byte 0

screen_26_is_secret_screen:
  .byte 0  ; no

screen_26_is_end_screen:
  .byte 0  ; no

; ── Screen 27: S04P04 ──────────────────────────
screen_27_id:
  .byte 27

screen_27_name:
  .ascii "S04P04"
  .ascii "e"

screen_27_action1:
  .byte 48  ; S04P04-EXPLORARZONA

screen_27_action2:
  .byte 49  ; S04P04-USARSALIENTES

screen_27_action3:
  .byte 50  ; S04P04-NOUSARSALIENTES

screen_27_action4:
  .byte 15  ; DESCANSAR

screen_27_description:
  .ascii "Llegas a la saliente. Podes explorar la zona o seguir."
  .ascii ""
  .ascii "El fondo parece estar mas cerca"
  .ascii "e"

screen_27_ascii:
  .ascii ""
  .ascii "e"

screen_27_flashlight_on:
  .ascii ""
  .ascii "e"

screen_27_flashlight_off:
  .ascii ""
  .ascii "e"

screen_27_enemy_probability:
  .byte 0

screen_27_is_secret_screen:
  .byte 0  ; no

screen_27_is_end_screen:
  .byte 0  ; no

; ── Screen 28: S04P05 ──────────────────────────
screen_28_id:
  .byte 28

screen_28_name:
  .ascii "S04P05"
  .ascii "e"

screen_28_action1:
  .byte 51  ; S04P05-VOLVER

screen_28_action2:
  .byte 255  ; none

screen_28_action3:
  .byte 255  ; none

screen_28_action4:
  .byte 255  ; none

screen_28_description:
  .ascii "¡ENCONTRAS UN SECRETO!"
  .ascii "e"

screen_28_ascii:
  .ascii "Secreto: Soga cortada al borde de una saliente."
  .ascii ""
  .ascii "EL CORTE NO PARECE HABER SIDO HECHO DE MANERA NATURAL"
  .ascii "e"

screen_28_flashlight_on:
  .ascii ""
  .ascii "e"

screen_28_flashlight_off:
  .ascii ""
  .ascii "e"

screen_28_enemy_probability:
  .byte 0

screen_28_is_secret_screen:
  .byte 1  ; yes

screen_28_is_end_screen:
  .byte 0  ; no

; ── Screen 29: FINAL ──────────────────────────
screen_29_id:
  .byte 29

screen_29_name:
  .ascii "FINAL"
  .ascii "e"

screen_29_action1:
  .byte 255  ; none

screen_29_action2:
  .byte 255  ; none

screen_29_action3:
  .byte 255  ; none

screen_29_action4:
  .byte 255  ; none

screen_29_description:
  .ascii "Sales arrastrándote."
  .ascii ""
  .ascii "El agua no te sigue."
  .ascii ""
  .ascii "La caverna no se derrumba."
  .ascii ""
  .ascii ""
  .ascii ""
  .ascii "Simplemente deja de importarte. Tu humanidad quedo enterrada alli."
  .ascii "e"

screen_29_ascii:
  .ascii ""
  .ascii "e"

screen_29_flashlight_on:
  .ascii ""
  .ascii "e"

screen_29_flashlight_off:
  .ascii ""
  .ascii "e"

screen_29_enemy_probability:
  .byte 0

screen_29_is_secret_screen:
  .byte 0  ; no

screen_29_is_end_screen:
  .byte 0  ; no

; ── Screen 30: EndScreenSimulationTimeisUp ──────────────────────────
screen_30_id:
  .byte 30

screen_30_name:
  .ascii "EndScreenSimulationTimeisUp"
  .ascii "e"

screen_30_action1:
  .byte 52  ; TERMINAR EL JUEGO

screen_30_action2:
  .byte 255  ; none

screen_30_action3:
  .byte 255  ; none

screen_30_action4:
  .byte 255  ; none

screen_30_description:
  .ascii "Tardaste Muuuucho y te quedaste sin tiempo....."
  .ascii "e"

screen_30_ascii:
  .ascii ""
  .ascii "e"

screen_30_flashlight_on:
  .ascii ""
  .ascii "e"

screen_30_flashlight_off:
  .ascii ""
  .ascii "e"

screen_30_enemy_probability:
  .byte 0

screen_30_is_secret_screen:
  .byte 0  ; no

screen_30_is_end_screen:
  .byte 1  ; yes

; ── Screen 31: endScreenByEnemy ──────────────────────────
screen_31_id:
  .byte 31

screen_31_name:
  .ascii "endScreenByEnemy"
  .ascii "e"

screen_31_action1:
  .byte 52  ; TERMINAR EL JUEGO

screen_31_action2:
  .byte 255  ; none

screen_31_action3:
  .byte 255  ; none

screen_31_action4:
  .byte 255  ; none

screen_31_description:
  .ascii "El enemigo que siempre acechaba te atrapó, este es tu fin"
  .ascii "e"

screen_31_ascii:
  .ascii ""
  .ascii "e"

screen_31_flashlight_on:
  .ascii ""
  .ascii "e"

screen_31_flashlight_off:
  .ascii ""
  .ascii "e"

screen_31_enemy_probability:
  .byte 0

screen_31_is_secret_screen:
  .byte 0  ; no

screen_31_is_end_screen:
  .byte 1  ; yes

; ── Screen 32: endScreenByActionFailed ──────────────────────────
screen_32_id:
  .byte 32

screen_32_name:
  .ascii "endScreenByActionFailed"
  .ascii "e"

screen_32_action1:
  .byte 52  ; TERMINAR EL JUEGO

screen_32_action2:
  .byte 255  ; none

screen_32_action3:
  .byte 255  ; none

screen_32_action4:
  .byte 255  ; none

screen_32_description:
  .ascii "Tu acción tenía una gran chance de fallar y falló. Este es tu fin"
  .ascii "e"

screen_32_ascii:
  .ascii ""
  .ascii "e"

screen_32_flashlight_on:
  .ascii ""
  .ascii "e"

screen_32_flashlight_off:
  .ascii ""
  .ascii "e"

screen_32_enemy_probability:
  .byte 0

screen_32_is_secret_screen:
  .byte 0  ; no

screen_32_is_end_screen:
  .byte 1  ; yes

; ── Total screen count ──────────────────────────────────────
screen_count:
  .byte 33

; ── Total secret screens count ──────────────────────────────
screens_with_secrets:
  .byte 4
