; ============================================================
;  ACS Actions — auto-generated by acs_actions_to_asm.py
; ============================================================

actions_index:
  .word action_pointer_0  ; LEVANTARSE
  .word action_pointer_1  ; MIRAR ALREDEDOR
  .word action_pointer_2  ; GRITAR POR AYUDA
  .word action_pointer_3  ; MIRAR ENTRADA
  .word action_pointer_4  ; GRITAR
  .word action_pointer_5  ; LINTERNA
  .word action_pointer_6  ; EXPLORAR CAMINO
  .word action_pointer_7  ; CAEAGUA
actions_index_record_length:
  .byte 2  ; each actions_index entry is 1 .word (2 bytes)

actions_pointers:
action_pointer_0:
  .word action_0_id            ; LEVANTARSE id            [0,1]
  .word action_0_name          ; LEVANTARSE name          [2,3]
  .word action_0_sensor_id     ; LEVANTARSE sensor_id     [4,5]
  .word action_0_sensor_active ; LEVANTARSE sensor_active [6,7]
  .word action_0_cost          ; LEVANTARSE cost          [8,9]
  .word action_0_description   ; LEVANTARSE description   [10,11]
action_pointer_1:
  .word action_1_id            ; MIRAR ALREDEDOR id            [12,13]
  .word action_1_name          ; MIRAR ALREDEDOR name          [14,15]
  .word action_1_sensor_id     ; MIRAR ALREDEDOR sensor_id     [16,17]
  .word action_1_sensor_active ; MIRAR ALREDEDOR sensor_active [18,19]
  .word action_1_cost          ; MIRAR ALREDEDOR cost          [20,21]
  .word action_1_description   ; MIRAR ALREDEDOR description   [22,23]
action_pointer_2:
  .word action_2_id            ; GRITAR POR AYUDA id            [24,25]
  .word action_2_name          ; GRITAR POR AYUDA name          [26,27]
  .word action_2_sensor_id     ; GRITAR POR AYUDA sensor_id     [28,29]
  .word action_2_sensor_active ; GRITAR POR AYUDA sensor_active [30,31]
  .word action_2_cost          ; GRITAR POR AYUDA cost          [32,33]
  .word action_2_description   ; GRITAR POR AYUDA description   [34,35]
action_pointer_3:
  .word action_3_id            ; MIRAR ENTRADA id            [36,37]
  .word action_3_name          ; MIRAR ENTRADA name          [38,39]
  .word action_3_sensor_id     ; MIRAR ENTRADA sensor_id     [40,41]
  .word action_3_sensor_active ; MIRAR ENTRADA sensor_active [42,43]
  .word action_3_cost          ; MIRAR ENTRADA cost          [44,45]
  .word action_3_description   ; MIRAR ENTRADA description   [46,47]
action_pointer_4:
  .word action_4_id            ; GRITAR id            [48,49]
  .word action_4_name          ; GRITAR name          [50,51]
  .word action_4_sensor_id     ; GRITAR sensor_id     [52,53]
  .word action_4_sensor_active ; GRITAR sensor_active [54,55]
  .word action_4_cost          ; GRITAR cost          [56,57]
  .word action_4_description   ; GRITAR description   [58,59]
action_pointer_5:
  .word action_5_id            ; LINTERNA id            [60,61]
  .word action_5_name          ; LINTERNA name          [62,63]
  .word action_5_sensor_id     ; LINTERNA sensor_id     [64,65]
  .word action_5_sensor_active ; LINTERNA sensor_active [66,67]
  .word action_5_cost          ; LINTERNA cost          [68,69]
  .word action_5_description   ; LINTERNA description   [70,71]
action_pointer_6:
  .word action_6_id            ; EXPLORAR CAMINO id            [72,73]
  .word action_6_name          ; EXPLORAR CAMINO name          [74,75]
  .word action_6_sensor_id     ; EXPLORAR CAMINO sensor_id     [76,77]
  .word action_6_sensor_active ; EXPLORAR CAMINO sensor_active [78,79]
  .word action_6_cost          ; EXPLORAR CAMINO cost          [80,81]
  .word action_6_description   ; EXPLORAR CAMINO description   [82,83]
action_pointer_7:
  .word action_7_id            ; CAEAGUA id            [84,85]
  .word action_7_name          ; CAEAGUA name          [86,87]
  .word action_7_sensor_id     ; CAEAGUA sensor_id     [88,89]
  .word action_7_sensor_active ; CAEAGUA sensor_active [90,91]
  .word action_7_cost          ; CAEAGUA cost          [92,93]
  .word action_7_description   ; CAEAGUA description   [94,95]
action_name_offset:
  .byte 2  ; (byte of action_0_name in actions_pointers)
action_description_offset:
  .byte 10  ; (byte of action_0_description in actions_pointers)
action_record_length:
  .byte 12  ; (total .word bytes per action record)

; ── Action 0: LEVANTARSE ──────────────────────────
action_0_id:
  .byte 0

action_0_name:
  .ascii "LEVANTARSE"
  .ascii "e"

action_0_sensor_id:
  .byte 0  ; none

action_0_sensor_active:
  .byte 1  ; on

action_0_cost:
  .byte 15

action_0_description:
  .ascii "\"Con esfuerzo, te incorporas sin saber como. Semejante derrumbe deberia haber sido mortal. El frio no duele, todavia\"."
  .ascii "e"

; ── Action 1: MIRAR ALREDEDOR ──────────────────────────
action_1_id:
  .byte 1

action_1_name:
  .ascii "MIRAR ALREDEDOR"
  .ascii "e"

action_1_sensor_id:
  .byte 255  ; none

action_1_sensor_active:
  .byte 0  ; off

action_1_cost:
  .byte 15

action_1_description:
  .ascii "\"Desde el suelo solo se ve oscuridad\""
  .ascii "e"

; ── Action 2: GRITAR POR AYUDA ──────────────────────────
action_2_id:
  .byte 2

action_2_name:
  .ascii "GRITAR POR AYUDA"
  .ascii "e"

action_2_sensor_id:
  .byte 255  ; none

action_2_sensor_active:
  .byte 0  ; off

action_2_cost:
  .byte 15

action_2_description:
  .ascii "\"Intentas gritar, pero tu boca esta llena de agua\""
  .ascii "e"

; ── Action 3: MIRAR ENTRADA ──────────────────────────
action_3_id:
  .byte 3

action_3_name:
  .ascii "MIRAR ENTRADA"
  .ascii "e"

action_3_sensor_id:
  .byte 255  ; none

action_3_sensor_active:
  .byte 0  ; off

action_3_cost:
  .byte 15

action_3_description:
  .ascii "\"Entre las rocas hay rendijas por donde entra aire viciado, pero ninguna lo bastante grande para pasar. Hay marcas irregulares, como si alguien hubiera intentado moverlas y se hubiera detenido a mitad de camino. Tal vez no sea una opcion volver por ahí, pero la idea de explorar una caverna a oscuras no parece tentadora.\""
  .ascii "e"

; ── Action 4: GRITAR ──────────────────────────
action_4_id:
  .byte 4

action_4_name:
  .ascii "GRITAR"
  .ascii "e"

action_4_sensor_id:
  .byte 255  ; none

action_4_sensor_active:
  .byte 0  ; off

action_4_cost:
  .byte 10

action_4_description:
  .ascii "\"El eco tarda demasiado en volver. Sientes que algo se mueve encima de ti. Debe ser tu imaginacion, te repites.\""
  .ascii "e"

; ── Action 5: LINTERNA ──────────────────────────
action_5_id:
  .byte 5

action_5_name:
  .ascii "LINTERNA"
  .ascii "e"

action_5_sensor_id:
  .byte 255  ; none

action_5_sensor_active:
  .byte 0  ; off

action_5_cost:
  .byte 5

action_5_description:
  .ascii "La linterna se "
  .ascii "e"

; ── Action 6: EXPLORAR CAMINO ──────────────────────────
action_6_id:
  .byte 6

action_6_name:
  .ascii "EXPLORAR CAMINO"
  .ascii "e"

action_6_sensor_id:
  .byte 255  ; none

action_6_sensor_active:
  .byte 0  ; off

action_6_cost:
  .byte 20

action_6_description:
  .ascii "La linterna se "
  .ascii "e"

; ── Action 7: CAEAGUA ──────────────────────────
action_7_id:
  .byte 7

action_7_name:
  .ascii "CAEAGUA"
  .ascii "e"

action_7_sensor_id:
  .byte 255  ; none

action_7_sensor_active:
  .byte 0  ; off

action_7_cost:
  .byte 0

action_7_description:
  .ascii ""
  .ascii "e"

; ── Total action count ──────────────────────────────────────
action_count:
  .byte 8
