; ============================================================
;  ACS Actions — auto-generated by acs_actions_to_asm.py
; ============================================================

actions_index:
  .word action_pointer_0  ; LEVANTARSE
  .word action_pointer_1  ; MIRAR ALREDEDOR
  .word action_pointer_2  ; GRITAR POR AYUDA
  .word action_pointer_3  ; MIRAR ENTRADA
  .word action_pointer_4  ; GRITAR
  .word action_pointer_5  ; LINTERNA
  .word action_pointer_6  ; EXPLORAR CAMINO
  .word action_pointer_7  ; VEO QUE CAE AGUA
  .word action_pointer_8  ; COMENZAR EL JUEGO
  .word action_pointer_9  ; TERMINAR EL JUEGO
  .word action_pointer_10  ; EXPLORAR MARCAS
  .word action_pointer_11  ; FORZAR ENTRADA
  .word action_pointer_12  ; VOLVER A MIRAR ADELANTE
actions_index_record_length:
  .byte 2  ; each actions_index entry is 1 .word (2 bytes)

actions_pointers:
action_pointer_0:
  .word action_0_id            ; LEVANTARSE id            [0,1]
  .word action_0_name          ; LEVANTARSE name          [2,3]
  .word action_0_sensor_id     ; LEVANTARSE sensor_id     [4,5]
  .word action_0_sensor_active ; LEVANTARSE sensor_active [6,7]
  .word action_0_screen        ; LEVANTARSE screen        [8,9]
  .word action_0_cost          ; LEVANTARSE cost          [10,11]
  .word action_0_description   ; LEVANTARSE description   [12,13]
action_pointer_1:
  .word action_1_id            ; MIRAR ALREDEDOR id            [14,15]
  .word action_1_name          ; MIRAR ALREDEDOR name          [16,17]
  .word action_1_sensor_id     ; MIRAR ALREDEDOR sensor_id     [18,19]
  .word action_1_sensor_active ; MIRAR ALREDEDOR sensor_active [20,21]
  .word action_1_screen        ; MIRAR ALREDEDOR screen        [22,23]
  .word action_1_cost          ; MIRAR ALREDEDOR cost          [24,25]
  .word action_1_description   ; MIRAR ALREDEDOR description   [26,27]
action_pointer_2:
  .word action_2_id            ; GRITAR POR AYUDA id            [28,29]
  .word action_2_name          ; GRITAR POR AYUDA name          [30,31]
  .word action_2_sensor_id     ; GRITAR POR AYUDA sensor_id     [32,33]
  .word action_2_sensor_active ; GRITAR POR AYUDA sensor_active [34,35]
  .word action_2_screen        ; GRITAR POR AYUDA screen        [36,37]
  .word action_2_cost          ; GRITAR POR AYUDA cost          [38,39]
  .word action_2_description   ; GRITAR POR AYUDA description   [40,41]
action_pointer_3:
  .word action_3_id            ; MIRAR ENTRADA id            [42,43]
  .word action_3_name          ; MIRAR ENTRADA name          [44,45]
  .word action_3_sensor_id     ; MIRAR ENTRADA sensor_id     [46,47]
  .word action_3_sensor_active ; MIRAR ENTRADA sensor_active [48,49]
  .word action_3_screen        ; MIRAR ENTRADA screen        [50,51]
  .word action_3_cost          ; MIRAR ENTRADA cost          [52,53]
  .word action_3_description   ; MIRAR ENTRADA description   [54,55]
action_pointer_4:
  .word action_4_id            ; GRITAR id            [56,57]
  .word action_4_name          ; GRITAR name          [58,59]
  .word action_4_sensor_id     ; GRITAR sensor_id     [60,61]
  .word action_4_sensor_active ; GRITAR sensor_active [62,63]
  .word action_4_screen        ; GRITAR screen        [64,65]
  .word action_4_cost          ; GRITAR cost          [66,67]
  .word action_4_description   ; GRITAR description   [68,69]
action_pointer_5:
  .word action_5_id            ; LINTERNA id            [70,71]
  .word action_5_name          ; LINTERNA name          [72,73]
  .word action_5_sensor_id     ; LINTERNA sensor_id     [74,75]
  .word action_5_sensor_active ; LINTERNA sensor_active [76,77]
  .word action_5_screen        ; LINTERNA screen        [78,79]
  .word action_5_cost          ; LINTERNA cost          [80,81]
  .word action_5_description   ; LINTERNA description   [82,83]
action_pointer_6:
  .word action_6_id            ; EXPLORAR CAMINO id            [84,85]
  .word action_6_name          ; EXPLORAR CAMINO name          [86,87]
  .word action_6_sensor_id     ; EXPLORAR CAMINO sensor_id     [88,89]
  .word action_6_sensor_active ; EXPLORAR CAMINO sensor_active [90,91]
  .word action_6_screen        ; EXPLORAR CAMINO screen        [92,93]
  .word action_6_cost          ; EXPLORAR CAMINO cost          [94,95]
  .word action_6_description   ; EXPLORAR CAMINO description   [96,97]
action_pointer_7:
  .word action_7_id            ; VEO QUE CAE AGUA id            [98,99]
  .word action_7_name          ; VEO QUE CAE AGUA name          [100,101]
  .word action_7_sensor_id     ; VEO QUE CAE AGUA sensor_id     [102,103]
  .word action_7_sensor_active ; VEO QUE CAE AGUA sensor_active [104,105]
  .word action_7_screen        ; VEO QUE CAE AGUA screen        [106,107]
  .word action_7_cost          ; VEO QUE CAE AGUA cost          [108,109]
  .word action_7_description   ; VEO QUE CAE AGUA description   [110,111]
action_pointer_8:
  .word action_8_id            ; COMENZAR EL JUEGO id            [112,113]
  .word action_8_name          ; COMENZAR EL JUEGO name          [114,115]
  .word action_8_sensor_id     ; COMENZAR EL JUEGO sensor_id     [116,117]
  .word action_8_sensor_active ; COMENZAR EL JUEGO sensor_active [118,119]
  .word action_8_screen        ; COMENZAR EL JUEGO screen        [120,121]
  .word action_8_cost          ; COMENZAR EL JUEGO cost          [122,123]
  .word action_8_description   ; COMENZAR EL JUEGO description   [124,125]
action_pointer_9:
  .word action_9_id            ; TERMINAR EL JUEGO id            [126,127]
  .word action_9_name          ; TERMINAR EL JUEGO name          [128,129]
  .word action_9_sensor_id     ; TERMINAR EL JUEGO sensor_id     [130,131]
  .word action_9_sensor_active ; TERMINAR EL JUEGO sensor_active [132,133]
  .word action_9_screen        ; TERMINAR EL JUEGO screen        [134,135]
  .word action_9_cost          ; TERMINAR EL JUEGO cost          [136,137]
  .word action_9_description   ; TERMINAR EL JUEGO description   [138,139]
action_pointer_10:
  .word action_10_id            ; EXPLORAR MARCAS id            [140,141]
  .word action_10_name          ; EXPLORAR MARCAS name          [142,143]
  .word action_10_sensor_id     ; EXPLORAR MARCAS sensor_id     [144,145]
  .word action_10_sensor_active ; EXPLORAR MARCAS sensor_active [146,147]
  .word action_10_screen        ; EXPLORAR MARCAS screen        [148,149]
  .word action_10_cost          ; EXPLORAR MARCAS cost          [150,151]
  .word action_10_description   ; EXPLORAR MARCAS description   [152,153]
action_pointer_11:
  .word action_11_id            ; FORZAR ENTRADA id            [154,155]
  .word action_11_name          ; FORZAR ENTRADA name          [156,157]
  .word action_11_sensor_id     ; FORZAR ENTRADA sensor_id     [158,159]
  .word action_11_sensor_active ; FORZAR ENTRADA sensor_active [160,161]
  .word action_11_screen        ; FORZAR ENTRADA screen        [162,163]
  .word action_11_cost          ; FORZAR ENTRADA cost          [164,165]
  .word action_11_description   ; FORZAR ENTRADA description   [166,167]
action_pointer_12:
  .word action_12_id            ; VOLVER A MIRAR ADELANTE id            [168,169]
  .word action_12_name          ; VOLVER A MIRAR ADELANTE name          [170,171]
  .word action_12_sensor_id     ; VOLVER A MIRAR ADELANTE sensor_id     [172,173]
  .word action_12_sensor_active ; VOLVER A MIRAR ADELANTE sensor_active [174,175]
  .word action_12_screen        ; VOLVER A MIRAR ADELANTE screen        [176,177]
  .word action_12_cost          ; VOLVER A MIRAR ADELANTE cost          [178,179]
  .word action_12_description   ; VOLVER A MIRAR ADELANTE description   [180,181]
action_name_offset:
  .byte 2  ; (byte of action_0_name in actions_pointers)
action_sensor_id_offset:
  .byte 4  ; (byte of action_0_sensor_id in actions_pointers)
action_sensor_active_offset:
  .byte 6  ; (byte of action_0_sensor_id in actions_pointers)
action_screen_offset:
  .byte 8  ; (byte of action_0_screen in actions_pointers)
action_description_offset:
  .byte 12  ; (byte of action_0_description in actions_pointers)
action_record_length:
  .byte 14  ; (total .word bytes per action record)

; ── Action 0: LEVANTARSE ──────────────────────────
action_0_id:
  .byte 0

action_0_name:
  .ascii "LEVANTARSE"
  .ascii "e"

action_0_sensor_id:
  .byte 0  ; none

action_0_sensor_active:
  .byte 1  ; on

action_0_screen:
  .byte 1  ; screen id

action_0_cost:
  .byte 15

action_0_description:
  .ascii "Con esfuerzo, te incorporas sin saber como. Semejante derrumbe deberia haber sido mortal. El frio no duele, todavia."
  .ascii "e"

; ── Action 1: MIRAR ALREDEDOR ──────────────────────────
action_1_id:
  .byte 1

action_1_name:
  .ascii "MIRAR ALREDEDOR"
  .ascii "e"

action_1_sensor_id:
  .byte 255  ; none

action_1_sensor_active:
  .byte 0  ; off

action_1_screen:
  .byte 255  ; screen id

action_1_cost:
  .byte 15

action_1_description:
  .ascii "Desde el suelo solo se ve oscuridad"
  .ascii "e"

; ── Action 2: GRITAR POR AYUDA ──────────────────────────
action_2_id:
  .byte 2

action_2_name:
  .ascii "GRITAR POR AYUDA"
  .ascii "e"

action_2_sensor_id:
  .byte 255  ; none

action_2_sensor_active:
  .byte 0  ; off

action_2_screen:
  .byte 255  ; screen id

action_2_cost:
  .byte 15

action_2_description:
  .ascii "Intentas gritar, pero tu boca esta llena de agua"
  .ascii "e"

; ── Action 3: MIRAR ENTRADA ──────────────────────────
action_3_id:
  .byte 3

action_3_name:
  .ascii "MIRAR ENTRADA"
  .ascii "e"

action_3_sensor_id:
  .byte 255  ; none

action_3_sensor_active:
  .byte 0  ; off

action_3_screen:
  .byte 6  ; screen id

action_3_cost:
  .byte 15

action_3_description:
  .ascii "Miras la Entrada"
  .ascii "e"

; ── Action 4: GRITAR ──────────────────────────
action_4_id:
  .byte 4

action_4_name:
  .ascii "GRITAR"
  .ascii "e"

action_4_sensor_id:
  .byte 255  ; none

action_4_sensor_active:
  .byte 0  ; off

action_4_screen:
  .byte 255  ; screen id

action_4_cost:
  .byte 10

action_4_description:
  .ascii "El eco tarda demasiado en volver. Sientes que algo se mueve encima de ti. Debe ser tu imaginacion, te repites."
  .ascii "e"

; ── Action 5: LINTERNA ──────────────────────────
action_5_id:
  .byte 5

action_5_name:
  .ascii "LINTERNA"
  .ascii "e"

action_5_sensor_id:
  .byte 2  ; none

action_5_sensor_active:
  .byte 1  ; on

action_5_screen:
  .byte 255  ; screen id

action_5_cost:
  .byte 5

action_5_description:
  .ascii "La linterna se "
  .ascii "e"

; ── Action 6: EXPLORAR CAMINO ──────────────────────────
action_6_id:
  .byte 6

action_6_name:
  .ascii "EXPLORAR CAMINO"
  .ascii "e"

action_6_sensor_id:
  .byte 255  ; none

action_6_sensor_active:
  .byte 0  ; off

action_6_screen:
  .byte 9  ; screen id

action_6_cost:
  .byte 20

action_6_description:
  .ascii "Te dispones a explorar el camino que se abre en la oscuridad."
  .ascii "e"

; ── Action 7: VEO QUE CAE AGUA ──────────────────────────
action_7_id:
  .byte 7

action_7_name:
  .ascii "VEO QUE CAE AGUA"
  .ascii "e"

action_7_sensor_id:
  .byte 0  ; none

action_7_sensor_active:
  .byte 1  ; on

action_7_screen:
  .byte 2  ; screen id

action_7_cost:
  .byte 0

action_7_description:
  .ascii "Si es verdad, ves como se empieza a llenar la caverna."
  .ascii "e"

; ── Action 8: COMENZAR EL JUEGO ──────────────────────────
action_8_id:
  .byte 8

action_8_name:
  .ascii "COMENZAR EL JUEGO"
  .ascii "e"

action_8_sensor_id:
  .byte 3  ; none

action_8_sensor_active:
  .byte 1  ; on

action_8_screen:
  .byte 0  ; screen id

action_8_cost:
  .byte 0

action_8_description:
  .ascii "Y entras en la caverna misteriosa, el tiempo esta en tu contra"
  .ascii "e"

; ── Action 9: TERMINAR EL JUEGO ──────────────────────────
action_9_id:
  .byte 9

action_9_name:
  .ascii "TERMINAR EL JUEGO"
  .ascii "e"

action_9_sensor_id:
  .byte 4  ; none

action_9_sensor_active:
  .byte 0  ; off

action_9_screen:
  .byte 3  ; screen id

action_9_cost:
  .byte 0

action_9_description:
  .ascii ""
  .ascii "e"

; ── Action 10: EXPLORAR MARCAS ──────────────────────────
action_10_id:
  .byte 10

action_10_name:
  .ascii "EXPLORAR MARCAS"
  .ascii "e"

action_10_sensor_id:
  .byte 255  ; none

action_10_sensor_active:
  .byte 0  ; off

action_10_screen:
  .byte 7  ; screen id

action_10_cost:
  .byte 20

action_10_description:
  .ascii "Entre las marcas notas un extraño dibujo"
  .ascii "e"

; ── Action 11: FORZAR ENTRADA ──────────────────────────
action_11_id:
  .byte 11

action_11_name:
  .ascii "FORZAR ENTRADA"
  .ascii "e"

action_11_sensor_id:
  .byte 255  ; none

action_11_sensor_active:
  .byte 0  ; off

action_11_screen:
  .byte 8  ; screen id

action_11_cost:
  .byte 20

action_11_description:
  .ascii "Intentas mover las rocas de la entrada."
  .ascii "e"

; ── Action 12: VOLVER A MIRAR ADELANTE ──────────────────────────
action_12_id:
  .byte 12

action_12_name:
  .ascii "VOLVER A MIRAR ADELANTE"
  .ascii "e"

action_12_sensor_id:
  .byte 255  ; none

action_12_sensor_active:
  .byte 0  ; off

action_12_screen:
  .byte 2  ; screen id

action_12_cost:
  .byte 20

action_12_description:
  .ascii "Por un momento consideras que mover toneladas de rocas sin equipamiento indicado tal vez sea inutil. Explorar la caverna, aun sin conocerla, puede tener mejores resultados."
  .ascii "e"

; ── Total action count ──────────────────────────────────────
action_count:
  .byte 13
