import json
import os

JSON_FILE = "acs_actions.json"
ASM_FILE  = "acs_actions.asm"


def sanitize_id(name):
    """Turn an action name into a safe ASM label prefix (lowercase, spaces→_)."""
    return name.strip().lower().replace(" ", "_").replace("-", "_")


def to_asm(actions):
    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Actions — auto-generated by acs_actions_to_asm.py")
    lines.append("; ============================================================")
    lines.append("")

    # ── Action index table (pointer to the start of each action record) ──────
    lines.append("actions_index:")
    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        name   = act.get("Name", key)
        lines.append(f"  .word action_pointer_{act_id}  ; {name}")
    lines.append(f"actions_index_record_length:")
    lines.append(f"  .byte 2  ; each actions_index entry is 1 .word (2 bytes)")
    lines.append("")

    # ── Pointer table ────────────────────────────────────────
    lines.append("actions_pointers:")
    offset = 0

    # Captured from action 0 for offset labels emitted after all entries
    act0_name_offset        = None
    act0_description_offset = None
    act0_record_length      = None

    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        label  = f"action_{act_id}"
        name   = act.get("Name", key)

        start_offset = offset

        lines.append(f"action_pointer_{act_id}:")
        lines.append(f"  .word {label}_id            ; {name} id            [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_name          ; {name} name          [{offset},{offset+1}]") ; _nam = offset ; offset += 2
        lines.append(f"  .word {label}_sensor_id     ; {name} sensor_id     [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_sensor_active ; {name} sensor_active [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_cost          ; {name} cost          [{offset},{offset+1}]") ; offset += 2
        lines.append(f"  .word {label}_description   ; {name} description   [{offset},{offset+1}]") ; _dsc = offset ; offset += 2

        if index == 0:
            act0_name_offset        = _nam
            act0_description_offset = _dsc
            act0_record_length      = offset - start_offset  # 12 bytes (6 x .word)

    # -- Offset labels, placed after all action entries
    lines.append(f"action_name_offset:")
    lines.append(f"  .byte {act0_name_offset}  ; (byte of action_0_name in actions_pointers)")
    lines.append(f"action_description_offset:")
    lines.append(f"  .byte {act0_description_offset}  ; (byte of action_0_description in actions_pointers)")
    lines.append(f"action_record_length:")
    lines.append(f"  .byte {act0_record_length}  ; (total .word bytes per action record)")
    lines.append("")

    for index, (key, act) in enumerate(actions.items()):
        act_id     = act.get("ID",          str(index)).strip()
        label      = f"action_{act_id}"
        name_str   = act.get("Name",        "").replace('"', '\\"')
        desc_str   = act.get("Description", "").replace('"', '\\"')

        # Sensor ID — stored as SensorID in JSON, 255 = no sensor
        try:
            sensor_id_val = int(act.get("SensorID", 255))
        except (ValueError, TypeError):
            sensor_id_val = 255
        if sensor_id_val < 0 or sensor_id_val > 254:
            sensor_id_val = 255

        # SensorActive — boolean stored as SensorActive in JSON
        sensor_active_raw = act.get("SensorActive", False)
        if isinstance(sensor_active_raw, bool):
            sensor_active_val = 1 if sensor_active_raw else 0
        elif isinstance(sensor_active_raw, str):
            sensor_active_val = 1 if sensor_active_raw.lower() in ("true", "1", "yes") else 0
        else:
            sensor_active_val = 1 if sensor_active_raw else 0

        sensor_name_comment = act.get("Sensor", "none") or "none"

        lines.append(f"; ── Action {act_id}: {act.get('Name', key)} ──────────────────────────")

        # ID
        lines.append(f"{label}_id:")
        lines.append(f"  .byte {act_id}")
        lines.append("")

        # Name
        lines.append(f"{label}_name:")
        lines.append(f'  .ascii "{name_str}"')
        lines.append('  .ascii "e"')
        lines.append("")

        # Sensor ID
        lines.append(f"{label}_sensor_id:")
        lines.append(f"  .byte {sensor_id_val}  ; {sensor_name_comment}")
        lines.append("")

        # Sensor Active
        lines.append(f"{label}_sensor_active:")
        lines.append(f"  .byte {sensor_active_val}  ; {'on' if sensor_active_val else 'off'}")
        lines.append("")

        # Cost
        cost_val = act.get("Cost", 0)
        try:
            cost_val = int(cost_val)
            cost_val = max(0, min(256, cost_val))
        except (ValueError, TypeError):
            cost_val = 0
        lines.append(f"{label}_cost:")
        lines.append(f"  .byte {cost_val}")
        lines.append("")

        # Description
        lines.append(f"{label}_description:")
        lines.append(f'  .ascii "{desc_str}"')
        lines.append('  .ascii "e"')
        lines.append("")

    # ── Action count constant ─────────────────────────────────
    lines.append("; ── Total action count ──────────────────────────────────────")
    lines.append("action_count:")
    lines.append(f"  .byte {len(actions)}")
    lines.append("")

    return "\n".join(lines)


def main():
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found. Run the ACS editor first.")
        return

    with open(JSON_FILE, "r", encoding="utf-8") as f:
        actions = json.load(f)

    if not actions:
        print("[WARNING] No actions found in the JSON file.")
        return

    actions = dict(sorted(actions.items(), key=lambda item: int(item[1].get("ID", 0))))

    asm = to_asm(actions)

    with open(ASM_FILE, "w", encoding="utf-8") as f:
        f.write(asm)

    print(f"[OK] Generated '{ASM_FILE}' with {len(actions)} action(s).")
    print("-" * 50)
    print(asm)


if __name__ == "__main__":
    main()