; ============================================================
;  ACS Screens — auto-generated by acs_screens_to_asm.py
; ============================================================

screens_index:
  .word screen_pointers_0  ; s1s1
  .word screen_pointers_1  ; s1s2
  .word screen_pointers_2  ; s1s3
  .word screen_pointers_254  ; startScreen
screens_index_record_length:
  .byte 2  ; each screens_index entry is 1 .word (2 bytes)

screens_pointers:
screen_pointers_0:
  .word screen_0_id                ; s1s1 id                [0,1]
  .word screen_0_name              ; s1s1 name              [2,3]
  .word screen_0_north             ; s1s1 north             [4,5]
  .word screen_0_south             ; s1s1 south             [6,7]
  .word screen_0_east              ; s1s1 east              [8,9]
  .word screen_0_west              ; s1s1 west              [10,11]
  .word screen_0_puzzle1           ; s1s1 puzzle1           [12,13]
  .word screen_0_puzzle2           ; s1s1 puzzle2           [14,15]
  .word screen_0_action1           ; s1s1 action1           [16,17]
  .word screen_0_action2           ; s1s1 action2           [18,19]
  .word screen_0_action3           ; s1s1 action3           [20,21]
  .word screen_0_action4           ; s1s1 action4           [22,23]
  .word screen_0_action5           ; s1s1 action5           [24,25]
  .word screen_0_action6           ; s1s1 action6           [26,27]
  .word screen_0_description       ; s1s1 description       [28,29]
  .word screen_0_ascii             ; s1s1 ascii             [30,31]
  .word screen_0_flashlight_on     ; s1s1 flashlight_on     [32,33]
  .word screen_0_flashlight_off    ; s1s1 flashlight_off    [34,35]
screen_pointers_1:
  .word screen_1_id                ; s1s2 id                [36,37]
  .word screen_1_name              ; s1s2 name              [38,39]
  .word screen_1_north             ; s1s2 north             [40,41]
  .word screen_1_south             ; s1s2 south             [42,43]
  .word screen_1_east              ; s1s2 east              [44,45]
  .word screen_1_west              ; s1s2 west              [46,47]
  .word screen_1_puzzle1           ; s1s2 puzzle1           [48,49]
  .word screen_1_puzzle2           ; s1s2 puzzle2           [50,51]
  .word screen_1_action1           ; s1s2 action1           [52,53]
  .word screen_1_action2           ; s1s2 action2           [54,55]
  .word screen_1_action3           ; s1s2 action3           [56,57]
  .word screen_1_action4           ; s1s2 action4           [58,59]
  .word screen_1_action5           ; s1s2 action5           [60,61]
  .word screen_1_action6           ; s1s2 action6           [62,63]
  .word screen_1_description       ; s1s2 description       [64,65]
  .word screen_1_ascii             ; s1s2 ascii             [66,67]
  .word screen_1_flashlight_on     ; s1s2 flashlight_on     [68,69]
  .word screen_1_flashlight_off    ; s1s2 flashlight_off    [70,71]
screen_pointers_2:
  .word screen_2_id                ; s1s3 id                [72,73]
  .word screen_2_name              ; s1s3 name              [74,75]
  .word screen_2_north             ; s1s3 north             [76,77]
  .word screen_2_south             ; s1s3 south             [78,79]
  .word screen_2_east              ; s1s3 east              [80,81]
  .word screen_2_west              ; s1s3 west              [82,83]
  .word screen_2_puzzle1           ; s1s3 puzzle1           [84,85]
  .word screen_2_puzzle2           ; s1s3 puzzle2           [86,87]
  .word screen_2_action1           ; s1s3 action1           [88,89]
  .word screen_2_action2           ; s1s3 action2           [90,91]
  .word screen_2_action3           ; s1s3 action3           [92,93]
  .word screen_2_action4           ; s1s3 action4           [94,95]
  .word screen_2_action5           ; s1s3 action5           [96,97]
  .word screen_2_action6           ; s1s3 action6           [98,99]
  .word screen_2_description       ; s1s3 description       [100,101]
  .word screen_2_ascii             ; s1s3 ascii             [102,103]
  .word screen_2_flashlight_on     ; s1s3 flashlight_on     [104,105]
  .word screen_2_flashlight_off    ; s1s3 flashlight_off    [106,107]
screen_pointers_254:
  .word screen_254_id                ; startScreen id                [108,109]
  .word screen_254_name              ; startScreen name              [110,111]
  .word screen_254_north             ; startScreen north             [112,113]
  .word screen_254_south             ; startScreen south             [114,115]
  .word screen_254_east              ; startScreen east              [116,117]
  .word screen_254_west              ; startScreen west              [118,119]
  .word screen_254_puzzle1           ; startScreen puzzle1           [120,121]
  .word screen_254_puzzle2           ; startScreen puzzle2           [122,123]
  .word screen_254_action1           ; startScreen action1           [124,125]
  .word screen_254_action2           ; startScreen action2           [126,127]
  .word screen_254_action3           ; startScreen action3           [128,129]
  .word screen_254_action4           ; startScreen action4           [130,131]
  .word screen_254_action5           ; startScreen action5           [132,133]
  .word screen_254_action6           ; startScreen action6           [134,135]
  .word screen_254_description       ; startScreen description       [136,137]
  .word screen_254_ascii             ; startScreen ascii             [138,139]
  .word screen_254_flashlight_on     ; startScreen flashlight_on     [140,141]
  .word screen_254_flashlight_off    ; startScreen flashlight_off    [142,143]
screen_puzzle_offset:
  .byte 12  ; (byte of screen_0_puzzle1 in screens_pointers)
screen_action_offset:
  .byte 16  ; (byte of screen_0_action1 in screens_pointers)
screen_description_offset:
  .byte 28  ; (byte of screen_0_description in screens_pointers)
screen_ascii_offset:
  .byte 30  ; (byte of screen_0_ascii in screens_pointers)
screen_flashlight_on_offset:
  .byte 32  ; (byte of screen_0_flashlight_on in screens_pointers)
screen_flashlight_off_offset:
  .byte 34  ; (byte of screen_0_flashlight_off in screens_pointers)
screen_record_length:
  .byte 36  ; (total .word bytes per screen record)

; ── Screen 0: s1s1 ──────────────────────────
screen_0_id:
  .byte 0

screen_0_name:
  .ascii "s1s1"
  .ascii "e"

screen_0_north:
  .byte 255  ; none

screen_0_south:
  .byte 255  ; none

screen_0_east:
  .byte 1  ; s1s2

screen_0_west:
  .byte 255  ; none

screen_0_puzzle1:
  .byte 0  ; s1s1Levantarse

screen_0_puzzle2:
  .byte 255  ; none

screen_0_action1:
  .byte 0  ; LEVANTARSE

screen_0_action2:
  .byte 1  ; MIRAR ALREDEDOR

screen_0_action3:
  .byte 2  ; GRITAR POR AYUDA

screen_0_action4:
  .byte 255  ; none

screen_0_action5:
  .byte 255  ; none

screen_0_action6:
  .byte 255  ; none

screen_0_description:
  .ascii ""
  .ascii "e"

screen_0_ascii:
  .ascii ""
  .ascii "e"

screen_0_flashlight_on:
  .ascii "Despiertas sobre piedra húmeda. La caverna se cerro detrás de ti. Un derrumbe de rocas antiguas, pesadas, acomodadas como si el colapso hubiera sido final, no accidental. El frío no duele todavía. Sientes un constante goteo de agua, cada vez mas cerca de ti."
  .ascii "e"

screen_0_flashlight_off:
  .ascii "Despiertas sobre piedra húmeda. La caverna se cerro detrás de ti. Un derrumbe de rocas antiguas, pesadas, acomodadas como si el colapso hubiera sido final, no accidental. El frío no duele todavía. Sientes un constante goteo de agua, cada vez mas cerca de ti."
  .ascii "e"

; ── Screen 1: s1s2 ──────────────────────────
screen_1_id:
  .byte 1

screen_1_name:
  .ascii "s1s2"
  .ascii "e"

screen_1_north:
  .byte 255  ; none

screen_1_south:
  .byte 255  ; none

screen_1_east:
  .byte 255  ; none

screen_1_west:
  .byte 255  ; none

screen_1_puzzle1:
  .byte 255  ; none

screen_1_puzzle2:
  .byte 255  ; none

screen_1_action1:
  .byte 7  ; VEO QUE CAE AGUA

screen_1_action2:
  .byte 255  ; none

screen_1_action3:
  .byte 255  ; none

screen_1_action4:
  .byte 255  ; none

screen_1_action5:
  .byte 255  ; none

screen_1_action6:
  .byte 255  ; none

screen_1_description:
  .ascii ""
  .ascii "e"

screen_1_ascii:
  .ascii ""
  .ascii "e"

screen_1_flashlight_on:
  .ascii "Al levantarte, miras a tu alrededor. Ves que el agua gotea lenta, pero constantemente, inundando la caverna. Como si midiera el tiempo."
  .ascii "e"

screen_1_flashlight_off:
  .ascii "Al levantarte, miras a tu alrededor. Ves que el agua gotea lenta, pero constantemente, inundando la caverna. Como si midiera el tiempo."
  .ascii "e"

; ── Screen 2: s1s3 ──────────────────────────
screen_2_id:
  .byte 2

screen_2_name:
  .ascii "s1s3"
  .ascii "e"

screen_2_north:
  .byte 255  ; none

screen_2_south:
  .byte 255  ; none

screen_2_east:
  .byte 255  ; none

screen_2_west:
  .byte 255  ; none

screen_2_puzzle1:
  .byte 255  ; none

screen_2_puzzle2:
  .byte 255  ; none

screen_2_action1:
  .byte 255  ; none

screen_2_action2:
  .byte 255  ; none

screen_2_action3:
  .byte 255  ; none

screen_2_action4:
  .byte 255  ; none

screen_2_action5:
  .byte 255  ; none

screen_2_action6:
  .byte 255  ; none

screen_2_description:
  .ascii ""
  .ascii "e"

screen_2_ascii:
  .ascii ""
  .ascii "e"

screen_2_flashlight_on:
  .ascii "La caverna se abre en una cámara amplia pero baja. El techo parece aplastarte con su peso, estalactitas afiladas cuelgan peligrosamente del mismo. Las paredes son rugosas, húmedas al tacto, y reflejan una luz apagada que no tiene fuente clara. El aire es frío y estancado. Huele a roca mojada y a algo más viejo, casi orgánico. El suelo tiene marcas irregulares, como pasos interrumpidos en un camino que se pierde en la oscuridad."
  .ascii "e"

screen_2_flashlight_off:
  .ascii "La caverna se abre en una cámara amplia pero baja. El techo parece aplastarte con su peso, estalactitas afiladas cuelgan peligrosamente del mismo. Las paredes son rugosas, húmedas al tacto, y reflejan una luz apagada que no tiene fuente clara. El aire es frío y estancado. Huele a roca mojada y a algo más viejo, casi orgánico. El suelo tiene marcas irregulares, como pasos interrumpidos en un camino que se pierde en la oscuridad."
  .ascii "e"

; ── Screen 254: startScreen ──────────────────────────
screen_254_id:
  .byte 254

screen_254_name:
  .ascii "startScreen"
  .ascii "e"

screen_254_north:
  .byte 255  ; none

screen_254_south:
  .byte 255  ; none

screen_254_east:
  .byte 0  ; s1s1

screen_254_west:
  .byte 255  ; none

screen_254_puzzle1:
  .byte 255  ; none

screen_254_puzzle2:
  .byte 255  ; none

screen_254_action1:
  .byte 254  ; COMENZAR EL JUEGO

screen_254_action2:
  .byte 255  ; none

screen_254_action3:
  .byte 255  ; none

screen_254_action4:
  .byte 255  ; none

screen_254_action5:
  .byte 255  ; none

screen_254_action6:
  .byte 255  ; none

screen_254_description:
  .ascii "Bienvenido a la aventura gráfica más Espectacular del mundo"
  .ascii "e"

screen_254_ascii:
  .ascii ""
  .ascii "e"

screen_254_flashlight_on:
  .ascii ""
  .ascii "e"

screen_254_flashlight_off:
  .ascii ""
  .ascii "e"

; ── Total screen count ──────────────────────────────────────
screen_count:
  .byte 4
