; ============================================================
;  ACS Sensors — auto-generated by acs_parser_sensors.py
; ============================================================

sensors_index:
  .word sensor_pointer_0  ; water
  .word sensor_pointer_1  ; heart
  .word sensor_pointer_2  ; flashlight
  .word sensor_pointer_3  ; timer1minuto
sensors_index_record_length:
  .byte 2  ; each sensors_index entry is 1 .word (2 bytes)

sensors_pointers:
sensor_pointer_0:
  .word sensor_0_id     ; water id     [0,1]
  .word sensor_0_name   ; water name   [2,3]
  .word sensor_0_active ; water active [4,5]
sensor_pointer_1:
  .word sensor_1_id     ; heart id     [6,7]
  .word sensor_1_name   ; heart name   [8,9]
  .word sensor_1_active ; heart active [10,11]
sensor_pointer_2:
  .word sensor_2_id     ; flashlight id     [12,13]
  .word sensor_2_name   ; flashlight name   [14,15]
  .word sensor_2_active ; flashlight active [16,17]
sensor_pointer_3:
  .word sensor_3_id     ; timer1minuto id     [18,19]
  .word sensor_3_name   ; timer1minuto name   [20,21]
  .word sensor_3_active ; timer1minuto active [22,23]
sensor_name_offset:
  .byte 2  ; (byte of sensor_0_name in sensors_pointers)
sensor_record_length:
  .byte 6  ; (total .word bytes per sensor record)

; ── Sensor 0: water ──────────────────────────
sensor_0_id:
  .byte 0

sensor_0_name:
  .ascii "water"
  .ascii "e"

sensor_0_active:
  .byte 0  ; off

; ── Sensor 1: heart ──────────────────────────
sensor_1_id:
  .byte 1

sensor_1_name:
  .ascii "heart"
  .ascii "e"

sensor_1_active:
  .byte 0  ; off

; ── Sensor 2: flashlight ──────────────────────────
sensor_2_id:
  .byte 2

sensor_2_name:
  .ascii "flashlight"
  .ascii "e"

sensor_2_active:
  .byte 0  ; off

; ── Sensor 3: timer1minuto ──────────────────────────
sensor_3_id:
  .byte 3

sensor_3_name:
  .ascii "timer1minuto"
  .ascii "e"

sensor_3_active:
  .byte 0  ; off

; ── Total sensor count ──────────────────────────────────────
sensor_count:
  .byte 4
