import json
import os
from acs_compression import (
    build_shared_dictionary, emit_compressed_field_asm, compute_stats,
    ACTION_STRING_FIELDS as STRING_FIELDS
)

JSON_FILE = "acs_actions.json"
ASM_FILE  = "acs_actions.asm"


def ascii_lines(text):
    segments = text.split("\n")
    out = []
    for si, seg in enumerate(segments):
        if si < len(segments) - 1:
            seg += "\\n"
        while len(seg) > 80:
            out.append(f'  .ascii "{seg[:80]}"')
            seg = seg[80:]
        if seg:
            out.append(f'  .ascii "{seg}"')
    return out


def to_asm(actions):
    word_to_id, id_to_word, freq = build_shared_dictionary()

    lines = []
    lines.append("; ============================================================")
    lines.append(";  ACS Actions — auto-generated by acs_actions_to_asm.py")
    lines.append(";  Uses shared token dictionary from acs_screens.asm")
    lines.append("; ============================================================")
    lines.append("")

    # ── Action index table ────────────────────────────────────
    lines.append("actions_index:")
    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        name   = act.get("Name", key)
        lines.append(f"  .word action_pointer_{act_id}  ; {name}")
    lines.append(f"actions_index_record_length:")
    lines.append(f"  .byte 2")
    lines.append("")

    # ── Pointer table ────────────────────────────────────────
    lines.append("actions_pointers:")
    offset = 0
    act0_offsets = {}
    act0_record_length = None

    pointer_fields = [
        "id", "name", "alias", "sensor_id", "sensor_active", "screen",
        "cost", "enemy_probability", "reset_enemy_prob", "death_probability",
        "description", "desc_action_failed",
        "hide_water", "hide_fear", "hide_flashlight",
        "description_compressed", "desc_action_failed_compressed",
    ]

    for index, (key, act) in enumerate(actions.items()):
        act_id = act.get("ID", str(index)).strip()
        label  = f"action_{act_id}"
        name   = act.get("Name", key)
        start_offset = offset

        lines.append(f"action_pointer_{act_id}:")
        for fname in pointer_fields:
            pad = " " * max(0, 38 - len(fname))
            lines.append(f"  .word {label}_{fname}{pad}; {name} {fname} [{offset},{offset+1}]")
            if index == 0:
                act0_offsets[fname] = offset
            offset += 2

        if index == 0:
            act0_record_length = offset - start_offset

    # ── Offset labels ─────────────────────────────────────────
    for fname in pointer_fields[1:]:  # skip "id"
        lines.append(f"action_{fname}_offset:")
        lines.append(f"  .byte {act0_offsets[fname]}")
    lines.append(f"action_record_length:")
    lines.append(f"  .byte {act0_record_length}")
    lines.append("")

    # ── Per-action data ───────────────────────────────────────
    for index, (key, act) in enumerate(actions.items()):
        act_id   = act.get("ID", str(index)).strip()
        label    = f"action_{act_id}"
        name_str = act.get("Name", "").replace('"', '\\"')
        desc_str = act.get("Description", "").replace('"', '\\"')
        desc_raw = act.get("Description", "")
        desc_failed_str = act.get("DescriptionActionFailed", "").replace('"', '\\"')
        desc_failed_raw = act.get("DescriptionActionFailed", "")

        try:
            sensor_id_val = int(act.get("SensorID", 255))
        except (ValueError, TypeError):
            sensor_id_val = 255
        if sensor_id_val < 0 or sensor_id_val > 254:
            sensor_id_val = 255

        sensor_active_raw = act.get("SensorActive", False)
        if isinstance(sensor_active_raw, bool):
            sensor_active_val = 1 if sensor_active_raw else 0
        elif isinstance(sensor_active_raw, str):
            sensor_active_val = 1 if sensor_active_raw.lower() in ("true", "1", "yes") else 0
        else:
            sensor_active_val = 1 if sensor_active_raw else 0

        sensor_name_comment = act.get("Sensor", "none") or "none"

        lines.append(f"; ── Action {act_id}: {act.get('Name', key)} ──────────────────────────")

        lines.append(f"{label}_id:")
        lines.append(f"  .byte {act_id}")
        lines.append("")

        lines.append(f"{label}_name:")
        lines.extend(ascii_lines(name_str))
        lines.append("")

        alias_str = act.get("Alias", "").replace('"', '\\"')
        lines.append(f"{label}_alias:")
        lines.extend(ascii_lines(alias_str))
        lines.append("")

        lines.append(f"{label}_sensor_id:")
        lines.append(f"  .byte {sensor_id_val}  ; {sensor_name_comment}")
        lines.append("")

        lines.append(f"{label}_sensor_active:")
        lines.append(f"  .byte {sensor_active_val}  ; {'on' if sensor_active_val else 'off'}")
        lines.append("")

        try:
            screen_id_val = int(act.get("ScreenID", 255))
        except (ValueError, TypeError):
            screen_id_val = 255
        if screen_id_val < 0 or screen_id_val > 254:
            screen_id_val = 255
        lines.append(f"{label}_screen:")
        lines.append(f"  .byte {screen_id_val}  ; screen id")
        lines.append("")

        cost_val = act.get("Cost", 0)
        try:
            cost_val = max(0, min(256, int(cost_val)))
        except (ValueError, TypeError):
            cost_val = 0
        lines.append(f"{label}_cost:")
        lines.append(f"  .byte {cost_val}")
        lines.append("")

        try:
            enemy_prob_val = max(0, min(255, int(act.get("EnemyProbability", 0))))
        except (ValueError, TypeError):
            enemy_prob_val = 0
        lines.append(f"{label}_enemy_probability:")
        lines.append(f"  .byte {enemy_prob_val}")
        lines.append("")

        try:
            reset_enemy_val = 1 if int(act.get("ResetEnemyProbability", 0)) else 0
        except (ValueError, TypeError):
            reset_enemy_val = 0
        lines.append(f"{label}_reset_enemy_prob:")
        lines.append(f"  .byte {reset_enemy_val}  ; {'on' if reset_enemy_val else 'off'}")
        lines.append("")

        try:
            death_prob_val = max(0, min(255, int(act.get("DeathProbability", 0))))
        except (ValueError, TypeError):
            death_prob_val = 0
        lines.append(f"{label}_death_probability:")
        lines.append(f"  .byte {death_prob_val}")
        lines.append("")

        # Description (commented out original)
        lines.append(f"{label}_description:")
        for aline in ascii_lines(desc_str):
            lines.append(f"  ;{aline.lstrip()}")
        lines.append("")

        lines.extend(emit_compressed_field_asm(
            f"{label}_description_compressed", desc_raw, word_to_id, id_to_word))

        # Description Action Failed (commented out original)
        lines.append(f"{label}_desc_action_failed:")
        for aline in ascii_lines(desc_failed_str):
            lines.append(f"  ;{aline.lstrip()}")
        lines.append("")

        lines.extend(emit_compressed_field_asm(
            f"{label}_desc_action_failed_compressed", desc_failed_raw, word_to_id, id_to_word))

        try:
            hide_water_val = 1 if int(act.get("HideOnWaterLevelHigh", 0)) else 0
        except (ValueError, TypeError):
            hide_water_val = 0
        lines.append(f"{label}_hide_water:")
        lines.append(f"  .byte {hide_water_val}  ; {'on' if hide_water_val else 'off'}")
        lines.append("")

        try:
            hide_fear_val = 1 if int(act.get("HideOnFearLevelHigh", 0)) else 0
        except (ValueError, TypeError):
            hide_fear_val = 0
        lines.append(f"{label}_hide_fear:")
        lines.append(f"  .byte {hide_fear_val}  ; {'on' if hide_fear_val else 'off'}")
        lines.append("")

        try:
            hide_flashlight_val = 1 if int(act.get("HideWithFlashlightOff", 0)) else 0
        except (ValueError, TypeError):
            hide_flashlight_val = 0
        lines.append(f"{label}_hide_flashlight:")
        lines.append(f"  .byte {hide_flashlight_val}  ; {'on' if hide_flashlight_val else 'off'}")
        lines.append("")

    lines.append("action_count:")
    lines.append(f"  .byte {len(actions)}")
    lines.append("")

    texts = [act.get(f, "") for act in actions.values() for f in STRING_FIELDS if act.get(f, "").strip()]
    total_orig, total_comp, dict_bytes = compute_stats(texts, word_to_id)
    net = total_comp + dict_bytes
    savings = total_orig - net
    pct = (savings / total_orig * 100) if total_orig > 0 else 0
    lines.append("; ── Compression stats (actions only, shared dict) ──────────")
    lines.append(f";  Action original string bytes: {total_orig}")
    lines.append(f";  Action compressed bytes (1-byte IDs): {total_comp}")
    lines.append(f";  Dictionary overhead (shared, paid once): {dict_bytes}")
    lines.append(f";  Net: {net} vs {total_orig}")
    lines.append(f";  Savings: {savings} bytes ({pct:.1f}%)")
    lines.append("")

    return "\n".join(lines)


def main():
    if not os.path.exists(JSON_FILE):
        print(f"[ERROR] '{JSON_FILE}' not found.")
        return
    with open(JSON_FILE, "r", encoding="utf-8") as f:
        actions = json.load(f)
    if not actions:
        print("[WARNING] No actions found.")
        return
    actions = dict(sorted(actions.items(), key=lambda item: int(item[1].get("ID", 0))))
    asm = to_asm(actions)
    with open(ASM_FILE, "w", encoding="utf-8") as f:
        f.write(asm)
    print(f"[OK] Generated '{ASM_FILE}' with {len(actions)} action(s).")


if __name__ == "__main__":
    main()
