; ============================================================
;  ACS Screens — auto-generated by acs_screens_to_asm.py
; ============================================================

; ════════════════════════════════════════════════════════════
;  Token Dictionary — compressed string tokens
; ════════════════════════════════════════════════════════════

token_dict_index:
  .word token_0  ; [0] "Despiertas "
  .word token_1  ; [1] "sobre "
  .word token_2  ; [2] "piedra "
  .word token_3  ; [3] "húmeda.\n"
  .word token_4  ; [4] "La "
  .word token_5  ; [5] "caverna "
  .word token_6  ; [6] "se "
  .word token_7  ; [7] "cerro "
  .word token_8  ; [8] "detrás "
  .word token_9  ; [9] "de "
  .word token_10  ; [10] "ti. \n"
  .word token_11  ; [11] "Un "
  .word token_12  ; [12] "derrumbe "
  .word token_13  ; [13] "rocas "
  .word token_14  ; [14] "antiguas, "
  .word token_15  ; [15] "pesadas, "
  .word token_16  ; [16] "acomodadas "
  .word token_17  ; [17] "como "
  .word token_18  ; [18] "si "
  .word token_19  ; [19] "el "
  .word token_20  ; [20] "colapso "
  .word token_21  ; [21] "hubiera "
  .word token_22  ; [22] "sido "
  .word token_23  ; [23] "final, "
  .word token_24  ; [24] "no "
  .word token_25  ; [25] "accidental.\n"
  .word token_26  ; [26] "El "
  .word token_27  ; [27] "frío "
  .word token_28  ; [28] "duele "
  .word token_29  ; [29] "todavía. \n"
  .word token_30  ; [30] "Sientes "
  .word token_31  ; [31] "un "
  .word token_32  ; [32] "constante "
  .word token_33  ; [33] "goteo "
  .word token_34  ; [34] "agua, "
  .word token_35  ; [35] "cada "
  .word token_36  ; [36] "vez "
  .word token_37  ; [37] "mas "
  .word token_38  ; [38] "cerca "
  .word token_39  ; [39] "ti."
  .word token_40  ; [40] "Al "
  .word token_41  ; [41] "levantarte, "
  .word token_42  ; [42] "miras "
  .word token_43  ; [43] "a "
  .word token_44  ; [44] "tu "
  .word token_45  ; [45] "alrededor.\n"
  .word token_46  ; [46] "Ves "
  .word token_47  ; [47] "que "
  .word token_48  ; [48] "agua "
  .word token_49  ; [49] "gotea "
  .word token_50  ; [50] "lenta, "
  .word token_51  ; [51] "pero "
  .word token_52  ; [52] "constantemente, "
  .word token_53  ; [53] "inundando "
  .word token_54  ; [54] "la "
  .word token_55  ; [55] "caverna.\n"
  .word token_56  ; [56] "Como "
  .word token_57  ; [57] "midiera "
  .word token_58  ; [58] "tiempo."
  .word token_59  ; [59] "abre "
  .word token_60  ; [60] "en "
  .word token_61  ; [61] "una "
  .word token_62  ; [62] "cámara "
  .word token_63  ; [63] "amplia "
  .word token_64  ; [64] "baja. \n"
  .word token_65  ; [65] "techo "
  .word token_66  ; [66] "parece "
  .word token_67  ; [67] "aplastarte "
  .word token_68  ; [68] "con "
  .word token_69  ; [69] "su "
  .word token_70  ; [70] "peso, "
  .word token_71  ; [71] "estalactitas "
  .word token_72  ; [72] "afiladas "
  .word token_73  ; [73] "cuelgan "
  .word token_74  ; [74] "peligrosamente "
  .word token_75  ; [75] "del "
  .word token_76  ; [76] "mismo. \n"
  .word token_77  ; [77] "Las "
  .word token_78  ; [78] "paredes "
  .word token_79  ; [79] "son "
  .word token_80  ; [80] "rugosas, "
  .word token_81  ; [81] "húmedas "
  .word token_82  ; [82] "al "
  .word token_83  ; [83] "tacto, "
  .word token_84  ; [84] "y "
  .word token_85  ; [85] "reflejan "
  .word token_86  ; [86] "luz "
  .word token_87  ; [87] "apagada "
  .word token_88  ; [88] "tiene "
  .word token_89  ; [89] "fuente "
  .word token_90  ; [90] "clara. \n"
  .word token_91  ; [91] "aire "
  .word token_92  ; [92] "es "
  .word token_93  ; [93] "estancado. \n"
  .word token_94  ; [94] "Huele "
  .word token_95  ; [95] "roca "
  .word token_96  ; [96] "mojada "
  .word token_97  ; [97] "algo "
  .word token_98  ; [98] "más "
  .word token_99  ; [99] "viejo, "
  .word token_100  ; [100] "casi "
  .word token_101  ; [101] "orgánico. \n"
  .word token_102  ; [102] "suelo "
  .word token_103  ; [103] "marcas "
  .word token_104  ; [104] "irregulares, "
  .word token_105  ; [105] "pasos "
  .word token_106  ; [106] "interrumpidos "
  .word token_107  ; [107] "camino "
  .word token_108  ; [108] "pierde "
  .word token_109  ; [109] "oscuridad\n"
  .word token_110  ; [110] "Siente "
  .word token_111  ; [111] "o "
  .word token_112  ; [112] "alguien "
  .word token_113  ; [113] "puede "
  .word token_114  ; [114] "estar "
  .word token_115  ; [115] "acechando"
  .word token_116  ; [116] "Bienvenido "
  .word token_117  ; [117] "aventura "
  .word token_118  ; [118] "gráfica "
  .word token_119  ; [119] "Espectacular "
  .word token_120  ; [120] "mundo"
  .word token_121  ; [121] "era "
  .word token_122  ; [122] "hipnotico. "
  .word token_123  ; [123] "Gota, "
  .word token_124  ; [124] "pausa, "
  .word token_125  ; [125] "gota. "
  .word token_126  ; [126] "comenzo "
  .word token_127  ; [127] "entumecer "
  .word token_128  ; [128] "tus "
  .word token_129  ; [129] "extremidades "
  .word token_130  ; [130] "hasta "
  .word token_131  ; [131] "dejaste "
  .word token_132  ; [132] "sentirlas. "
  .word token_133  ; [133] "eterno "
  .word token_134  ; [134] "sueño "
  .word token_135  ; [135] "te "
  .word token_136  ; [136] "dio "
  .word token_137  ; [137] "bienvenida."
  .word token_138  ; [138] "Asi "
  .word token_139  ; [139] "terminas "
  .word token_140  ; [140] "dias "
  .word token_141  ; [141] "atrapado "
  .word token_142  ; [142] "Caverna"
  .word token_143  ; [143] "Entre "
  .word token_144  ; [144] "las "
  .word token_145  ; [145] "hay "
  .word token_146  ; [146] "rendijas "
  .word token_147  ; [147] "por "
  .word token_148  ; [148] "donde "
  .word token_149  ; [149] "entra "
  .word token_150  ; [150] "viciado, "
  .word token_151  ; [151] "ninguna "
  .word token_152  ; [152] "lo "
  .word token_153  ; [153] "bastante "
  .word token_154  ; [154] "grande "
  .word token_155  ; [155] "para "
  .word token_156  ; [156] "pasar. "
  .word token_157  ; [157] "Hay "
  .word token_158  ; [158] "intentado "
  .word token_159  ; [159] "moverlas "
  .word token_160  ; [160] "detenido "
  .word token_161  ; [161] "mitad "
  .word token_162  ; [162] "camino. "
  .word token_163  ; [163] "Tal "
  .word token_164  ; [164] "sea "
  .word token_165  ; [165] "opcion "
  .word token_166  ; [166] "volver "
  .word token_167  ; [167] "ahí, "
  .word token_168  ; [168] "idea "
  .word token_169  ; [169] "explorar "
  .word token_170  ; [170] "oscuras "
  .word token_171  ; [171] "tentadora."
  .word token_172  ; [172] "Este "
  .word token_173  ; [173] "PITFALL"
  .word token_174  ; [174] "comienza "
  .word token_175  ; [175] "temblar "
  .word token_176  ; [176] "entrada "
  .word token_177  ; [177] "empieza "
  .word token_178  ; [178] "desmoronarse "
  .word token_179  ; [179] "ti. "
  .word token_180  ; [180] "Lo "
  .word token_181  ; [181] "ultimo "
  .word token_182  ; [182] "piensas "
  .word token_183  ; [183] "estaban "
  .word token_184  ; [184] "sellando "
  .word token_185  ; [185] "salida. "
  .word token_186  ; [186] "Estaban "
  .word token_187  ; [187] "sosteniendo "
  .word token_188  ; [188] "resto\n"
  .word token_189  ; [189] "Haz "
  .word token_190  ; [190] "muerto"
  .word token_191  ; [191] "Luego "
  .word token_192  ; [192] "pasillo, "
  .word token_193  ; [193] "encuentras "
  .word token_194  ; [194] "sala "
  .word token_195  ; [195] "grande. "
  .word token_196  ; [196] "Dos "
  .word token_197  ; [197] "tuneles "
  .word token_198  ; [198] "abren "
  .word token_199  ; [199] "frente "
  .word token_200  ; [200] "Decidir "
  .word token_201  ; [201] "estas "
  .word token_202  ; [202] "condiciones "
  .word token_203  ; [203] "dificil, "
  .word token_204  ; [204] "necesario. "
  .word token_205  ; [205] "sigue "
  .word token_206  ; [206] "subiendo "
  .word token_207  ; [207] "lentamente."
  .word token_208  ; [208] "A "
  .word token_209  ; [209] "ciegas "
  .word token_210  ; [210] "tanteas "
  .word token_211  ; [211] "pared "
  .word token_212  ; [212] "acaba. "
  .word token_213  ; [213] "Tienes "
  .word token_214  ; [214] "sensacion "
  .word token_215  ; [215] "llegaste "
  .word token_216  ; [216] "lugar "
  .word token_217  ; [217] "espacioso. "
  .word token_218  ; [218] "Recorres "
  .word token_219  ; [219] "tientas "
  .word token_220  ; [220] "dos "
  .word token_221  ; [221] "grandes "
  .word token_222  ; [222] "huecos. "
  .word token_223  ; [223] "¿Tal "
  .word token_224  ; [224] "sean "
  .word token_225  ; [225] "tuneles?. "
  .word token_226  ; [226] "No "
  .word token_227  ; [227] "detienes "
  .word token_228  ; [228] "demasiado "
  .word token_229  ; [229] "pensarlo, "
  .word token_230  ; [230] "sientes "
  .word token_231  ; [231] "contacto "
  .word token_232  ; [232] "cuerpo."
  .word token_233  ; [233] "Tardaste "
  .word token_234  ; [234] "Muuuucho "
  .word token_235  ; [235] "quedaste "
  .word token_236  ; [236] "sin "
  .word token_237  ; [237] "tiempo....."
  .word token_238  ; [238] "enemigo "
  .word token_239  ; [239] "siempre "
  .word token_240  ; [240] "acechaba "
  .word token_241  ; [241] "atrapó, "
  .word token_242  ; [242] "este "
  .word token_243  ; [243] "fin"
  .word token_244  ; [244] "Tu "
  .word token_245  ; [245] "acción "
  .word token_246  ; [246] "tenía "
  .word token_247  ; [247] "gran "
  .word token_248  ; [248] "chance "
  .word token_249  ; [249] "fallar "
  .word token_250  ; [250] "falló. "

token_0:  ; "Despiertas "
  .ascii "Despiertas "
  .byte $00  ; end-of-token sentinel

token_1:  ; "sobre "
  .ascii "sobre "
  .byte $00  ; end-of-token sentinel

token_2:  ; "piedra "
  .ascii "piedra "
  .byte $00  ; end-of-token sentinel

token_3:  ; "húmeda.\n"
  .ascii "húmeda.\n"
  .byte $0a  ; \n
  .byte $00  ; end-of-token sentinel

token_4:  ; "La "
  .ascii "La "
  .byte $00  ; end-of-token sentinel

token_5:  ; "caverna "
  .ascii "caverna "
  .byte $00  ; end-of-token sentinel

token_6:  ; "se "
  .ascii "se "
  .byte $00  ; end-of-token sentinel

token_7:  ; "cerro "
  .ascii "cerro "
  .byte $00  ; end-of-token sentinel

token_8:  ; "detrás "
  .ascii "detrás "
  .byte $00  ; end-of-token sentinel

token_9:  ; "de "
  .ascii "de "
  .byte $00  ; end-of-token sentinel

token_10:  ; "ti. \n"
  .ascii "ti. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_11:  ; "Un "
  .ascii "Un "
  .byte $00  ; end-of-token sentinel

token_12:  ; "derrumbe "
  .ascii "derrumbe "
  .byte $00  ; end-of-token sentinel

token_13:  ; "rocas "
  .ascii "rocas "
  .byte $00  ; end-of-token sentinel

token_14:  ; "antiguas, "
  .ascii "antiguas, "
  .byte $00  ; end-of-token sentinel

token_15:  ; "pesadas, "
  .ascii "pesadas, "
  .byte $00  ; end-of-token sentinel

token_16:  ; "acomodadas "
  .ascii "acomodadas "
  .byte $00  ; end-of-token sentinel

token_17:  ; "como "
  .ascii "como "
  .byte $00  ; end-of-token sentinel

token_18:  ; "si "
  .ascii "si "
  .byte $00  ; end-of-token sentinel

token_19:  ; "el "
  .ascii "el "
  .byte $00  ; end-of-token sentinel

token_20:  ; "colapso "
  .ascii "colapso "
  .byte $00  ; end-of-token sentinel

token_21:  ; "hubiera "
  .ascii "hubiera "
  .byte $00  ; end-of-token sentinel

token_22:  ; "sido "
  .ascii "sido "
  .byte $00  ; end-of-token sentinel

token_23:  ; "final, "
  .ascii "final, "
  .byte $00  ; end-of-token sentinel

token_24:  ; "no "
  .ascii "no "
  .byte $00  ; end-of-token sentinel

token_25:  ; "accidental.\n"
  .ascii "accidental."
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_26:  ; "El "
  .ascii "El "
  .byte $00  ; end-of-token sentinel

token_27:  ; "frío "
  .ascii "frío "
  .byte $00  ; end-of-token sentinel

token_28:  ; "duele "
  .ascii "duele "
  .byte $00  ; end-of-token sentinel

token_29:  ; "todavía. \n"
  .ascii "todavía. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_30:  ; "Sientes "
  .ascii "Sientes "
  .byte $00  ; end-of-token sentinel

token_31:  ; "un "
  .ascii "un "
  .byte $00  ; end-of-token sentinel

token_32:  ; "constante "
  .ascii "constante "
  .byte $00  ; end-of-token sentinel

token_33:  ; "goteo "
  .ascii "goteo "
  .byte $00  ; end-of-token sentinel

token_34:  ; "agua, "
  .ascii "agua, "
  .byte $00  ; end-of-token sentinel

token_35:  ; "cada "
  .ascii "cada "
  .byte $00  ; end-of-token sentinel

token_36:  ; "vez "
  .ascii "vez "
  .byte $00  ; end-of-token sentinel

token_37:  ; "mas "
  .ascii "mas "
  .byte $00  ; end-of-token sentinel

token_38:  ; "cerca "
  .ascii "cerca "
  .byte $00  ; end-of-token sentinel

token_39:  ; "ti."
  .ascii "ti."
  .byte $00  ; end-of-token sentinel

token_40:  ; "Al "
  .ascii "Al "
  .byte $00  ; end-of-token sentinel

token_41:  ; "levantarte, "
  .ascii "levantarte, "
  .byte $00  ; end-of-token sentinel

token_42:  ; "miras "
  .ascii "miras "
  .byte $00  ; end-of-token sentinel

token_43:  ; "a "
  .ascii "a "
  .byte $00  ; end-of-token sentinel

token_44:  ; "tu "
  .ascii "tu "
  .byte $00  ; end-of-token sentinel

token_45:  ; "alrededor.\n"
  .ascii "alrededor."
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_46:  ; "Ves "
  .ascii "Ves "
  .byte $00  ; end-of-token sentinel

token_47:  ; "que "
  .ascii "que "
  .byte $00  ; end-of-token sentinel

token_48:  ; "agua "
  .ascii "agua "
  .byte $00  ; end-of-token sentinel

token_49:  ; "gotea "
  .ascii "gotea "
  .byte $00  ; end-of-token sentinel

token_50:  ; "lenta, "
  .ascii "lenta, "
  .byte $00  ; end-of-token sentinel

token_51:  ; "pero "
  .ascii "pero "
  .byte $00  ; end-of-token sentinel

token_52:  ; "constantemente, "
  .ascii "constantemente, "
  .byte $00  ; end-of-token sentinel

token_53:  ; "inundando "
  .ascii "inundando "
  .byte $00  ; end-of-token sentinel

token_54:  ; "la "
  .ascii "la "
  .byte $00  ; end-of-token sentinel

token_55:  ; "caverna.\n"
  .ascii "caverna."
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_56:  ; "Como "
  .ascii "Como "
  .byte $00  ; end-of-token sentinel

token_57:  ; "midiera "
  .ascii "midiera "
  .byte $00  ; end-of-token sentinel

token_58:  ; "tiempo."
  .ascii "tiempo."
  .byte $00  ; end-of-token sentinel

token_59:  ; "abre "
  .ascii "abre "
  .byte $00  ; end-of-token sentinel

token_60:  ; "en "
  .ascii "en "
  .byte $00  ; end-of-token sentinel

token_61:  ; "una "
  .ascii "una "
  .byte $00  ; end-of-token sentinel

token_62:  ; "cámara "
  .ascii "cámara "
  .byte $00  ; end-of-token sentinel

token_63:  ; "amplia "
  .ascii "amplia "
  .byte $00  ; end-of-token sentinel

token_64:  ; "baja. \n"
  .ascii "baja. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_65:  ; "techo "
  .ascii "techo "
  .byte $00  ; end-of-token sentinel

token_66:  ; "parece "
  .ascii "parece "
  .byte $00  ; end-of-token sentinel

token_67:  ; "aplastarte "
  .ascii "aplastarte "
  .byte $00  ; end-of-token sentinel

token_68:  ; "con "
  .ascii "con "
  .byte $00  ; end-of-token sentinel

token_69:  ; "su "
  .ascii "su "
  .byte $00  ; end-of-token sentinel

token_70:  ; "peso, "
  .ascii "peso, "
  .byte $00  ; end-of-token sentinel

token_71:  ; "estalactitas "
  .ascii "estalactitas "
  .byte $00  ; end-of-token sentinel

token_72:  ; "afiladas "
  .ascii "afiladas "
  .byte $00  ; end-of-token sentinel

token_73:  ; "cuelgan "
  .ascii "cuelgan "
  .byte $00  ; end-of-token sentinel

token_74:  ; "peligrosamente "
  .ascii "peligrosamente "
  .byte $00  ; end-of-token sentinel

token_75:  ; "del "
  .ascii "del "
  .byte $00  ; end-of-token sentinel

token_76:  ; "mismo. \n"
  .ascii "mismo. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_77:  ; "Las "
  .ascii "Las "
  .byte $00  ; end-of-token sentinel

token_78:  ; "paredes "
  .ascii "paredes "
  .byte $00  ; end-of-token sentinel

token_79:  ; "son "
  .ascii "son "
  .byte $00  ; end-of-token sentinel

token_80:  ; "rugosas, "
  .ascii "rugosas, "
  .byte $00  ; end-of-token sentinel

token_81:  ; "húmedas "
  .ascii "húmedas "
  .byte $00  ; end-of-token sentinel

token_82:  ; "al "
  .ascii "al "
  .byte $00  ; end-of-token sentinel

token_83:  ; "tacto, "
  .ascii "tacto, "
  .byte $00  ; end-of-token sentinel

token_84:  ; "y "
  .ascii "y "
  .byte $00  ; end-of-token sentinel

token_85:  ; "reflejan "
  .ascii "reflejan "
  .byte $00  ; end-of-token sentinel

token_86:  ; "luz "
  .ascii "luz "
  .byte $00  ; end-of-token sentinel

token_87:  ; "apagada "
  .ascii "apagada "
  .byte $00  ; end-of-token sentinel

token_88:  ; "tiene "
  .ascii "tiene "
  .byte $00  ; end-of-token sentinel

token_89:  ; "fuente "
  .ascii "fuente "
  .byte $00  ; end-of-token sentinel

token_90:  ; "clara. \n"
  .ascii "clara. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_91:  ; "aire "
  .ascii "aire "
  .byte $00  ; end-of-token sentinel

token_92:  ; "es "
  .ascii "es "
  .byte $00  ; end-of-token sentinel

token_93:  ; "estancado. \n"
  .ascii "estancado. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_94:  ; "Huele "
  .ascii "Huele "
  .byte $00  ; end-of-token sentinel

token_95:  ; "roca "
  .ascii "roca "
  .byte $00  ; end-of-token sentinel

token_96:  ; "mojada "
  .ascii "mojada "
  .byte $00  ; end-of-token sentinel

token_97:  ; "algo "
  .ascii "algo "
  .byte $00  ; end-of-token sentinel

token_98:  ; "más "
  .ascii "más "
  .byte $00  ; end-of-token sentinel

token_99:  ; "viejo, "
  .ascii "viejo, "
  .byte $00  ; end-of-token sentinel

token_100:  ; "casi "
  .ascii "casi "
  .byte $00  ; end-of-token sentinel

token_101:  ; "orgánico. \n"
  .ascii "orgánico. "
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_102:  ; "suelo "
  .ascii "suelo "
  .byte $00  ; end-of-token sentinel

token_103:  ; "marcas "
  .ascii "marcas "
  .byte $00  ; end-of-token sentinel

token_104:  ; "irregulares, "
  .ascii "irregulares, "
  .byte $00  ; end-of-token sentinel

token_105:  ; "pasos "
  .ascii "pasos "
  .byte $00  ; end-of-token sentinel

token_106:  ; "interrumpidos "
  .ascii "interrumpidos "
  .byte $00  ; end-of-token sentinel

token_107:  ; "camino "
  .ascii "camino "
  .byte $00  ; end-of-token sentinel

token_108:  ; "pierde "
  .ascii "pierde "
  .byte $00  ; end-of-token sentinel

token_109:  ; "oscuridad\n"
  .ascii "oscuridad"
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_110:  ; "Siente "
  .ascii "Siente "
  .byte $00  ; end-of-token sentinel

token_111:  ; "o "
  .ascii "o "
  .byte $00  ; end-of-token sentinel

token_112:  ; "alguien "
  .ascii "alguien "
  .byte $00  ; end-of-token sentinel

token_113:  ; "puede "
  .ascii "puede "
  .byte $00  ; end-of-token sentinel

token_114:  ; "estar "
  .ascii "estar "
  .byte $00  ; end-of-token sentinel

token_115:  ; "acechando"
  .ascii "acechando"
  .byte $00  ; end-of-token sentinel

token_116:  ; "Bienvenido "
  .ascii "Bienvenido "
  .byte $00  ; end-of-token sentinel

token_117:  ; "aventura "
  .ascii "aventura "
  .byte $00  ; end-of-token sentinel

token_118:  ; "gráfica "
  .ascii "gráfica "
  .byte $00  ; end-of-token sentinel

token_119:  ; "Espectacular "
  .ascii "Espectacular "
  .byte $00  ; end-of-token sentinel

token_120:  ; "mundo"
  .ascii "mundo"
  .byte $00  ; end-of-token sentinel

token_121:  ; "era "
  .ascii "era "
  .byte $00  ; end-of-token sentinel

token_122:  ; "hipnotico. "
  .ascii "hipnotico. "
  .byte $00  ; end-of-token sentinel

token_123:  ; "Gota, "
  .ascii "Gota, "
  .byte $00  ; end-of-token sentinel

token_124:  ; "pausa, "
  .ascii "pausa, "
  .byte $00  ; end-of-token sentinel

token_125:  ; "gota. "
  .ascii "gota. "
  .byte $00  ; end-of-token sentinel

token_126:  ; "comenzo "
  .ascii "comenzo "
  .byte $00  ; end-of-token sentinel

token_127:  ; "entumecer "
  .ascii "entumecer "
  .byte $00  ; end-of-token sentinel

token_128:  ; "tus "
  .ascii "tus "
  .byte $00  ; end-of-token sentinel

token_129:  ; "extremidades "
  .ascii "extremidades "
  .byte $00  ; end-of-token sentinel

token_130:  ; "hasta "
  .ascii "hasta "
  .byte $00  ; end-of-token sentinel

token_131:  ; "dejaste "
  .ascii "dejaste "
  .byte $00  ; end-of-token sentinel

token_132:  ; "sentirlas. "
  .ascii "sentirlas. "
  .byte $00  ; end-of-token sentinel

token_133:  ; "eterno "
  .ascii "eterno "
  .byte $00  ; end-of-token sentinel

token_134:  ; "sueño "
  .ascii "sueño "
  .byte $00  ; end-of-token sentinel

token_135:  ; "te "
  .ascii "te "
  .byte $00  ; end-of-token sentinel

token_136:  ; "dio "
  .ascii "dio "
  .byte $00  ; end-of-token sentinel

token_137:  ; "bienvenida."
  .ascii "bienvenida."
  .byte $00  ; end-of-token sentinel

token_138:  ; "Asi "
  .ascii "Asi "
  .byte $00  ; end-of-token sentinel

token_139:  ; "terminas "
  .ascii "terminas "
  .byte $00  ; end-of-token sentinel

token_140:  ; "dias "
  .ascii "dias "
  .byte $00  ; end-of-token sentinel

token_141:  ; "atrapado "
  .ascii "atrapado "
  .byte $00  ; end-of-token sentinel

token_142:  ; "Caverna"
  .ascii "Caverna"
  .byte $00  ; end-of-token sentinel

token_143:  ; "Entre "
  .ascii "Entre "
  .byte $00  ; end-of-token sentinel

token_144:  ; "las "
  .ascii "las "
  .byte $00  ; end-of-token sentinel

token_145:  ; "hay "
  .ascii "hay "
  .byte $00  ; end-of-token sentinel

token_146:  ; "rendijas "
  .ascii "rendijas "
  .byte $00  ; end-of-token sentinel

token_147:  ; "por "
  .ascii "por "
  .byte $00  ; end-of-token sentinel

token_148:  ; "donde "
  .ascii "donde "
  .byte $00  ; end-of-token sentinel

token_149:  ; "entra "
  .ascii "entra "
  .byte $00  ; end-of-token sentinel

token_150:  ; "viciado, "
  .ascii "viciado, "
  .byte $00  ; end-of-token sentinel

token_151:  ; "ninguna "
  .ascii "ninguna "
  .byte $00  ; end-of-token sentinel

token_152:  ; "lo "
  .ascii "lo "
  .byte $00  ; end-of-token sentinel

token_153:  ; "bastante "
  .ascii "bastante "
  .byte $00  ; end-of-token sentinel

token_154:  ; "grande "
  .ascii "grande "
  .byte $00  ; end-of-token sentinel

token_155:  ; "para "
  .ascii "para "
  .byte $00  ; end-of-token sentinel

token_156:  ; "pasar. "
  .ascii "pasar. "
  .byte $00  ; end-of-token sentinel

token_157:  ; "Hay "
  .ascii "Hay "
  .byte $00  ; end-of-token sentinel

token_158:  ; "intentado "
  .ascii "intentado "
  .byte $00  ; end-of-token sentinel

token_159:  ; "moverlas "
  .ascii "moverlas "
  .byte $00  ; end-of-token sentinel

token_160:  ; "detenido "
  .ascii "detenido "
  .byte $00  ; end-of-token sentinel

token_161:  ; "mitad "
  .ascii "mitad "
  .byte $00  ; end-of-token sentinel

token_162:  ; "camino. "
  .ascii "camino. "
  .byte $00  ; end-of-token sentinel

token_163:  ; "Tal "
  .ascii "Tal "
  .byte $00  ; end-of-token sentinel

token_164:  ; "sea "
  .ascii "sea "
  .byte $00  ; end-of-token sentinel

token_165:  ; "opcion "
  .ascii "opcion "
  .byte $00  ; end-of-token sentinel

token_166:  ; "volver "
  .ascii "volver "
  .byte $00  ; end-of-token sentinel

token_167:  ; "ahí, "
  .ascii "ahí, "
  .byte $00  ; end-of-token sentinel

token_168:  ; "idea "
  .ascii "idea "
  .byte $00  ; end-of-token sentinel

token_169:  ; "explorar "
  .ascii "explorar "
  .byte $00  ; end-of-token sentinel

token_170:  ; "oscuras "
  .ascii "oscuras "
  .byte $00  ; end-of-token sentinel

token_171:  ; "tentadora."
  .ascii "tentadora."
  .byte $00  ; end-of-token sentinel

token_172:  ; "Este "
  .ascii "Este "
  .byte $00  ; end-of-token sentinel

token_173:  ; "PITFALL"
  .ascii "PITFALL"
  .byte $00  ; end-of-token sentinel

token_174:  ; "comienza "
  .ascii "comienza "
  .byte $00  ; end-of-token sentinel

token_175:  ; "temblar "
  .ascii "temblar "
  .byte $00  ; end-of-token sentinel

token_176:  ; "entrada "
  .ascii "entrada "
  .byte $00  ; end-of-token sentinel

token_177:  ; "empieza "
  .ascii "empieza "
  .byte $00  ; end-of-token sentinel

token_178:  ; "desmoronarse "
  .ascii "desmoronarse "
  .byte $00  ; end-of-token sentinel

token_179:  ; "ti. "
  .ascii "ti. "
  .byte $00  ; end-of-token sentinel

token_180:  ; "Lo "
  .ascii "Lo "
  .byte $00  ; end-of-token sentinel

token_181:  ; "ultimo "
  .ascii "ultimo "
  .byte $00  ; end-of-token sentinel

token_182:  ; "piensas "
  .ascii "piensas "
  .byte $00  ; end-of-token sentinel

token_183:  ; "estaban "
  .ascii "estaban "
  .byte $00  ; end-of-token sentinel

token_184:  ; "sellando "
  .ascii "sellando "
  .byte $00  ; end-of-token sentinel

token_185:  ; "salida. "
  .ascii "salida. "
  .byte $00  ; end-of-token sentinel

token_186:  ; "Estaban "
  .ascii "Estaban "
  .byte $00  ; end-of-token sentinel

token_187:  ; "sosteniendo "
  .ascii "sosteniendo "
  .byte $00  ; end-of-token sentinel

token_188:  ; "resto\n"
  .ascii "resto"
  .byte $0A  ; \n
  .byte $00  ; end-of-token sentinel

token_189:  ; "Haz "
  .ascii "Haz "
  .byte $00  ; end-of-token sentinel

token_190:  ; "muerto"
  .ascii "muerto"
  .byte $00  ; end-of-token sentinel

token_191:  ; "Luego "
  .ascii "Luego "
  .byte $00  ; end-of-token sentinel

token_192:  ; "pasillo, "
  .ascii "pasillo, "
  .byte $00  ; end-of-token sentinel

token_193:  ; "encuentras "
  .ascii "encuentras "
  .byte $00  ; end-of-token sentinel

token_194:  ; "sala "
  .ascii "sala "
  .byte $00  ; end-of-token sentinel

token_195:  ; "grande. "
  .ascii "grande. "
  .byte $00  ; end-of-token sentinel

token_196:  ; "Dos "
  .ascii "Dos "
  .byte $00  ; end-of-token sentinel

token_197:  ; "tuneles "
  .ascii "tuneles "
  .byte $00  ; end-of-token sentinel

token_198:  ; "abren "
  .ascii "abren "
  .byte $00  ; end-of-token sentinel

token_199:  ; "frente "
  .ascii "frente "
  .byte $00  ; end-of-token sentinel

token_200:  ; "Decidir "
  .ascii "Decidir "
  .byte $00  ; end-of-token sentinel

token_201:  ; "estas "
  .ascii "estas "
  .byte $00  ; end-of-token sentinel

token_202:  ; "condiciones "
  .ascii "condiciones "
  .byte $00  ; end-of-token sentinel

token_203:  ; "dificil, "
  .ascii "dificil, "
  .byte $00  ; end-of-token sentinel

token_204:  ; "necesario. "
  .ascii "necesario. "
  .byte $00  ; end-of-token sentinel

token_205:  ; "sigue "
  .ascii "sigue "
  .byte $00  ; end-of-token sentinel

token_206:  ; "subiendo "
  .ascii "subiendo "
  .byte $00  ; end-of-token sentinel

token_207:  ; "lentamente."
  .ascii "lentamente."
  .byte $00  ; end-of-token sentinel

token_208:  ; "A "
  .ascii "A "
  .byte $00  ; end-of-token sentinel

token_209:  ; "ciegas "
  .ascii "ciegas "
  .byte $00  ; end-of-token sentinel

token_210:  ; "tanteas "
  .ascii "tanteas "
  .byte $00  ; end-of-token sentinel

token_211:  ; "pared "
  .ascii "pared "
  .byte $00  ; end-of-token sentinel

token_212:  ; "acaba. "
  .ascii "acaba. "
  .byte $00  ; end-of-token sentinel

token_213:  ; "Tienes "
  .ascii "Tienes "
  .byte $00  ; end-of-token sentinel

token_214:  ; "sensacion "
  .ascii "sensacion "
  .byte $00  ; end-of-token sentinel

token_215:  ; "llegaste "
  .ascii "llegaste "
  .byte $00  ; end-of-token sentinel

token_216:  ; "lugar "
  .ascii "lugar "
  .byte $00  ; end-of-token sentinel

token_217:  ; "espacioso. "
  .ascii "espacioso. "
  .byte $00  ; end-of-token sentinel

token_218:  ; "Recorres "
  .ascii "Recorres "
  .byte $00  ; end-of-token sentinel

token_219:  ; "tientas "
  .ascii "tientas "
  .byte $00  ; end-of-token sentinel

token_220:  ; "dos "
  .ascii "dos "
  .byte $00  ; end-of-token sentinel

token_221:  ; "grandes "
  .ascii "grandes "
  .byte $00  ; end-of-token sentinel

token_222:  ; "huecos. "
  .ascii "huecos. "
  .byte $00  ; end-of-token sentinel

token_223:  ; "¿Tal "
  .ascii "¿Tal "
  .byte $00  ; end-of-token sentinel

token_224:  ; "sean "
  .ascii "sean "
  .byte $00  ; end-of-token sentinel

token_225:  ; "tuneles?. "
  .ascii "tuneles?. "
  .byte $00  ; end-of-token sentinel

token_226:  ; "No "
  .ascii "No "
  .byte $00  ; end-of-token sentinel

token_227:  ; "detienes "
  .ascii "detienes "
  .byte $00  ; end-of-token sentinel

token_228:  ; "demasiado "
  .ascii "demasiado "
  .byte $00  ; end-of-token sentinel

token_229:  ; "pensarlo, "
  .ascii "pensarlo, "
  .byte $00  ; end-of-token sentinel

token_230:  ; "sientes "
  .ascii "sientes "
  .byte $00  ; end-of-token sentinel

token_231:  ; "contacto "
  .ascii "contacto "
  .byte $00  ; end-of-token sentinel

token_232:  ; "cuerpo."
  .ascii "cuerpo."
  .byte $00  ; end-of-token sentinel

token_233:  ; "Tardaste "
  .ascii "Tardaste "
  .byte $00  ; end-of-token sentinel

token_234:  ; "Muuuucho "
  .ascii "Muuuucho "
  .byte $00  ; end-of-token sentinel

token_235:  ; "quedaste "
  .ascii "quedaste "
  .byte $00  ; end-of-token sentinel

token_236:  ; "sin "
  .ascii "sin "
  .byte $00  ; end-of-token sentinel

token_237:  ; "tiempo....."
  .ascii "tiempo....."
  .byte $00  ; end-of-token sentinel

token_238:  ; "enemigo "
  .ascii "enemigo "
  .byte $00  ; end-of-token sentinel

token_239:  ; "siempre "
  .ascii "siempre "
  .byte $00  ; end-of-token sentinel

token_240:  ; "acechaba "
  .ascii "acechaba "
  .byte $00  ; end-of-token sentinel

token_241:  ; "atrapó, "
  .ascii "atrapó, "
  .byte $00  ; end-of-token sentinel

token_242:  ; "este "
  .ascii "este "
  .byte $00  ; end-of-token sentinel

token_243:  ; "fin"
  .ascii "fin"
  .byte $00  ; end-of-token sentinel

token_244:  ; "Tu "
  .ascii "Tu "
  .byte $00  ; end-of-token sentinel

token_245:  ; "acción "
  .ascii "acción "
  .byte $00  ; end-of-token sentinel

token_246:  ; "tenía "
  .ascii "tenía "
  .byte $00  ; end-of-token sentinel

token_247:  ; "gran "
  .ascii "gran "
  .byte $00  ; end-of-token sentinel

token_248:  ; "chance "
  .ascii "chance "
  .byte $00  ; end-of-token sentinel

token_249:  ; "fallar "
  .ascii "fallar "
  .byte $00  ; end-of-token sentinel

token_250:  ; "falló. "
  .ascii "falló. "
  .byte $00  ; end-of-token sentinel

token_dict_count:
  .byte 251

screens_index:
  .word screen_pointers_0  ; s1s1
  .word screen_pointers_1  ; s1s2
  .word screen_pointers_2  ; s1s3
  .word screen_pointers_3  ; startScreen
  .word screen_pointers_4  ; endScreens1s1
  .word screen_pointers_5  ; endScreenDefault
  .word screen_pointers_6  ; s1s4
  .word screen_pointers_7  ; s1s5
  .word screen_pointers_8  ; endScreens1s4
  .word screen_pointers_9  ; s2s1
  .word screen_pointers_10  ; EndScreenSimulationTimeisUp
  .word screen_pointers_11  ; endScreenByEnemy
  .word screen_pointers_12  ; endScreenByActionFailed
screens_index_record_length:
  .byte 2  ; each screens_index entry is 1 .word (2 bytes)

screens_pointers:
screen_pointers_0:
  .word screen_0_id                          ; s1s1 id                          [0,1]
  .word screen_0_name                        ; s1s1 name                        [2,3]
  .word screen_0_action1                     ; s1s1 action1                     [4,5]
  .word screen_0_action2                     ; s1s1 action2                     [6,7]
  .word screen_0_action3                     ; s1s1 action3                     [8,9]
  .word screen_0_action4                     ; s1s1 action4                     [10,11]
  .word screen_0_description                 ; s1s1 description                 [12,13]
  .word screen_0_ascii                       ; s1s1 ascii                       [14,15]
  .word screen_0_flashlight_on               ; s1s1 flashlight_on               [16,17]
  .word screen_0_flashlight_off              ; s1s1 flashlight_off              [18,19]
  .word screen_0_enemy_probability           ; s1s1 enemy_probability           [20,21]
  .word screen_0_is_secret_screen            ; s1s1 is_secret_screen            [22,23]
  .word screen_0_is_end_screen               ; s1s1 is_end_screen               [24,25]
  .word screen_0_description_compressed      ; s1s1 description_compressed      [26,27]
  .word screen_0_flashlight_on_compressed    ; s1s1 flashlight_on_compressed    [28,29]
  .word screen_0_flashlight_off_compressed   ; s1s1 flashlight_off_compressed   [30,31]
screen_pointers_1:
  .word screen_1_id                          ; s1s2 id                          [32,33]
  .word screen_1_name                        ; s1s2 name                        [34,35]
  .word screen_1_action1                     ; s1s2 action1                     [36,37]
  .word screen_1_action2                     ; s1s2 action2                     [38,39]
  .word screen_1_action3                     ; s1s2 action3                     [40,41]
  .word screen_1_action4                     ; s1s2 action4                     [42,43]
  .word screen_1_description                 ; s1s2 description                 [44,45]
  .word screen_1_ascii                       ; s1s2 ascii                       [46,47]
  .word screen_1_flashlight_on               ; s1s2 flashlight_on               [48,49]
  .word screen_1_flashlight_off              ; s1s2 flashlight_off              [50,51]
  .word screen_1_enemy_probability           ; s1s2 enemy_probability           [52,53]
  .word screen_1_is_secret_screen            ; s1s2 is_secret_screen            [54,55]
  .word screen_1_is_end_screen               ; s1s2 is_end_screen               [56,57]
  .word screen_1_description_compressed      ; s1s2 description_compressed      [58,59]
  .word screen_1_flashlight_on_compressed    ; s1s2 flashlight_on_compressed    [60,61]
  .word screen_1_flashlight_off_compressed   ; s1s2 flashlight_off_compressed   [62,63]
screen_pointers_2:
  .word screen_2_id                          ; s1s3 id                          [64,65]
  .word screen_2_name                        ; s1s3 name                        [66,67]
  .word screen_2_action1                     ; s1s3 action1                     [68,69]
  .word screen_2_action2                     ; s1s3 action2                     [70,71]
  .word screen_2_action3                     ; s1s3 action3                     [72,73]
  .word screen_2_action4                     ; s1s3 action4                     [74,75]
  .word screen_2_description                 ; s1s3 description                 [76,77]
  .word screen_2_ascii                       ; s1s3 ascii                       [78,79]
  .word screen_2_flashlight_on               ; s1s3 flashlight_on               [80,81]
  .word screen_2_flashlight_off              ; s1s3 flashlight_off              [82,83]
  .word screen_2_enemy_probability           ; s1s3 enemy_probability           [84,85]
  .word screen_2_is_secret_screen            ; s1s3 is_secret_screen            [86,87]
  .word screen_2_is_end_screen               ; s1s3 is_end_screen               [88,89]
  .word screen_2_description_compressed      ; s1s3 description_compressed      [90,91]
  .word screen_2_flashlight_on_compressed    ; s1s3 flashlight_on_compressed    [92,93]
  .word screen_2_flashlight_off_compressed   ; s1s3 flashlight_off_compressed   [94,95]
screen_pointers_3:
  .word screen_3_id                          ; startScreen id                          [96,97]
  .word screen_3_name                        ; startScreen name                        [98,99]
  .word screen_3_action1                     ; startScreen action1                     [100,101]
  .word screen_3_action2                     ; startScreen action2                     [102,103]
  .word screen_3_action3                     ; startScreen action3                     [104,105]
  .word screen_3_action4                     ; startScreen action4                     [106,107]
  .word screen_3_description                 ; startScreen description                 [108,109]
  .word screen_3_ascii                       ; startScreen ascii                       [110,111]
  .word screen_3_flashlight_on               ; startScreen flashlight_on               [112,113]
  .word screen_3_flashlight_off              ; startScreen flashlight_off              [114,115]
  .word screen_3_enemy_probability           ; startScreen enemy_probability           [116,117]
  .word screen_3_is_secret_screen            ; startScreen is_secret_screen            [118,119]
  .word screen_3_is_end_screen               ; startScreen is_end_screen               [120,121]
  .word screen_3_description_compressed      ; startScreen description_compressed      [122,123]
  .word screen_3_flashlight_on_compressed    ; startScreen flashlight_on_compressed    [124,125]
  .word screen_3_flashlight_off_compressed   ; startScreen flashlight_off_compressed   [126,127]
screen_pointers_4:
  .word screen_4_id                          ; endScreens1s1 id                          [128,129]
  .word screen_4_name                        ; endScreens1s1 name                        [130,131]
  .word screen_4_action1                     ; endScreens1s1 action1                     [132,133]
  .word screen_4_action2                     ; endScreens1s1 action2                     [134,135]
  .word screen_4_action3                     ; endScreens1s1 action3                     [136,137]
  .word screen_4_action4                     ; endScreens1s1 action4                     [138,139]
  .word screen_4_description                 ; endScreens1s1 description                 [140,141]
  .word screen_4_ascii                       ; endScreens1s1 ascii                       [142,143]
  .word screen_4_flashlight_on               ; endScreens1s1 flashlight_on               [144,145]
  .word screen_4_flashlight_off              ; endScreens1s1 flashlight_off              [146,147]
  .word screen_4_enemy_probability           ; endScreens1s1 enemy_probability           [148,149]
  .word screen_4_is_secret_screen            ; endScreens1s1 is_secret_screen            [150,151]
  .word screen_4_is_end_screen               ; endScreens1s1 is_end_screen               [152,153]
  .word screen_4_description_compressed      ; endScreens1s1 description_compressed      [154,155]
  .word screen_4_flashlight_on_compressed    ; endScreens1s1 flashlight_on_compressed    [156,157]
  .word screen_4_flashlight_off_compressed   ; endScreens1s1 flashlight_off_compressed   [158,159]
screen_pointers_5:
  .word screen_5_id                          ; endScreenDefault id                          [160,161]
  .word screen_5_name                        ; endScreenDefault name                        [162,163]
  .word screen_5_action1                     ; endScreenDefault action1                     [164,165]
  .word screen_5_action2                     ; endScreenDefault action2                     [166,167]
  .word screen_5_action3                     ; endScreenDefault action3                     [168,169]
  .word screen_5_action4                     ; endScreenDefault action4                     [170,171]
  .word screen_5_description                 ; endScreenDefault description                 [172,173]
  .word screen_5_ascii                       ; endScreenDefault ascii                       [174,175]
  .word screen_5_flashlight_on               ; endScreenDefault flashlight_on               [176,177]
  .word screen_5_flashlight_off              ; endScreenDefault flashlight_off              [178,179]
  .word screen_5_enemy_probability           ; endScreenDefault enemy_probability           [180,181]
  .word screen_5_is_secret_screen            ; endScreenDefault is_secret_screen            [182,183]
  .word screen_5_is_end_screen               ; endScreenDefault is_end_screen               [184,185]
  .word screen_5_description_compressed      ; endScreenDefault description_compressed      [186,187]
  .word screen_5_flashlight_on_compressed    ; endScreenDefault flashlight_on_compressed    [188,189]
  .word screen_5_flashlight_off_compressed   ; endScreenDefault flashlight_off_compressed   [190,191]
screen_pointers_6:
  .word screen_6_id                          ; s1s4 id                          [192,193]
  .word screen_6_name                        ; s1s4 name                        [194,195]
  .word screen_6_action1                     ; s1s4 action1                     [196,197]
  .word screen_6_action2                     ; s1s4 action2                     [198,199]
  .word screen_6_action3                     ; s1s4 action3                     [200,201]
  .word screen_6_action4                     ; s1s4 action4                     [202,203]
  .word screen_6_description                 ; s1s4 description                 [204,205]
  .word screen_6_ascii                       ; s1s4 ascii                       [206,207]
  .word screen_6_flashlight_on               ; s1s4 flashlight_on               [208,209]
  .word screen_6_flashlight_off              ; s1s4 flashlight_off              [210,211]
  .word screen_6_enemy_probability           ; s1s4 enemy_probability           [212,213]
  .word screen_6_is_secret_screen            ; s1s4 is_secret_screen            [214,215]
  .word screen_6_is_end_screen               ; s1s4 is_end_screen               [216,217]
  .word screen_6_description_compressed      ; s1s4 description_compressed      [218,219]
  .word screen_6_flashlight_on_compressed    ; s1s4 flashlight_on_compressed    [220,221]
  .word screen_6_flashlight_off_compressed   ; s1s4 flashlight_off_compressed   [222,223]
screen_pointers_7:
  .word screen_7_id                          ; s1s5 id                          [224,225]
  .word screen_7_name                        ; s1s5 name                        [226,227]
  .word screen_7_action1                     ; s1s5 action1                     [228,229]
  .word screen_7_action2                     ; s1s5 action2                     [230,231]
  .word screen_7_action3                     ; s1s5 action3                     [232,233]
  .word screen_7_action4                     ; s1s5 action4                     [234,235]
  .word screen_7_description                 ; s1s5 description                 [236,237]
  .word screen_7_ascii                       ; s1s5 ascii                       [238,239]
  .word screen_7_flashlight_on               ; s1s5 flashlight_on               [240,241]
  .word screen_7_flashlight_off              ; s1s5 flashlight_off              [242,243]
  .word screen_7_enemy_probability           ; s1s5 enemy_probability           [244,245]
  .word screen_7_is_secret_screen            ; s1s5 is_secret_screen            [246,247]
  .word screen_7_is_end_screen               ; s1s5 is_end_screen               [248,249]
  .word screen_7_description_compressed      ; s1s5 description_compressed      [250,251]
  .word screen_7_flashlight_on_compressed    ; s1s5 flashlight_on_compressed    [252,253]
  .word screen_7_flashlight_off_compressed   ; s1s5 flashlight_off_compressed   [254,255]
screen_pointers_8:
  .word screen_8_id                          ; endScreens1s4 id                          [256,257]
  .word screen_8_name                        ; endScreens1s4 name                        [258,259]
  .word screen_8_action1                     ; endScreens1s4 action1                     [260,261]
  .word screen_8_action2                     ; endScreens1s4 action2                     [262,263]
  .word screen_8_action3                     ; endScreens1s4 action3                     [264,265]
  .word screen_8_action4                     ; endScreens1s4 action4                     [266,267]
  .word screen_8_description                 ; endScreens1s4 description                 [268,269]
  .word screen_8_ascii                       ; endScreens1s4 ascii                       [270,271]
  .word screen_8_flashlight_on               ; endScreens1s4 flashlight_on               [272,273]
  .word screen_8_flashlight_off              ; endScreens1s4 flashlight_off              [274,275]
  .word screen_8_enemy_probability           ; endScreens1s4 enemy_probability           [276,277]
  .word screen_8_is_secret_screen            ; endScreens1s4 is_secret_screen            [278,279]
  .word screen_8_is_end_screen               ; endScreens1s4 is_end_screen               [280,281]
  .word screen_8_description_compressed      ; endScreens1s4 description_compressed      [282,283]
  .word screen_8_flashlight_on_compressed    ; endScreens1s4 flashlight_on_compressed    [284,285]
  .word screen_8_flashlight_off_compressed   ; endScreens1s4 flashlight_off_compressed   [286,287]
screen_pointers_9:
  .word screen_9_id                          ; s2s1 id                          [288,289]
  .word screen_9_name                        ; s2s1 name                        [290,291]
  .word screen_9_action1                     ; s2s1 action1                     [292,293]
  .word screen_9_action2                     ; s2s1 action2                     [294,295]
  .word screen_9_action3                     ; s2s1 action3                     [296,297]
  .word screen_9_action4                     ; s2s1 action4                     [298,299]
  .word screen_9_description                 ; s2s1 description                 [300,301]
  .word screen_9_ascii                       ; s2s1 ascii                       [302,303]
  .word screen_9_flashlight_on               ; s2s1 flashlight_on               [304,305]
  .word screen_9_flashlight_off              ; s2s1 flashlight_off              [306,307]
  .word screen_9_enemy_probability           ; s2s1 enemy_probability           [308,309]
  .word screen_9_is_secret_screen            ; s2s1 is_secret_screen            [310,311]
  .word screen_9_is_end_screen               ; s2s1 is_end_screen               [312,313]
  .word screen_9_description_compressed      ; s2s1 description_compressed      [314,315]
  .word screen_9_flashlight_on_compressed    ; s2s1 flashlight_on_compressed    [316,317]
  .word screen_9_flashlight_off_compressed   ; s2s1 flashlight_off_compressed   [318,319]
screen_pointers_10:
  .word screen_10_id                          ; EndScreenSimulationTimeisUp id                          [320,321]
  .word screen_10_name                        ; EndScreenSimulationTimeisUp name                        [322,323]
  .word screen_10_action1                     ; EndScreenSimulationTimeisUp action1                     [324,325]
  .word screen_10_action2                     ; EndScreenSimulationTimeisUp action2                     [326,327]
  .word screen_10_action3                     ; EndScreenSimulationTimeisUp action3                     [328,329]
  .word screen_10_action4                     ; EndScreenSimulationTimeisUp action4                     [330,331]
  .word screen_10_description                 ; EndScreenSimulationTimeisUp description                 [332,333]
  .word screen_10_ascii                       ; EndScreenSimulationTimeisUp ascii                       [334,335]
  .word screen_10_flashlight_on               ; EndScreenSimulationTimeisUp flashlight_on               [336,337]
  .word screen_10_flashlight_off              ; EndScreenSimulationTimeisUp flashlight_off              [338,339]
  .word screen_10_enemy_probability           ; EndScreenSimulationTimeisUp enemy_probability           [340,341]
  .word screen_10_is_secret_screen            ; EndScreenSimulationTimeisUp is_secret_screen            [342,343]
  .word screen_10_is_end_screen               ; EndScreenSimulationTimeisUp is_end_screen               [344,345]
  .word screen_10_description_compressed      ; EndScreenSimulationTimeisUp description_compressed      [346,347]
  .word screen_10_flashlight_on_compressed    ; EndScreenSimulationTimeisUp flashlight_on_compressed    [348,349]
  .word screen_10_flashlight_off_compressed   ; EndScreenSimulationTimeisUp flashlight_off_compressed   [350,351]
screen_pointers_11:
  .word screen_11_id                          ; endScreenByEnemy id                          [352,353]
  .word screen_11_name                        ; endScreenByEnemy name                        [354,355]
  .word screen_11_action1                     ; endScreenByEnemy action1                     [356,357]
  .word screen_11_action2                     ; endScreenByEnemy action2                     [358,359]
  .word screen_11_action3                     ; endScreenByEnemy action3                     [360,361]
  .word screen_11_action4                     ; endScreenByEnemy action4                     [362,363]
  .word screen_11_description                 ; endScreenByEnemy description                 [364,365]
  .word screen_11_ascii                       ; endScreenByEnemy ascii                       [366,367]
  .word screen_11_flashlight_on               ; endScreenByEnemy flashlight_on               [368,369]
  .word screen_11_flashlight_off              ; endScreenByEnemy flashlight_off              [370,371]
  .word screen_11_enemy_probability           ; endScreenByEnemy enemy_probability           [372,373]
  .word screen_11_is_secret_screen            ; endScreenByEnemy is_secret_screen            [374,375]
  .word screen_11_is_end_screen               ; endScreenByEnemy is_end_screen               [376,377]
  .word screen_11_description_compressed      ; endScreenByEnemy description_compressed      [378,379]
  .word screen_11_flashlight_on_compressed    ; endScreenByEnemy flashlight_on_compressed    [380,381]
  .word screen_11_flashlight_off_compressed   ; endScreenByEnemy flashlight_off_compressed   [382,383]
screen_pointers_12:
  .word screen_12_id                          ; endScreenByActionFailed id                          [384,385]
  .word screen_12_name                        ; endScreenByActionFailed name                        [386,387]
  .word screen_12_action1                     ; endScreenByActionFailed action1                     [388,389]
  .word screen_12_action2                     ; endScreenByActionFailed action2                     [390,391]
  .word screen_12_action3                     ; endScreenByActionFailed action3                     [392,393]
  .word screen_12_action4                     ; endScreenByActionFailed action4                     [394,395]
  .word screen_12_description                 ; endScreenByActionFailed description                 [396,397]
  .word screen_12_ascii                       ; endScreenByActionFailed ascii                       [398,399]
  .word screen_12_flashlight_on               ; endScreenByActionFailed flashlight_on               [400,401]
  .word screen_12_flashlight_off              ; endScreenByActionFailed flashlight_off              [402,403]
  .word screen_12_enemy_probability           ; endScreenByActionFailed enemy_probability           [404,405]
  .word screen_12_is_secret_screen            ; endScreenByActionFailed is_secret_screen            [406,407]
  .word screen_12_is_end_screen               ; endScreenByActionFailed is_end_screen               [408,409]
  .word screen_12_description_compressed      ; endScreenByActionFailed description_compressed      [410,411]
  .word screen_12_flashlight_on_compressed    ; endScreenByActionFailed flashlight_on_compressed    [412,413]
  .word screen_12_flashlight_off_compressed   ; endScreenByActionFailed flashlight_off_compressed   [414,415]
screen_action_offset:
  .byte 4  ; (byte of screen_0_action1 in screens_pointers)
screen_description_offset:
  .byte 12  ; (byte of screen_0_description in screens_pointers)
screen_ascii_offset:
  .byte 14  ; (byte of screen_0_ascii in screens_pointers)
screen_flashlight_on_offset:
  .byte 16  ; (byte of screen_0_flashlight_on in screens_pointers)
screen_flashlight_off_offset:
  .byte 18  ; (byte of screen_0_flashlight_off in screens_pointers)
screen_enemy_probability_offset:
  .byte 20  ; (byte of screen_0_enemy_probability in screens_pointers)
screen_is_secret_screen_offset:
  .byte 22  ; (byte of screen_0_is_secret_screen in screens_pointers)
screen_is_end_screen_offset:
  .byte 24  ; (byte of screen_0_is_end_screen in screens_pointers)
screen_description_compressed_offset:
  .byte 26  ; (byte of screen_0_description_compressed in screens_pointers)
screen_flashlight_on_compressed_offset:
  .byte 28  ; (byte of screen_0_flashlight_on_compressed in screens_pointers)
screen_flashlight_off_compressed_offset:
  .byte 30  ; (byte of screen_0_flashlight_off_compressed in screens_pointers)
screen_record_length:
  .byte 32  ; (total .word bytes per screen record)

; ── Screen 0: s1s1 ──────────────────────────
screen_0_id:
  .byte 0

screen_0_name:
  .ascii "s1s1"
  .byte $00  ; end-of-string sentinel

screen_0_action1:
  .byte 0  ; LEVANTARSE

screen_0_action2:
  .byte 1  ; MIRAR ALREDEDOR

screen_0_action3:
  .byte 2  ; GRITAR POR AYUDA

screen_0_action4:
  .byte 13  ; MUERTE DIRECTA

screen_0_description:
  .ascii "Despiertas sobre piedra húmeda."
  .byte $0A  ; \n
  .ascii "La caverna se cerro detrás de ti. "
  .byte $0A  ; \n
  .ascii "Un derrumbe de rocas antiguas, pesadas, acomodadas como si el colapso hubiera si"
  .ascii "do final, no accidental."
  .byte $0A  ; \n
  .ascii "El frío no duele todavía. "
  .byte $0A  ; \n
  .ascii "Sientes un constante goteo de agua, cada vez mas cerca de ti."
  .byte $00  ; end-of-string sentinel

screen_0_description_compressed:
  .word token_0  ; "Despiertas "
  .word token_1  ; "sobre "
  .word token_2  ; "piedra "
  .word token_3  ; "húmeda.\n"
  .word token_4  ; "La "
  .word token_5  ; "caverna "
  .word token_6  ; "se "
  .word token_7  ; "cerro "
  .word token_8  ; "detrás "
  .word token_9  ; "de "
  .word token_10  ; "ti. \n"
  .word token_11  ; "Un "
  .word token_12  ; "derrumbe "
  .word token_9  ; "de "
  .word token_13  ; "rocas "
  .word token_14  ; "antiguas, "
  .word token_15  ; "pesadas, "
  .word token_16  ; "acomodadas "
  .word token_17  ; "como "
  .word token_18  ; "si "
  .word token_19  ; "el "
  .word token_20  ; "colapso "
  .word token_21  ; "hubiera "
  .word token_22  ; "sido "
  .word token_23  ; "final, "
  .word token_24  ; "no "
  .word token_25  ; "accidental.\n"
  .word token_26  ; "El "
  .word token_27  ; "frío "
  .word token_24  ; "no "
  .word token_28  ; "duele "
  .word token_29  ; "todavía. \n"
  .word token_30  ; "Sientes "
  .word token_31  ; "un "
  .word token_32  ; "constante "
  .word token_33  ; "goteo "
  .word token_9  ; "de "
  .word token_34  ; "agua, "
  .word token_35  ; "cada "
  .word token_36  ; "vez "
  .word token_37  ; "mas "
  .word token_38  ; "cerca "
  .word token_9  ; "de "
  .word token_39  ; "ti."
  .word $FFFF  ; end sentinel

screen_0_ascii:
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#########░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#         ##░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#             #░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#                ##░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░░######                   #####░░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░░░#     #                   #    #░░░░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░##     #                     #  # ###░░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░░#     #                      # #     #░░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░░░#    #########                #####    #░░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░░#######         #       ########      #   #░░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░░░#                 #######     ##        #   #░░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░░##                  ##           ##        #   #░░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░░░#                     ###           #       ######░░░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░░##                      ##             ##     ###   ##░░░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░░░#####                    #                #   ##       ##░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░░#      #    ####         ###                ###            #░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░#        ## #    #       #########        ###  #            #░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░#          ##      #   ###         ##     #   ########       #░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░#         #         ###              ##  #####        ##      #░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░#        #            #                ##              ##    #░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░#       #              #               #                ##   #░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░░#     #                #             #                  #  #░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░░##    #                 #            #                    # #░░░░░░░░░░"
  .byte $0A  ; \n
  .ascii "░░░░░░░░##    ##                 ##            #                  #   #░░░░░░░░░"
  .byte $00  ; end-of-string sentinel

screen_0_flashlight_on:
  .byte $0A  ; \n
  .byte $00  ; end-of-string sentinel

screen_0_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_0_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_0_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_0_enemy_probability:
  .byte 33

screen_0_is_secret_screen:
  .byte 0  ; no

screen_0_is_end_screen:
  .byte 0  ; no

; ── Screen 1: s1s2 ──────────────────────────
screen_1_id:
  .byte 1

screen_1_name:
  .ascii "s1s2"
  .byte $00  ; end-of-string sentinel

screen_1_action1:
  .byte 7  ; VEO QUE CAE AGUA

screen_1_action2:
  .byte 255  ; none

screen_1_action3:
  .byte 255  ; none

screen_1_action4:
  .byte 255  ; none

screen_1_description:
  .ascii "Al levantarte, miras a tu alrededor."
  .byte $0A  ; \n
  .ascii "Ves que el agua gotea lenta, pero constantemente, inundando la caverna."
  .byte $0A  ; \n
  .ascii "Como si midiera el tiempo."
  .byte $00  ; end-of-string sentinel

screen_1_description_compressed:
  .word token_40  ; "Al "
  .word token_41  ; "levantarte, "
  .word token_42  ; "miras "
  .word token_43  ; "a "
  .word token_44  ; "tu "
  .word token_45  ; "alrededor.\n"
  .word token_46  ; "Ves "
  .word token_47  ; "que "
  .word token_19  ; "el "
  .word token_48  ; "agua "
  .word token_49  ; "gotea "
  .word token_50  ; "lenta, "
  .word token_51  ; "pero "
  .word token_52  ; "constantemente, "
  .word token_53  ; "inundando "
  .word token_54  ; "la "
  .word token_55  ; "caverna.\n"
  .word token_56  ; "Como "
  .word token_18  ; "si "
  .word token_57  ; "midiera "
  .word token_19  ; "el "
  .word token_58  ; "tiempo."
  .word $FFFF  ; end sentinel

screen_1_ascii:
  .byte $00  ; end-of-string sentinel

screen_1_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_1_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_1_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_1_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_1_enemy_probability:
  .byte 0

screen_1_is_secret_screen:
  .byte 0  ; no

screen_1_is_end_screen:
  .byte 0  ; no

; ── Screen 2: s1s3 ──────────────────────────
screen_2_id:
  .byte 2

screen_2_name:
  .ascii "s1s3"
  .byte $00  ; end-of-string sentinel

screen_2_action1:
  .byte 3  ; MIRAR ENTRADA

screen_2_action2:
  .byte 5  ; LINTERNA

screen_2_action3:
  .byte 6  ; EXPLORAR CAMINO

screen_2_action4:
  .byte 4  ; GRITAR

screen_2_description:
  .ascii "La caverna se abre en una cámara amplia pero baja. "
  .byte $0A  ; \n
  .ascii "El techo parece aplastarte con su peso, estalactitas afiladas cuelgan peligrosam"
  .ascii "ente del mismo. "
  .byte $0A  ; \n
  .ascii "Las paredes son rugosas, húmedas al tacto, y reflejan una luz apagada que no tie"
  .ascii "ne fuente clara. "
  .byte $0A  ; \n
  .ascii "El aire es frío y estancado. "
  .byte $0A  ; \n
  .ascii "Huele a roca mojada y a algo más viejo, casi orgánico. "
  .byte $0A  ; \n
  .ascii "El suelo tiene marcas irregulares, como pasos interrumpidos en un camino que se "
  .ascii "pierde en la oscuridad"
  .byte $0A  ; \n
  .ascii "Siente que algo o alguien puede estar acechando"
  .byte $00  ; end-of-string sentinel

screen_2_description_compressed:
  .word token_4  ; "La "
  .word token_5  ; "caverna "
  .word token_6  ; "se "
  .word token_59  ; "abre "
  .word token_60  ; "en "
  .word token_61  ; "una "
  .word token_62  ; "cámara "
  .word token_63  ; "amplia "
  .word token_51  ; "pero "
  .word token_64  ; "baja. \n"
  .word token_26  ; "El "
  .word token_65  ; "techo "
  .word token_66  ; "parece "
  .word token_67  ; "aplastarte "
  .word token_68  ; "con "
  .word token_69  ; "su "
  .word token_70  ; "peso, "
  .word token_71  ; "estalactitas "
  .word token_72  ; "afiladas "
  .word token_73  ; "cuelgan "
  .word token_74  ; "peligrosamente "
  .word token_75  ; "del "
  .word token_76  ; "mismo. \n"
  .word token_77  ; "Las "
  .word token_78  ; "paredes "
  .word token_79  ; "son "
  .word token_80  ; "rugosas, "
  .word token_81  ; "húmedas "
  .word token_82  ; "al "
  .word token_83  ; "tacto, "
  .word token_84  ; "y "
  .word token_85  ; "reflejan "
  .word token_61  ; "una "
  .word token_86  ; "luz "
  .word token_87  ; "apagada "
  .word token_47  ; "que "
  .word token_24  ; "no "
  .word token_88  ; "tiene "
  .word token_89  ; "fuente "
  .word token_90  ; "clara. \n"
  .word token_26  ; "El "
  .word token_91  ; "aire "
  .word token_92  ; "es "
  .word token_27  ; "frío "
  .word token_84  ; "y "
  .word token_93  ; "estancado. \n"
  .word token_94  ; "Huele "
  .word token_43  ; "a "
  .word token_95  ; "roca "
  .word token_96  ; "mojada "
  .word token_84  ; "y "
  .word token_43  ; "a "
  .word token_97  ; "algo "
  .word token_98  ; "más "
  .word token_99  ; "viejo, "
  .word token_100  ; "casi "
  .word token_101  ; "orgánico. \n"
  .word token_26  ; "El "
  .word token_102  ; "suelo "
  .word token_88  ; "tiene "
  .word token_103  ; "marcas "
  .word token_104  ; "irregulares, "
  .word token_17  ; "como "
  .word token_105  ; "pasos "
  .word token_106  ; "interrumpidos "
  .word token_60  ; "en "
  .word token_31  ; "un "
  .word token_107  ; "camino "
  .word token_47  ; "que "
  .word token_6  ; "se "
  .word token_108  ; "pierde "
  .word token_60  ; "en "
  .word token_54  ; "la "
  .word token_109  ; "oscuridad\n"
  .word token_110  ; "Siente "
  .word token_47  ; "que "
  .word token_97  ; "algo "
  .word token_111  ; "o "
  .word token_112  ; "alguien "
  .word token_113  ; "puede "
  .word token_114  ; "estar "
  .word token_115  ; "acechando"
  .word $FFFF  ; end sentinel

screen_2_ascii:
  .byte $00  ; end-of-string sentinel

screen_2_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_2_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_2_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_2_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_2_enemy_probability:
  .byte 1

screen_2_is_secret_screen:
  .byte 0  ; no

screen_2_is_end_screen:
  .byte 0  ; no

; ── Screen 3: startScreen ──────────────────────────
screen_3_id:
  .byte 3

screen_3_name:
  .ascii "startScreen"
  .byte $00  ; end-of-string sentinel

screen_3_action1:
  .byte 1  ; MIRAR ALREDEDOR

screen_3_action2:
  .byte 14  ; TIRAR AGUAR, EMPEZAR TIME

screen_3_action3:
  .byte 5  ; LINTERNA

screen_3_action4:
  .byte 4  ; GRITAR

screen_3_description:
  .ascii "Bienvenido a la aventura gráfica más Espectacular del mundo"
  .byte $00  ; end-of-string sentinel

screen_3_description_compressed:
  .word token_116  ; "Bienvenido "
  .word token_43  ; "a "
  .word token_54  ; "la "
  .word token_117  ; "aventura "
  .word token_118  ; "gráfica "
  .word token_98  ; "más "
  .word token_119  ; "Espectacular "
  .word token_75  ; "del "
  .word token_120  ; "mundo"
  .word $FFFF  ; end sentinel

screen_3_ascii:
  .byte $00  ; end-of-string sentinel

screen_3_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_3_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_3_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_3_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_3_enemy_probability:
  .byte 2

screen_3_is_secret_screen:
  .byte 0  ; no

screen_3_is_end_screen:
  .byte 0  ; no

; ── Screen 4: endScreens1s1 ──────────────────────────
screen_4_id:
  .byte 4

screen_4_name:
  .ascii "endScreens1s1"
  .byte $00  ; end-of-string sentinel

screen_4_action1:
  .byte 9  ; TERMINAR EL JUEGO

screen_4_action2:
  .byte 255  ; none

screen_4_action3:
  .byte 255  ; none

screen_4_action4:
  .byte 255  ; none

screen_4_description:
  .ascii "El constante goteo era hipnotico. Gota, pausa, gota. El agua comenzo a entumecer"
  .ascii " tus extremidades hasta que dejaste de sentirlas. Un eterno sueño te dio la bien"
  .ascii "venida."
  .byte $00  ; end-of-string sentinel

screen_4_description_compressed:
  .word token_26  ; "El "
  .word token_32  ; "constante "
  .word token_33  ; "goteo "
  .word token_121  ; "era "
  .word token_122  ; "hipnotico. "
  .word token_123  ; "Gota, "
  .word token_124  ; "pausa, "
  .word token_125  ; "gota. "
  .word token_26  ; "El "
  .word token_48  ; "agua "
  .word token_126  ; "comenzo "
  .word token_43  ; "a "
  .word token_127  ; "entumecer "
  .word token_128  ; "tus "
  .word token_129  ; "extremidades "
  .word token_130  ; "hasta "
  .word token_47  ; "que "
  .word token_131  ; "dejaste "
  .word token_9  ; "de "
  .word token_132  ; "sentirlas. "
  .word token_11  ; "Un "
  .word token_133  ; "eterno "
  .word token_134  ; "sueño "
  .word token_135  ; "te "
  .word token_136  ; "dio "
  .word token_54  ; "la "
  .word token_137  ; "bienvenida."
  .word $FFFF  ; end sentinel

screen_4_ascii:
  .byte $00  ; end-of-string sentinel

screen_4_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_4_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_4_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_4_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_4_enemy_probability:
  .byte 0

screen_4_is_secret_screen:
  .byte 0  ; no

screen_4_is_end_screen:
  .byte 0  ; no

; ── Screen 5: endScreenDefault ──────────────────────────
screen_5_id:
  .byte 5

screen_5_name:
  .ascii "endScreenDefault"
  .byte $00  ; end-of-string sentinel

screen_5_action1:
  .byte 9  ; TERMINAR EL JUEGO

screen_5_action2:
  .byte 255  ; none

screen_5_action3:
  .byte 255  ; none

screen_5_action4:
  .byte 255  ; none

screen_5_description:
  .ascii "Asi terminas tus dias atrapado en la Caverna"
  .byte $00  ; end-of-string sentinel

screen_5_description_compressed:
  .word token_138  ; "Asi "
  .word token_139  ; "terminas "
  .word token_128  ; "tus "
  .word token_140  ; "dias "
  .word token_141  ; "atrapado "
  .word token_60  ; "en "
  .word token_54  ; "la "
  .word token_142  ; "Caverna"
  .word $FFFF  ; end sentinel

screen_5_ascii:
  .byte $00  ; end-of-string sentinel

screen_5_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_5_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_5_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_5_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_5_enemy_probability:
  .byte 0

screen_5_is_secret_screen:
  .byte 0  ; no

screen_5_is_end_screen:
  .byte 1  ; yes

; ── Screen 6: s1s4 ──────────────────────────
screen_6_id:
  .byte 6

screen_6_name:
  .ascii "s1s4"
  .byte $00  ; end-of-string sentinel

screen_6_action1:
  .byte 10  ; EXPLORAR MARCAS

screen_6_action2:
  .byte 11  ; FORZAR ENTRADA

screen_6_action3:
  .byte 12  ; VOLVER A MIRAR ADELANTE

screen_6_action4:
  .byte 255  ; none

screen_6_description:
  .ascii "Entre las rocas hay rendijas por donde entra aire viciado, pero ninguna lo basta"
  .ascii "nte grande para pasar. Hay marcas irregulares, como si alguien hubiera intentado"
  .ascii " moverlas y se hubiera detenido a mitad de camino. Tal vez no sea una opcion vol"
  .ascii "ver por ahí, pero la idea de explorar una caverna a oscuras no parece tentadora."
  .byte $00  ; end-of-string sentinel

screen_6_description_compressed:
  .word token_143  ; "Entre "
  .word token_144  ; "las "
  .word token_13  ; "rocas "
  .word token_145  ; "hay "
  .word token_146  ; "rendijas "
  .word token_147  ; "por "
  .word token_148  ; "donde "
  .word token_149  ; "entra "
  .word token_91  ; "aire "
  .word token_150  ; "viciado, "
  .word token_51  ; "pero "
  .word token_151  ; "ninguna "
  .word token_152  ; "lo "
  .word token_153  ; "bastante "
  .word token_154  ; "grande "
  .word token_155  ; "para "
  .word token_156  ; "pasar. "
  .word token_157  ; "Hay "
  .word token_103  ; "marcas "
  .word token_104  ; "irregulares, "
  .word token_17  ; "como "
  .word token_18  ; "si "
  .word token_112  ; "alguien "
  .word token_21  ; "hubiera "
  .word token_158  ; "intentado "
  .word token_159  ; "moverlas "
  .word token_84  ; "y "
  .word token_6  ; "se "
  .word token_21  ; "hubiera "
  .word token_160  ; "detenido "
  .word token_43  ; "a "
  .word token_161  ; "mitad "
  .word token_9  ; "de "
  .word token_162  ; "camino. "
  .word token_163  ; "Tal "
  .word token_36  ; "vez "
  .word token_24  ; "no "
  .word token_164  ; "sea "
  .word token_61  ; "una "
  .word token_165  ; "opcion "
  .word token_166  ; "volver "
  .word token_147  ; "por "
  .word token_167  ; "ahí, "
  .word token_51  ; "pero "
  .word token_54  ; "la "
  .word token_168  ; "idea "
  .word token_9  ; "de "
  .word token_169  ; "explorar "
  .word token_61  ; "una "
  .word token_5  ; "caverna "
  .word token_43  ; "a "
  .word token_170  ; "oscuras "
  .word token_24  ; "no "
  .word token_66  ; "parece "
  .word token_171  ; "tentadora."
  .word $FFFF  ; end sentinel

screen_6_ascii:
  .byte $00  ; end-of-string sentinel

screen_6_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_6_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_6_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_6_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_6_enemy_probability:
  .byte 0

screen_6_is_secret_screen:
  .byte 0  ; no

screen_6_is_end_screen:
  .byte 0  ; no

; ── Screen 7: s1s5 ──────────────────────────
screen_7_id:
  .byte 7

screen_7_name:
  .ascii "s1s5"
  .byte $00  ; end-of-string sentinel

screen_7_action1:
  .byte 12  ; VOLVER A MIRAR ADELANTE

screen_7_action2:
  .byte 255  ; none

screen_7_action3:
  .byte 255  ; none

screen_7_action4:
  .byte 255  ; none

screen_7_description:
  .ascii "Este es el PITFALL"
  .byte $00  ; end-of-string sentinel

screen_7_description_compressed:
  .word token_172  ; "Este "
  .word token_92  ; "es "
  .word token_19  ; "el "
  .word token_173  ; "PITFALL"
  .word $FFFF  ; end sentinel

screen_7_ascii:
  .byte $00  ; end-of-string sentinel

screen_7_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_7_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_7_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_7_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_7_enemy_probability:
  .byte 0

screen_7_is_secret_screen:
  .byte 1  ; yes

screen_7_is_end_screen:
  .byte 0  ; no

; ── Screen 8: endScreens1s4 ──────────────────────────
screen_8_id:
  .byte 8

screen_8_name:
  .ascii "endScreens1s4"
  .byte $00  ; end-of-string sentinel

screen_8_action1:
  .byte 9  ; TERMINAR EL JUEGO

screen_8_action2:
  .byte 255  ; none

screen_8_action3:
  .byte 255  ; none

screen_8_action4:
  .byte 255  ; none

screen_8_description:
  .ascii "El suelo comienza a temblar y entrada empieza a desmoronarse sobre ti. Lo ultimo"
  .ascii " que piensas es que no estaban sellando la salida. Estaban sosteniendo el resto"
  .byte $0A  ; \n
  .ascii "Haz muerto"
  .byte $00  ; end-of-string sentinel

screen_8_description_compressed:
  .word token_26  ; "El "
  .word token_102  ; "suelo "
  .word token_174  ; "comienza "
  .word token_43  ; "a "
  .word token_175  ; "temblar "
  .word token_84  ; "y "
  .word token_176  ; "entrada "
  .word token_177  ; "empieza "
  .word token_43  ; "a "
  .word token_178  ; "desmoronarse "
  .word token_1  ; "sobre "
  .word token_179  ; "ti. "
  .word token_180  ; "Lo "
  .word token_181  ; "ultimo "
  .word token_47  ; "que "
  .word token_182  ; "piensas "
  .word token_92  ; "es "
  .word token_47  ; "que "
  .word token_24  ; "no "
  .word token_183  ; "estaban "
  .word token_184  ; "sellando "
  .word token_54  ; "la "
  .word token_185  ; "salida. "
  .word token_186  ; "Estaban "
  .word token_187  ; "sosteniendo "
  .word token_19  ; "el "
  .word token_188  ; "resto\n"
  .word token_189  ; "Haz "
  .word token_190  ; "muerto"
  .word $FFFF  ; end sentinel

screen_8_ascii:
  .byte $00  ; end-of-string sentinel

screen_8_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_8_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_8_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_8_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_8_enemy_probability:
  .byte 0

screen_8_is_secret_screen:
  .byte 0  ; no

screen_8_is_end_screen:
  .byte 0  ; no

; ── Screen 9: s2s1 ──────────────────────────
screen_9_id:
  .byte 9

screen_9_name:
  .ascii "s2s1"
  .byte $00  ; end-of-string sentinel

screen_9_action1:
  .byte 255  ; none

screen_9_action2:
  .byte 255  ; none

screen_9_action3:
  .byte 255  ; none

screen_9_action4:
  .byte 255  ; none

screen_9_description:
  .byte $00  ; end-of-string sentinel

screen_9_description_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_9_ascii:
  .byte $00  ; end-of-string sentinel

screen_9_flashlight_on:
  .ascii "Luego de explorar el pasillo, te encuentras con una sala grande. Dos tuneles se "
  .ascii "abren frente a ti. Decidir en estas condiciones es dificil, pero necesario. El a"
  .ascii "gua sigue subiendo lentamente."
  .byte $00  ; end-of-string sentinel

screen_9_flashlight_on_compressed:
  .word token_191  ; "Luego "
  .word token_9  ; "de "
  .word token_169  ; "explorar "
  .word token_19  ; "el "
  .word token_192  ; "pasillo, "
  .word token_135  ; "te "
  .word token_193  ; "encuentras "
  .word token_68  ; "con "
  .word token_61  ; "una "
  .word token_194  ; "sala "
  .word token_195  ; "grande. "
  .word token_196  ; "Dos "
  .word token_197  ; "tuneles "
  .word token_6  ; "se "
  .word token_198  ; "abren "
  .word token_199  ; "frente "
  .word token_43  ; "a "
  .word token_179  ; "ti. "
  .word token_200  ; "Decidir "
  .word token_60  ; "en "
  .word token_201  ; "estas "
  .word token_202  ; "condiciones "
  .word token_92  ; "es "
  .word token_203  ; "dificil, "
  .word token_51  ; "pero "
  .word token_204  ; "necesario. "
  .word token_26  ; "El "
  .word token_48  ; "agua "
  .word token_205  ; "sigue "
  .word token_206  ; "subiendo "
  .word token_207  ; "lentamente."
  .word $FFFF  ; end sentinel

screen_9_flashlight_off:
  .ascii "A ciegas tanteas la pared del pasillo, hasta que se acaba. Tienes la sensacion d"
  .ascii "e que llegaste a un lugar mas espacioso. Recorres la pared a tientas y encuentra"
  .ascii "s dos grandes huecos. ¿Tal vez sean tuneles?. No te detienes demasiado a pensarl"
  .ascii "o, sientes mas agua en contacto con tu cuerpo."
  .byte $00  ; end-of-string sentinel

screen_9_flashlight_off_compressed:
  .word token_208  ; "A "
  .word token_209  ; "ciegas "
  .word token_210  ; "tanteas "
  .word token_54  ; "la "
  .word token_211  ; "pared "
  .word token_75  ; "del "
  .word token_192  ; "pasillo, "
  .word token_130  ; "hasta "
  .word token_47  ; "que "
  .word token_6  ; "se "
  .word token_212  ; "acaba. "
  .word token_213  ; "Tienes "
  .word token_54  ; "la "
  .word token_214  ; "sensacion "
  .word token_9  ; "de "
  .word token_47  ; "que "
  .word token_215  ; "llegaste "
  .word token_43  ; "a "
  .word token_31  ; "un "
  .word token_216  ; "lugar "
  .word token_37  ; "mas "
  .word token_217  ; "espacioso. "
  .word token_218  ; "Recorres "
  .word token_54  ; "la "
  .word token_211  ; "pared "
  .word token_43  ; "a "
  .word token_219  ; "tientas "
  .word token_84  ; "y "
  .word token_193  ; "encuentras "
  .word token_220  ; "dos "
  .word token_221  ; "grandes "
  .word token_222  ; "huecos. "
  .word token_223  ; "¿Tal "
  .word token_36  ; "vez "
  .word token_224  ; "sean "
  .word token_225  ; "tuneles?. "
  .word token_226  ; "No "
  .word token_135  ; "te "
  .word token_227  ; "detienes "
  .word token_228  ; "demasiado "
  .word token_43  ; "a "
  .word token_229  ; "pensarlo, "
  .word token_230  ; "sientes "
  .word token_37  ; "mas "
  .word token_48  ; "agua "
  .word token_60  ; "en "
  .word token_231  ; "contacto "
  .word token_68  ; "con "
  .word token_44  ; "tu "
  .word token_232  ; "cuerpo."
  .word $FFFF  ; end sentinel

screen_9_enemy_probability:
  .byte 0

screen_9_is_secret_screen:
  .byte 0  ; no

screen_9_is_end_screen:
  .byte 0  ; no

; ── Screen 10: EndScreenSimulationTimeisUp ──────────────────────────
screen_10_id:
  .byte 10

screen_10_name:
  .ascii "EndScreenSimulationTimeisUp"
  .byte $00  ; end-of-string sentinel

screen_10_action1:
  .byte 9  ; TERMINAR EL JUEGO

screen_10_action2:
  .byte 255  ; none

screen_10_action3:
  .byte 255  ; none

screen_10_action4:
  .byte 255  ; none

screen_10_description:
  .ascii "Tardaste Muuuucho y te quedaste sin tiempo....."
  .byte $00  ; end-of-string sentinel

screen_10_description_compressed:
  .word token_233  ; "Tardaste "
  .word token_234  ; "Muuuucho "
  .word token_84  ; "y "
  .word token_135  ; "te "
  .word token_235  ; "quedaste "
  .word token_236  ; "sin "
  .word token_237  ; "tiempo....."
  .word $FFFF  ; end sentinel

screen_10_ascii:
  .byte $00  ; end-of-string sentinel

screen_10_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_10_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_10_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_10_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_10_enemy_probability:
  .byte 0

screen_10_is_secret_screen:
  .byte 0  ; no

screen_10_is_end_screen:
  .byte 1  ; yes

; ── Screen 11: endScreenByEnemy ──────────────────────────
screen_11_id:
  .byte 11

screen_11_name:
  .ascii "endScreenByEnemy"
  .byte $00  ; end-of-string sentinel

screen_11_action1:
  .byte 9  ; TERMINAR EL JUEGO

screen_11_action2:
  .byte 255  ; none

screen_11_action3:
  .byte 255  ; none

screen_11_action4:
  .byte 255  ; none

screen_11_description:
  .ascii "El enemigo que siempre acechaba te atrapó, este es tu fin"
  .byte $00  ; end-of-string sentinel

screen_11_description_compressed:
  .word token_26  ; "El "
  .word token_238  ; "enemigo "
  .word token_47  ; "que "
  .word token_239  ; "siempre "
  .word token_240  ; "acechaba "
  .word token_135  ; "te "
  .word token_241  ; "atrapó, "
  .word token_242  ; "este "
  .word token_92  ; "es "
  .word token_44  ; "tu "
  .word token_243  ; "fin"
  .word $FFFF  ; end sentinel

screen_11_ascii:
  .byte $00  ; end-of-string sentinel

screen_11_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_11_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_11_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_11_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_11_enemy_probability:
  .byte 0

screen_11_is_secret_screen:
  .byte 0  ; no

screen_11_is_end_screen:
  .byte 1  ; yes

; ── Screen 12: endScreenByActionFailed ──────────────────────────
screen_12_id:
  .byte 12

screen_12_name:
  .ascii "endScreenByActionFailed"
  .byte $00  ; end-of-string sentinel

screen_12_action1:
  .byte 9  ; TERMINAR EL JUEGO

screen_12_action2:
  .byte 255  ; none

screen_12_action3:
  .byte 255  ; none

screen_12_action4:
  .byte 255  ; none

screen_12_description:
  .ascii "Tu acción tenía una gran chance de fallar y falló. Este es tu fin"
  .byte $00  ; end-of-string sentinel

screen_12_description_compressed:
  .word token_244  ; "Tu "
  .word token_245  ; "acción "
  .word token_246  ; "tenía "
  .word token_61  ; "una "
  .word token_247  ; "gran "
  .word token_248  ; "chance "
  .word token_9  ; "de "
  .word token_249  ; "fallar "
  .word token_84  ; "y "
  .word token_250  ; "falló. "
  .word token_172  ; "Este "
  .word token_92  ; "es "
  .word token_44  ; "tu "
  .word token_243  ; "fin"
  .word $FFFF  ; end sentinel

screen_12_ascii:
  .byte $00  ; end-of-string sentinel

screen_12_flashlight_on:
  .byte $00  ; end-of-string sentinel

screen_12_flashlight_on_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_12_flashlight_off:
  .byte $00  ; end-of-string sentinel

screen_12_flashlight_off_compressed:
  .word $FFFF  ; end sentinel (empty)

screen_12_enemy_probability:
  .byte 0

screen_12_is_secret_screen:
  .byte 0  ; no

screen_12_is_end_screen:
  .byte 1  ; yes

; ── Total screen count ──────────────────────────────────────
screen_count:
  .byte 13

; ── Total secret screens count ──────────────────────────────
screens_with_secrets:
  .byte 1

; ── Compression stats ─────────────────────────────────────
;  Unique tokens in dictionary: 251
;  Original string bytes (Description+Flashlight fields): 2319
;  Compressed token refs bytes: 814
;  Dictionary overhead bytes: 2520
;  Net with dictionary: 3334 vs 2319 original
;  Savings: -1015 bytes (-43.8%)
