

RS_VIA_BASE  = $7000
RS_PORTB = RS_VIA_BASE + $00
RS_PORTA = RS_VIA_BASE + $01
RS_DDRB =  RS_VIA_BASE + $02
RS_DDRA =  RS_VIA_BASE + $03
RS_PCR =   RS_VIA_BASE + $04
RS_IFR =   RS_VIA_BASE + $05
RS_IER =   RS_VIA_BASE + $06

