

SENSOR_VIA_BASE  = $7000
SENSOR_PORTB = SENSOR_VIA_BASE + $00
SENSOR_PORTA = SENSOR_VIA_BASE + $01
SENSOR_DDRB =  SENSOR_VIA_BASE + $02
SENSOR_DDRA =  SENSOR_VIA_BASE + $03
SENSOR_PCR =   SENSOR_VIA_BASE + $04
SENSOR_IFR =   SENSOR_VIA_BASE + $05
SENSOR_IER =   SENSOR_VIA_BASE + $06

